<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DetailsDescription;

class DetailsDescriptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DetailsDescription::insert([
            [
                'id' => 1,
                'sousTitre1' => 'Performance exceptionnelle du processeur Intel® Core™ i7-1355U',
                'paragraph1' => 'L\'ordinateur tout-en-un HP 24-cr0000nk AIO PC (845P4EA) est propulsé par un processeur Intel® Core™ i7-1355U, offrant des performances exceptionnelles pour une variété de tâches informatiques. Avec une fréquence pouvant atteindre 5,0 GHz grâce à la technologie Intel® Turbo Boost, ce processeur offre une réactivité impressionnante, que ce soit pour la navigation sur le web, le multitâche ou les applications professionnelles exigeantes. Doté de 12 Mo de mémoire cache L3, 10 cœurs et 12 threads, il assure une efficacité énergétique optimisée et une gestion fluide des charges de travail les plus intensives.',
                'sousTitre2' => 'Mémoire RAM DDR4 rapide de 16 Go',
                'paragraph2' => 'Équipé de 16 Go de mémoire RAM DDR4-3200 MHz, le HP 24-cr0000nk AIO PC garantit une réactivité accrue et une performance fluide pour les applications multitâches. Cette quantité de mémoire permet aux utilisateurs de travailler efficacement sur plusieurs programmes simultanément, sans compromettre les performances du système. Que ce soit pour le traitement de données, le montage vidéo ou le jeu, cette mémoire RAM rapide assure une expérience utilisateur sans accroc.',
                'sousTitre3' => 'Stockage rapide et fiable avec SSD PCIe® NVMe™ M.2 de 512 Go',
                'paragraph3' => 'Pour un accès rapide à vos fichiers et programmes, cet ordinateur tout-en-un est équipé d\'un SSD PCIe® NVMe™ M.2 de 512 Go. Ce type de stockage offre des vitesses de lecture et d\'écriture bien supérieures à celles des disques durs traditionnels, garantissant des temps de démarrage rapides et des performances fluides lors du chargement des applications et des fichiers volumineux. En plus d\'offrir une grande capacité de stockage, ce SSD assure également une fiabilité accrue grâce à l\'absence de pièces mobiles.',
                'sousTitre4' => 'Écran tactile Full HD de 23,8 pouces avec technologie IPS',
                'paragraph4' => 'Le HP 24-cr0000nk AIO PC est équipé d\'un écran tactile Full HD de 60,5 cm (23,8 pouces) offrant une résolution de 1920 x 1080 pixels. Avec la technologie IPS, cet écran garantit des couleurs éclatantes et des angles de vision larges, idéaux pour le travail collaboratif et la consommation de contenu multimédia. Les micro-bords sur trois côtés offrent une expérience visuelle immersive, tandis que la luminosité de 300 nits et la surface antireflet assurent un affichage confortable dans toutes les conditions d\'éclairage.',
                'sousTitre5' => 'Carte graphique Intel® Iris® X et Windows 11 Famille',
                'paragraph5' => 'Avec la carte graphique intégrée Intel® Iris® X, cet ordinateur tout-en-un offre des performances graphiques fluides pour les tâches de création de contenu et les jeux légers. En outre, il est préinstallé avec Windows 11 Famille en mode S, offrant une interface utilisateur moderne, des fonctionnalités de sécurité avancées et une suite d\'applications intégrées pour une expérience informatique optimale. Que ce soit pour le travail, les études ou le divertissement, le HP 24-cr0000nk AIO PC offre une combinaison de puissance, de performance et de fonctionnalités pour répondre aux besoins variés des utilisateurs.'
            ],
            [
                'id' => 2,
                'sousTitre1' => 'Compatible Avec Xbox One Et PC',
                'paragraph1' => 'Driving Force est conçu pour les derniers jeux de course sur console Xbox One™. Vous n\'aurez plus envie de revenir à une manette conventionnelle pour les courses de voiture après avoir testé G920 Driving Force. Le volant G920 Driving Force fonctionne également avec une sélection de jeux PC utilisant Logitech - Assistant pour jeux vidéo.',
                'sousTitre2' => 'Retour de force à deux moteurs',
                'paragraph2' => 'Ressentez vos pneus à chaque virage, chaque dérive et sur chaque type de terrain. Le retour de force puissant à deux moteurs simule de manière réaliste les effets de force pour une réponse de précision.',
                'sousTitre3' => 'Conçu pour la distance',
                'paragraph3' => 'Driving Force résiste aux vibrations et offre une fiabilité longue durée. Les roulements à bille dans l\'axe du volant et ses leviers de vitesses et pédales en acier inoxydable font du volant G920 le volant de course idéal pour les longues distances. Le volant est revêtu de cuir de qualité supérieure, cousu main, et procure les sensations ressenties au volant d\'une voiture de course haute performance tout en vous faisant profiter d\'une expérience durable et confortable.',
                'sousTitre4' => 'Engrenage hélicoïdal avec système anti-jeu',
                'paragraph4' => 'L\'engrenage hélicoïdal s\'inspire des systèmes utilisés dans les transmissions automobiles pour réduire le bruit et les vibrations indésirables. Le système anti-jeu permet un bon maintien de la position du volant et des pédales, pour un contrôle optimal. Ce volant offre une conduite souple et silencieuse. Le volant de course Driving Force G920 présente un capteur de direction à effet Hall fiable et longue durée qui détecte la position du volant à l\'aide des champs magnétiques.',
                'sousTitre5' => 'Commandes de jeu d\'accès direct',
                'paragraph5' => 'Soyez maître de la configuration de votre voiture. Le volant de course G920 incorpore la croix directionnelle et les boutons de console dans le volant pour que toutes vos commandes soient accessibles. Les leviers de vitesses semi-automatiques vous permettent de changer les vitesses facilement et avec précision en cas de virages en épingle et d\'accélérations nerveuses.'
            ],
            [
                'id' => 3,
                'sousTitre1' => 'Qualité d\'image exceptionnelle en Full HD',
                'paragraph1' => 'Le vidéoprojecteur Epson EB-FH52 offre une qualité d\'image exceptionnelle grâce à sa résolution Full HD de 1920 x 1080 pixels et son rapport de contraste élevé de 16 000:1. Cette combinaison permet de reproduire des images nettes, détaillées et riches en couleurs, idéales pour les présentations professionnelles, les projections cinématographiques à domicile ou les événements grand public. La technologie 3LCD garantit des couleurs vives et éclatantes, ainsi qu\'une luminosité de 4 000 lumens en mode standard, assurant une visibilité optimale même dans des environnements lumineux.',
                'sousTitre2' => 'Flexibilité de projection et polyvalence',
                'paragraph2' => 'Avec un rapport de projection allant de 1,32 à 2,14:1, le vidéoprojecteur Epson EB-FH52 offre une grande flexibilité pour ajuster la taille de l\'image en fonction de l\'espace de projection disponible. Il peut projeter des images allant de 30 pouces à 300 pouces de diagonale, adaptées à une variété d\'applications, des petites salles de réunion aux grands auditoriums. Cette polyvalence est renforcée par une gamme complète de connexions, y compris des ports USB, VGA, HDMI et des options de connectivité sans fil via le réseau local WiFi 4 IEEE 802.11b/g/n et la technologie Miracast.',
                'sousTitre3' => 'Longévité et fiabilité',
                'paragraph3' => 'Le vidéoprojecteur Epson EB-FH52 est conçu pour offrir une durabilité exceptionnelle avec une lampe UHE de 230 W offrant jusqu\'à 5 500 heures de fonctionnement en mode standard et jusqu\'à 12 000 heures en mode économique. Cette longévité réduit les coûts de maintenance et assure une utilisation prolongée sans interruption pour les besoins professionnels et de divertissement. De plus, avec un poids de seulement 3,1 kg, il est facile à transporter et à installer, ce qui en fait un choix pratique pour les déplacements professionnels ou les installations temporaires.',
                'sousTitre4' => 'Son de qualité intégré',
                'paragraph4' => 'Le vidéoprojecteur Epson EB-FH52 est équipé d\'un haut-parleur intégré de 16 W, offrant un son de qualité pour accompagner les présentations visuelles. Cette fonctionnalité élimine le besoin d\'enceintes externes dans de nombreuses situations, ce qui simplifie l\'installation et réduit le nombre de câbles nécessaires. Que ce soit pour diffuser des vidéos, des présentations ou des films, le son clair et puissant assure une expérience immersive pour le public.',
                'sousTitre5' => 'Conception élégante et conviviale',
                'paragraph5' => 'En plus de ses performances impressionnantes, le vidéoprojecteur Epson EB-FH52 arbore une conception élégante et fonctionnelle. Son interface utilisateur intuitive et ses commandes conviviales facilitent la configuration et l\'utilisation, même pour les utilisateurs novices. De plus, sa taille compacte et son poids léger le rendent facile à intégrer dans n\'importe quel environnement, que ce soit dans une salle de classe, un bureau ou un salon à domicile. En combinant des performances de pointe, une polyvalence étendue et une facilité d\'utilisation, l\'Epson EB-FH52 est un choix idéal pour les besoins de projection professionnels et de divertissement.'
            ],
            [
                'id' => 4,
                'sousTitre1' => 'Amélioration de la connectivité sans fil',
                'paragraph1' => 'Le module WiFi Epson ELPAP11 offre une solution de connectivité sans fil avancée pour une large gamme de projecteurs Epson, éliminant ainsi le besoin de câbles encombrants et simplifiant la configuration. En offrant une connexion WiFi stable et rapide, ce module permet aux utilisateurs de diffuser du contenu depuis divers appareils compatibles, tels que des ordinateurs portables, des smartphones ou des tablettes, sans nécessiter de connexion filaire. La compatibilité avec les projecteurs Epson populaires garantit une intégration transparente dans divers environnements, des salles de réunion aux salles de classe, en passant par les installations de divertissement à domicile.',
                'sousTitre2' => 'Fonctionnement Dual Band 5 GHz',
                'paragraph2' => 'Le module WiFi Epson ELPAP11 est doté d\'une fonctionnalité Dual Band 5 GHz, offrant une connectivité réseau rapide et stable. En exploitant la bande de fréquences moins encombrée de 5 GHz, ce module garantit des performances optimales et une transmission fluide de contenu, même dans les environnements où les réseaux sans fil sont saturés. Cela se traduit par une expérience de projection plus fiable et une diminution des interférences, ce qui est essentiel pour les présentations professionnelles et les projections de haute qualité.',
                'sousTitre3' => 'Installation facile et polyvalente',
                'paragraph3' => 'Grâce à sa conception simple et à son interface utilisateur conviviale, le module WiFi Epson ELPAP11 est facile à installer et à configurer. Il se connecte facilement au port approprié du projecteur Epson compatible, sans nécessiter d\'outils spéciaux ni de compétences techniques avancées. De plus, sa compatibilité avec une vaste gamme de projecteurs Epson offre une polyvalence d\'utilisation, permettant aux utilisateurs de bénéficier des avantages de la connectivité sans fil sur différents modèles de projecteurs, quel que soit leur environnement d\'application.',
                'sousTitre4' => 'Fiabilité et performances optimales',
                'paragraph4' => 'Conçu et fabriqué par Epson, un leader mondial dans le domaine de la projection, le module WiFi Epson ELPAP11 garantit une fiabilité exceptionnelle et des performances optimales. Il est conçu pour répondre aux normes rigoureuses de qualité et de durabilité d\'Epson, assurant une connectivité sans fil stable et une compatibilité étroite avec les projecteurs Epson. Cette fiabilité renforce la confiance des utilisateurs dans leur équipement de projection, réduisant ainsi les interruptions potentielles et garantissant une expérience utilisateur fluide et sans tracas.',
                'sousTitre5' => 'Élargissement des possibilités de projection',
                'paragraph5' => 'En permettant une connectivité sans fil facile et fiable, le module WiFi Epson ELPAP11 élargit les possibilités de projection, offrant aux utilisateurs une plus grande liberté dans la diffusion de contenu. Que ce soit pour des présentations professionnelles, des projections éducatives en classe ou des divertissements à domicile, ce module permet aux utilisateurs de partager du contenu depuis une gamme d\'appareils compatibles, facilitant ainsi la collaboration, l\'apprentissage interactif et le divertissement multimédia. En fin de compte, le module WiFi Epson ELPAP11 enrichit l\'expérience de projection en offrant une connectivité sans fil pratique et fiable pour une variété d\'applications.'
            ],
            [
                'id' => 5,
                'sousTitre1' => 'Polyvalence multifonctionnelle',
                'paragraph1' => 'L\'imprimante multifonction laser couleur Canon i-SENSYS MF657Cdw (5158C001AA) est une solution complète répondant aux besoins d\'impression, de numérisation, de copie et de télécopie. Cette polyvalence permet aux utilisateurs de gérer efficacement une variété de tâches documentaires à partir d\'un seul appareil, ce qui en fait un choix idéal pour les environnements professionnels et les bureaux à domicile. Que ce soit pour créer des documents professionnels, numériser des images ou envoyer des télécopies, cette imprimante offre une gamme complète de fonctionnalités pour répondre à divers besoins.',
                'sousTitre2' => 'Performances d\'impression rapides et fiables',
                'paragraph2' => 'Avec une vitesse d\'impression couleur allant jusqu\'à 21 pages par minute pour le format A4 et jusqu\'à 38 pages par minute pour le format A5 en mode paysage, l\'i-SENSYS MF657Cdw garantit des performances rapides et efficaces. Cette rapidité d\'impression permet aux utilisateurs de produire rapidement des documents de haute qualité, améliorant ainsi la productivité globale. De plus, la fonction d\'impression recto verso automatique contribue à économiser du temps et des ressources en réduisant le gaspillage de papier.',
                'sousTitre3' => 'Qualité d\'impression professionnelle',
                'paragraph3' => 'Avec une résolution d\'impression allant jusqu\'à 1200 × 1200 ppp, cette imprimante offre une qualité d\'impression exceptionnelle pour les documents couleur et monochrome. Les textes sont nets et précis, tandis que les graphiques et les images sont reproduits avec des couleurs vibrantes et fidèles à la réalité. Cette qualité d\'impression professionnelle est essentielle pour les documents commerciaux, les présentations et d\'autres supports de communication nécessitant une apparence impeccable.',
                'sousTitre4' => 'Adaptabilité à différents volumes de travail',
                'paragraph4' => 'Avec un volume de pages mensuel recommandé allant de 250 à 2500 pages par mois, l\'i-SENSYS MF657Cdw est parfaitement adaptée à une utilisation dans les petits bureaux, les groupes de travail ou les bureaux à domicile. Cette adaptabilité permet à l\'imprimante de répondre aux besoins évolutifs des utilisateurs, qu\'il s\'agisse de volumes d\'impression plus légers ou plus intensifs. De plus, sa conception robuste et fiable assure des performances constantes même dans des environnements de travail exigeants.',
                'sousTitre5' => 'Connectivité étendue pour une flexibilité maximale',
                'paragraph5' => 'Dotée de ports USB 2.0 Haute Vitesse, 10BASE-T/100BASE-TX/1000Base-T, ainsi que d\'une connectivité sans fil 802.11b/g/n et d\'une option de connexion directe sans fil, cette imprimante offre une connectivité étendue pour une flexibilité maximale. Les utilisateurs peuvent imprimer facilement à partir d\'une variété de périphériques, y compris des ordinateurs, des smartphones et des tablettes, ce qui facilite la collaboration et le partage de documents. Cette connectivité polyvalente est essentielle pour les environnements de travail modernes où la mobilité et la collaboration sont essentielles.'
            ],
            [
                'id' => 6,
                'sousTitre1' => 'Le D2 Dédié aux profesionnels',
                'paragraph1' => 'Avec le d2 professional, LaCie perfectionne et destine encore un peu le stockage de bureau aux professionnels. Travaillez plus rapidement - sur n\'importe quel ordinateur - grace au port USB 3.1 (10 Gbit/s) et à un disque dur tournant à 7200 tours par minute. Il comprend également un boîtier monobloc innovant et entièrement en aluminium, grâce auquel vous remarquerez une réduction incrovable du bruit et des viorations. Decouvrez les nouveaux standards en termes de stockage de bureau. Le boitier monobloc entièrement en aluminium du designer Neil Poulton, évacue la chaleur du disque dur. La base intégrée augmente la surface du boitier, offrant ainsi plus d\'espace pour une meilleure dissipation de la chaleur. En conséquence. les composants ont une lonque durée de vie et le fonctionnement est ultrasilencieux. Evitez toute déconnexion accidentelle des câbles de l\'intertace ou de l\'alimentation sans pour autant compromettre l\'apparence de l\'appareil. Les vibrations sont radicalement reduites. absorbees par les supports de disque et le pied amortissant',
                'sousTitre2' => 'Conception éprouvée',
                'paragraph2' => 'Le boîtier est conçu à partir d\'une seule pièce d\'aluminium garantissant une rigidité exceptionnelle pour une fiabilité lonque duree et une qualite obumale. Le disque s arrete automatiquement lorsque le svsteme d\'exoloitation note est en mode veille. Ou alors, utilisez le LaCie Desktop Manager pour configurer l\'arret du disque après une durée déterminée',
                'sousTitre3' => 'Compatibilité Universelle',
                'paragraph3' => 'Disposant de la nouvelle generation d\'intertaces USb 3.1, le Lacie d2 protessional garantit des vitesses optimales sur les derniers modeles d\'ordinateurs tu ou Mac. Etant donne que Usb 3.1 est 3.0 & 2.0. vous pouvez accéder a vos fichiers depuis n\'importe quel ordinateur',
                'sousTitre4' => 'Vitesse sans compromis pour des workflows plus fluides',
                'paragraph4' => 'Les composants professionnels fournissent des vitesses professionnelles. Le nouveau LaCie d2 associe une interface hautement performante à un disque dur Seagate professionnel de 10 To 7 200 tr/min, ce qui se traduit par des vitesses allant iusqu\'à 240 Mo/s. A des telles vitesses, le LaCie d2 professional permet de sauvegarder et de parcouri une grande bibliotheque RAW d\'Adobe Lightroom sans temps mort',
                'sousTitre5' => 'Une valeur sûre pour les profesionnels',
                'paragraph5' => 'Le LaCie d2 Profesionnal offre tout ce dont les professionnels ont besoin pour une sauvegarde sécurisée : une suite logicielle de sauvegarde et la compatibilité avec Time Machine et Windows Backup. Est également inclus le logiciel LaCie Private-Public gui vous permet de protéger les volumes par mot de passe via un crvotage AES 256-bit. Enfin, pour une plus grande tranquillité d\'esprit et une meilleure valeur ajoutée, le LaCie d2 Professional est protégé par une garantie limee lonque duree de cino ans avec une assistance technique Interne specialisee er un service de reparation et/ou de remplacement dans le monde entier.'
            ],
            [
                'id' => 7,
                'sousTitre1' => 'Performance et Connectivité',
                'paragraph1' => 'Le disque dur externe portable ADATA HV620S 2,5" offre des performances remarquables grâce à sa connectivité USB 3.1, qui garantit des transferts de données rapides et efficaces. De plus, sa rétrocompatibilité avec USB 2.0 permet une utilisation polyvalente sur une variété d\'appareils. Que ce soit pour le stockage de fichiers volumineux ou pour des sauvegardes régulières, ce disque dur assure une performance fiable et constante.',
                'sousTitre2' => 'Capacité de Stockage',
                'paragraph2' => 'Disponible en différentes capacités allant de 1 à 4 To, l\'ADATA HV620S offre un espace de stockage généreux pour répondre à tous vos besoins. Que vous soyez un professionnel nécessitant un stockage de données important ou un utilisateur domestique cherchant à sauvegarder des fichiers multimédias, ce disque dur portable répondra à vos exigences en matière de stockage.',
                'sousTitre3' => 'Design Compact et Léger',
                'paragraph3' => 'Avec des dimensions de 115 x 78 x 11.5mm pour les versions 1TB/2TB et 115 x 78 x 21mm pour la version 4TB, ainsi qu\'un poids de seulement 152g pour les versions 1TB/2TB et 230g pour la version 4TB, le ADATA HV620S est extrêmement portable. Son design fin et léger en fait le compagnon idéal pour les déplacements, que ce soit pour le travail, les voyages ou simplement à la maison.',
                'sousTitre4' => 'Compatibilité Étendue',
                'paragraph4' => 'Ce disque dur externe est compatible avec une large gamme de systèmes d\'exploitation, y compris Windows 7/8/8.1/10, Mac OS X 10.6 ou ultérieur, et Linux kernel 2.6 ou ultérieur. Cette compatibilité étendue garantit une intégration fluide avec divers appareils, qu\'il s\'agisse d\'ordinateurs portables, de PC de bureau ou même de consoles de jeu.',
                'sousTitre5' => 'Robustesse et Fiabilité',
                'paragraph5' => 'Avec une plage de température de fonctionnement allant de 5°C (41°F) à 50°C (121°F), ce disque dur portable est conçu pour résister à des conditions environnementales variées. Sa construction robuste assure une durabilité à long terme, tandis que sa fiabilité vous offre la tranquillité d\'esprit quant à la sécurité de vos données, que ce soit à la maison, au bureau ou en déplacement.'
            ],
            [
                'id' => 8,
                'sousTitre1' => 'Connectivité Performante',
                'paragraph1' => 'Le prolongateur réseau TP-Link RE505X est un appareil polyvalent qui agit à la fois comme émetteur et récepteur réseau, offrant des vitesses allant jusqu\'à 1200 Mbit/s. Cette connectivité rapide et stable garantit des transferts de données fluides et des performances réseau optimales pour une variété d\'applications, qu\'il s\'agisse de streaming vidéo en haute définition, de jeux en ligne ou de téléchargements de fichiers volumineux.',
                'sousTitre2' => 'Adaptabilité aux Réseaux Filaires et Sans Fil',
                'paragraph2' => 'Avec une prise en charge des connexions filaires 10/100/1000Base-T(X) et des connexions sans fil bi-bande (2,4 GHz / 5 GHz) 802.11a, 802.11b, 802.11g, Wi-Fi 4 (802.11n), Wi-Fi 5 (802.11ac), et Wi-Fi 6 (802.11ax), le RE505X s\'adapte à une large gamme de configurations réseau. Que vous ayez besoin d\'étendre un réseau câblé existant ou d\'améliorer la couverture Wi-Fi dans votre maison ou votre bureau, ce prolongateur réseau offre une solution polyvalente.',
                'sousTitre3' => 'Performance sans Compromis',
                'paragraph3' => 'Doté de technologies avancées, ce prolongateur réseau garantit une performance sans compromis, même dans les environnements les plus exigeants. Sa capacité à fonctionner sur les bandes de fréquences 2,4 GHz et 5 GHz permet d\'éviter les interférences et d\'assurer une connexion stable et rapide, quel que soit le nombre d\'appareils connectés au réseau.',
                'sousTitre4' => 'Design Élégant et Discret',
                'paragraph4' => 'Avec son design blanc élégant, le TP-Link RE505X s\'intègre harmonieusement dans n\'importe quel environnement domestique ou professionnel. Son format compact et discret lui permet de se fondre discrètement dans votre décor, tandis que ses performances puissantes en font un élément essentiel de votre infrastructure réseau.',
                'sousTitre5' => 'Facilité d\'Installation et d\'Utilisation',
                'paragraph5' => 'L\'installation et la configuration du prolongateur réseau sont simples et rapides, grâce à une interface conviviale et des instructions claires. Que vous soyez un utilisateur novice ou expérimenté, vous pouvez mettre en place et profiter des avantages de ce dispositif en quelques minutes seulement, sans avoir besoin de compétences techniques avancées.'
            ],
            [
                'id' => 9,
                'sousTitre1' => 'Votre espace vous appartient',
                'paragraph1' => 'Transformez n\'importe quel espace en endroit minimaliste, moderne et silencieux avec l\'ensemble sans fil ultra-fin MK470 qui comprend un clavier et une souris au design compact et avant-gardiste, parfait pour travailler efficacement.',
                'sousTitre2' => 'Minimaliste, Moderne, Ultra fin',
                'paragraph2' => 'L’ensemble ultra-fin MK470 se démarque par sa simplicité. Le profil mince et le design minimaliste font de votre clavier et de votre souris de véritables ornements pour un bureau propre et élégant.',
                'sousTitre3' => 'Productivité et gain d\'espace',
                'paragraph3' => 'Le clavier compact comprend un pavé numérique et 12 touches de raccourcis, avec tout ce dont vous avez besoin. La souris fine est extra portable et vous pouvez facilement la ranger dans le sac de votre ordinateur portable ou dans votre poche pour rester productif partout. L\'encombrement réduit de l’ensemble vous permet de travailler sur les bureaux les plus exigus et de garder votre souris à portée de main.',
                'sousTitre4' => 'Frappe et navigation fluide et confortable',
                'paragraph4' => 'Les touches ciseaux ultra-plates offrent une expérience de frappe fluide et familière, semblable à celle d\'un ordinateur portable. La forme de galet lisse de la souris ambidextre offre un toucher agréable dans chaque main.',
                'sousTitre5' => 'Travail Silencieux',
                'paragraph5' => 'Un clavier silencieux et une souris testée en laboratoire 90% moins bruyante garantissent une expérience de travail ultra-silencieuse pour vous et votre entourage.'
            ],
            [
                'id' => 10,
                'sousTitre1' => 'Taille et Format d\'Écran',
                'paragraph1' => 'L\'écran Samsung Essential Monitor S3 S31C offre une expérience visuelle immersive avec sa taille de 24 pouces et son format d\'image 16:9. Cette taille d\'écran généreuse est idéale pour une variété d\'utilisations, qu\'il s\'agisse de travailler sur des documents, de regarder des films ou de jouer à des jeux vidéo, offrant une grande surface d\'affichage pour une immersion totale.',
                'sousTitre2' => 'Conception Plat et Courbure de l\'Écran',
                'paragraph2' => 'Conçu avec une courbure d\'écran plat, le S31C de Samsung offre une esthétique épurée et moderne qui s\'intègre parfaitement à n\'importe quel espace de travail ou de divertissement. La courbure de l\'écran est optimisée pour réduire la fatigue visuelle et offrir un confort visuel accru, ce qui en fait un choix idéal pour de longues sessions devant l\'écran.',
                'sousTitre3' => 'Qualité d\'Image et Réactivité',
                'paragraph3' => 'Grâce à sa dalle IPS (In-Plane Switching), cet écran offre une qualité d\'image exceptionnelle avec des couleurs vives et des angles de vision larges. La résolution Full HD de 1920 x 1080 pixels garantit des détails nets et précis, tandis que le temps de réponse rapide de 5 ms (gris à gris) et le taux de rafraîchissement de 75 Hz assurent une réactivité fluide, réduisant ainsi les effets de flou et les déchirements d\'image.',
                'sousTitre4' => 'Connectivité Polyvalente',
                'paragraph4' => 'Pour une connectivité pratique, l\'écran Samsung Essential Monitor S3 S31C est équipé de ports d\'entrée VGA et HDMI, offrant ainsi une compatibilité étendue avec une variété de périphériques tels que les ordinateurs portables, les PC de bureau, les consoles de jeu et les lecteurs multimédias. Cette polyvalence vous permet de connecter facilement vos appareils préférés pour profiter d\'une expérience multimédia immersive.',
                'sousTitre5' => 'Réglages Ergonomiques',
                'paragraph5' => 'Pour un confort optimal, cet écran offre des réglages ergonomiques de la position, notamment une inclinaison de -2.0°(-1.0°/+2.0°) à 20.0°(±2.0°), vous permettant d\'ajuster l\'angle de vision pour répondre à vos besoins spécifiques. Que vous préfériez travailler debout ou assis, ou que vous recherchiez simplement la meilleure position pour votre confort visuel, ces réglages vous permettent de personnaliser votre expérience d\'utilisation.'
            ],
            [
                'id' => 11,
                'sousTitre1' => 'Performance et Puissance de Traitement',
                'paragraph1' => 'L\'ordinateur de bureau Lenovo ThinkCentre neo 50t (11SE00QFFM) est équipé d\'un processeur Intel® Core™ i3-12100, avec 4 cœurs et 8 threads, offrant une puissance de traitement remarquable pour une variété de tâches. Avec une fréquence de base de 3,3 GHz et une capacité de Turbo Boost atteignant 4,3 GHz, ce processeur assure une réactivité rapide et une exécution fluide des applications, même dans les environnements multitâches les plus exigeants.',
                'sousTitre2' => 'Stockage Rapide et Fiable',
                'paragraph2' => 'Pour le stockage des données, cet ordinateur est équipé d\'un SSD M.2 2280 PCIe® 4.0x4 NVMe® Opal 2.0 de 512 Go. Ce SSD offre des vitesses de lecture et d\'écriture ultra-rapides, permettant un démarrage rapide du système, des chargements d\'application instantanés et des transferts de fichiers fluides. Vous pouvez ainsi accéder à vos données rapidement et efficacement, améliorant ainsi votre productivité au quotidien.',
                'sousTitre3' => 'Graphismes Intégrés et Polyvalence',
                'paragraph3' => 'La carte graphique intégrée Intel® UHD Graphics 730 offre des performances graphiques suffisantes pour une utilisation quotidienne, ainsi que pour certaines tâches professionnelles et de divertissement. Que vous travailliez sur des documents, naviguiez sur le Web, regardiez des vidéos en streaming ou jouiez à des jeux occasionnels, cette carte graphique garantit une expérience visuelle fluide et agréable.',
                'sousTitre4' => 'Flexibilité du Système d\'Exploitation',
                'paragraph4' => 'Livré avec le système d\'exploitation FreeDOS, cet ordinateur offre une flexibilité totale en termes de choix du système d\'exploitation. Vous pouvez installer votre système d\'exploitation préféré, que ce soit Windows, Linux ou tout autre système compatible, selon vos besoins et préférences. Cette liberté vous permet de personnaliser votre expérience informatique selon vos besoins spécifiques.',
                'sousTitre5' => 'Design Compact et Polyvalent',
                'paragraph5' => 'Avec son design compact et sans écran, le Lenovo ThinkCentre neo 50t s\'intègre facilement dans n\'importe quel environnement de bureau ou domestique. Son format compact lui permet de s\'adapter même aux espaces les plus restreints, tout en offrant une puissance de traitement et des capacités de stockage robustes. Polyvalent et fiable, cet ordinateur de bureau est un choix idéal pour les utilisateurs à la recherche de performances et de flexibilité.'
            ],
            [
                'id' => 12,
                'sousTitre1' => 'Puissance et Performance',
                'paragraph1' => 'L\'ordinateur portable Asus ROG Zephyrus G14 brille par sa puissance de traitement et ses performances exceptionnelles, grâce à son processeur AMD Ryzen™ 5-4600HS cadencé à 3.0 GHz, avec une capacité de Turbo Boost jusqu\'à 4.0 GHz. Cette configuration assure une exécution fluide des tâches multitâches, des jeux exigeants et des applications professionnelles gourmandes en ressources, offrant ainsi une expérience utilisateur sans compromis.',
                'sousTitre2' => 'Mémoire et Stockage',
                'paragraph2' => 'Avec une mémoire vive de 16 Go, combinant 8 Go DDR4 intégrés et 8 Go DDR4-3200 SO-DIMM, cet ordinateur portable offre une excellente réactivité et une gestion efficace des données. De plus, son disque dur SSD M.2 NVMe™ PCIe® 3.0 de 512 Go garantit des temps de chargement rapides et une expérience utilisateur fluide, permettant ainsi de stocker et d\'accéder rapidement à vos fichiers, programmes et jeux préférés.',
                'sousTitre3' => 'Écran Immersif',
                'paragraph3' => 'L\'écran de 14 pouces FHD (1920 x 1080) de l\'Asus ROG Zephyrus G14 offre une expérience visuelle immersive avec des couleurs vives, des détails précis et des angles de vision larges. Doté de la technologie IPS, d\'une luminosité de 300 nits et d\'un taux de contraste de 700:1, cet écran est parfait pour le jeu, le streaming de contenu multimédia et le travail professionnel nécessitant une précision visuelle.',
                'sousTitre4' => 'Graphismes et Jeux',
                'paragraph4' => 'La carte graphique NVIDIA® GeForce® GTX 1650 Ti 4 Go GDDR6 assure des performances graphiques exceptionnelles pour les jeux les plus récents et les applications créatives. Avec cette carte graphique dédiée, les utilisateurs peuvent profiter d\'une expérience de jeu fluide, de graphismes détaillés et de temps de réponse rapides, ce qui en fait un choix idéal pour les joueurs passionnés et les créateurs de contenu.',
                'sousTitre5' => 'Mobilité et Polyvalence',
                'paragraph5' => 'Avec son poids léger de seulement 1,60 kg, cet ordinateur portable est facilement transportable, ce qui en fait le compagnon idéal pour les déplacements quotidiens, que ce soit pour le travail, l\'école ou les loisirs. Doté de Windows 10 Home et d\'un clavier AZERTY français, il est prêt à l\'emploi dès sa sortie de la boîte, offrant ainsi une expérience informatique polyvalente et conviviale pour tous les utilisateurs.'
            ],
            [
                'id' => 13,
                'sousTitre1' => 'Solution d\'impression polyvalente',
                'paragraph1' => 'L\'imprimante multifonction HP Smart Tank 530 (4SB24A) est bien plus qu\'une simple imprimante. Avec ses fonctionnalités d\'impression, de numérisation et de copie, ainsi qu\'un chargeur automatique de documents, elle répond à tous vos besoins en matière de documentation, que ce soit pour les travaux professionnels, les tâches scolaires ou les projets domestiques. Cette polyvalence en fait un outil indispensable pour toute la famille ou pour une utilisation professionnelle.',
                'sousTitre2' => 'Économique et écologique',
                'paragraph2' => 'Grâce à ses réservoirs rechargeables, l\'imprimante HP Smart Tank 530 offre une solution économique et écologique pour l\'impression. Fini les cartouches coûteuses à remplacer régulièrement. Avec les bouteilles d\'encre incluses, vous pouvez imprimer des milliers de pages avant d\'avoir besoin de recharger les réservoirs. Cela réduit non seulement les coûts d\'impression à long terme, mais contribue également à réduire les déchets plastiques liés aux cartouches d\'encre.',
                'sousTitre3' => 'Qualité d\'impression exceptionnelle',
                'paragraph3' => 'Ne sacrifiez pas la qualité pour l\'économie. L\'imprimante HP Smart Tank 530 offre des résultats exceptionnels avec une résolution maximale de 1200 x 1200 ppp en noir et jusqu\'à 4800 x 1200 ppp en couleur. Que vous imprimiez des documents texte, des graphiques ou des photos, vous bénéficiez d\'une qualité d\'impression nette, détaillée et vibrante.',
                'sousTitre4' => 'Rapidité et efficacité',
                'paragraph4' => 'Avec une vitesse d\'impression de 22 pages par minute en noir et 16 pages par minute en couleur, cette imprimante est rapide et efficace, vous permettant de terminer vos travaux d\'impression en un rien de temps. De plus, le chargeur automatique de documents simplifie la numérisation et la copie de plusieurs pages, vous faisant gagner du temps et de l\'énergie.',
                'sousTitre5' => 'Connectivité moderne et conviviale',
                'paragraph5' => 'Grâce à sa connectivité Wi-Fi, Bluetooth LE et USB 2.0 haut débit, l\'imprimante HP Smart Tank 530 offre une flexibilité totale en termes de connexion à vos appareils. Que vous travailliez depuis un ordinateur, un smartphone ou une tablette, vous pouvez facilement imprimer, numériser et copier des documents sans tracas. De plus, les pilotes intuitifs et conviviaux rendent l\'utilisation de cette imprimante simple et accessible à tous.'
            ],
            [
                'id' => 14,
                'sousTitre1' => 'Qualité d\'impression exceptionnelle',
                'paragraph1' => 'La cartouche d\'encre Canon PG-445 Noir est conçue pour offrir une qualité d\'impression exceptionnelle à chaque utilisation. Avec les encres Canon d\'origine, vous pouvez vous attendre à des couleurs fidèles et éclatantes, ainsi qu\'à des photos durables qui résistent à l\'épreuve du temps. Que vous imprimiez des documents professionnels ou des photos personnelles, cette cartouche vous garantit des résultats nets et précis.',
                'sousTitre2' => 'Technologie FINE de Canon',
                'paragraph2' => 'Grâce à la technologie FINE (Full-photolithography Inkjet Nozzle Engineering) exclusive de Canon, cette cartouche d\'encre assure la protection et la longévité de votre imprimante. La technologie FINE garantit un débit d\'encre uniforme et une distribution précise des gouttelettes d\'encre, ce qui se traduit par des impressions de haute qualité à chaque utilisation. Vous pouvez ainsi imprimer en toute confiance, sachant que votre imprimante est entre de bonnes mains.',
                'sousTitre3' => 'Précision optimale',
                'paragraph3' => 'Avec une capacité de 8 ml, la cartouche d\'encre Canon PG-445 Noir offre une précision optimale pour les petits caractères et les lignes fines. Que vous imprimiez du texte, des graphiques ou des images, cette cartouche vous permet d\'obtenir des résultats nets et détaillés, sans compromis sur la qualité. Vous pouvez compter sur cette cartouche pour produire des impressions de haute qualité, jour après jour.',
                'sousTitre4' => 'Durabilité et fiabilité',
                'paragraph4' => 'En choisissant les encres Canon d\'origine, vous optez pour la durabilité et la fiabilité. Ces encres sont spécialement formulées pour fonctionner de manière optimale avec les imprimantes Canon, garantissant ainsi des performances constantes et fiables. Vous pouvez donc imprimer en toute tranquillité d\'esprit, sachant que vos documents et vos photos seront toujours de la plus haute qualité.',
                'sousTitre5' => 'Performances constantes',
                'paragraph5' => 'Avec la cartouche d\'encre Canon PG-445 Noir, vous pouvez vous attendre à des performances constantes à chaque utilisation. Que vous imprimiez occasionnellement ou régulièrement, cette cartouche vous offre des résultats de haute qualité à chaque fois. Elle vous permet de réaliser des impressions nettes et précises, tout en prolongeant la durée de vie de votre imprimante.'
            ],
            [
                'id' => 15,
                'sousTitre1' => 'Des performances révolutionnaires',
                'paragraph1' => 'Le Disque Dur SSD Kingston FURY Renegade Heatsink M.2 2280 PCIe Gen4 x4 NVMe 1 To repousse les limites de la performance avec la technologie PCIe Gen 4, offrant des transferts de données ultra-rapides allant jusqu\'à 8 Go/s. Cette vitesse exceptionnelle permet de réduire considérablement les temps de chargement des jeux et des applications, offrant ainsi une expérience informatique fluide et réactive.',
                'sousTitre2' => 'Vitesses de lecture/écriture incroyables',
                'paragraph2' => 'Ce SSD révolutionnaire offre des vitesses de lecture/écriture impressionnantes allant jusqu\'à 7 300/7 000 Mo/s, ainsi qu\'une incroyable performance en termes de IOPS, atteignant jusqu\'à 1 000 000. Ces performances exceptionnelles garantissent des temps de réponse ultra-rapides, vous permettant de profiter pleinement de vos jeux et de vos applications sans aucun temps mort.',
                'sousTitre3' => 'Gestion thermique avancée',
                'paragraph3' => 'Pour maintenir des performances optimales et assurer une stabilité maximale, le Disque Dur SSD Kingston FURY Renegade est équipé d\'une gestion thermique avancée. Son dissipateur thermique efficace aide à dissiper la chaleur générée par les opérations intensives, garantissant ainsi des performances fiables même lors de sessions de jeu prolongées.',
                'sousTitre4' => 'Idéal pour les passionnés de jeux',
                'paragraph4' => 'Avec ses performances exceptionnelles et sa gestion thermique avancée, ce SSD est idéal pour les passionnés de jeux et de matériel informatique exigeants. Il offre une expérience de jeu fluide et sans interruption, permettant aux joueurs de profiter pleinement de leurs jeux préférés sans être freinés par des temps de chargement lents ou des ralentissements du système.',
                'sousTitre5' => 'Fiabilité et durabilité',
                'paragraph5' => 'En tant que produit de la gamme Kingston FURY, ce SSD bénéficie de la réputation de fiabilité et de durabilité de la marque. Construit avec des composants de haute qualité et soumis à des tests rigoureux, ce SSD est conçu pour offrir des performances constantes et fiables sur le long terme, assurant ainsi une expérience informatique optimale pour les années à venir.'
            ],
            [
                'id' => 16,
                'sousTitre1' => 'Conception ergonomique et légère',
                'paragraph1' => 'La souris gaming filaire Logitech G502 X offre une expérience de jeu ergonomique et confortable grâce à son design repensé et à son poids léger de seulement 89 grammes. Conçue pour s\'adapter parfaitement à votre main, elle offre une prise en main confortable même lors de sessions de jeu prolongées, ce qui en fait un compagnon idéal pour les joueurs les plus exigeants.',
                'sousTitre2' => 'Performances de pointe',
                'paragraph2' => 'Dotée des tout nouveaux commutateurs optiques-mécaniques LIGHTFORCE et du capteur HERO 25K submicronique, la souris G502 X offre des performances de pointe et une précision ultime à chaque mouvement. Que vous soyez en train de viser précisément un adversaire ou de vous déplacer rapidement sur le champ de bataille, cette souris vous offre un avantage compétitif grâce à sa réactivité et sa précision exceptionnelles.',
                'sousTitre3' => 'Personnalisation avancée',
                'paragraph3' => 'Avec jusqu\'à 5 profils de mémoire embarqués, vous pouvez personnaliser votre expérience de jeu selon vos préférences et vos besoins spécifiques. De plus, avec 13 commandes programmables, vous pouvez attribuer des actions spécifiques à chaque bouton de la souris, ce qui vous permet de réagir rapidement et efficacement dans toutes les situations de jeu.',
                'sousTitre4' => 'Glisse fluide',
                'paragraph4' => 'Les patins en PTFE à faible friction assurent une glisse fluide et précise sur n\'importe quelle surface, ce qui vous permet de manoeuvrer votre souris avec une précision optimale. Que vous utilisiez un tapis de souris ou une surface de bureau, vous bénéficiez d\'une sensation de contrôle total sur votre souris, améliorant ainsi votre expérience de jeu.',
                'sousTitre5' => 'Compatibilité universelle',
                'paragraph5' => 'La souris gaming Logitech G502 X est compatible avec Windows® 10 ou ultérieur et Mac 10.14 ou ultérieur, ce qui vous permet de l\'utiliser avec une large gamme d\'appareils. Il suffit de la connecter via son port USB et elle est prête à vous accompagner dans toutes vos aventures gaming, que ce soit sur PC ou sur Mac.'
            ],
            [
                'id' => 17,
                'sousTitre1' => 'Performance Gaming de Qualité',
                'paragraph1' => 'Le clavier gaming G213 Prodigy de Logitech est conçu pour offrir des performances de haute qualité aux joueurs les plus exigeants. Doté de touches tactiles à dômes mécaniques, ce clavier offre une réponse rapide et précise à chaque pression de touche, garantissant ainsi une expérience de frappe fluide et réactive. Que vous soyez en train de jouer à des jeux rapides ou de rédiger des messages, ce clavier offre une performance fiable et durable pour répondre à tous vos besoins.',
                'sousTitre2' => 'Eclairage RGB Personnalisable',
                'paragraph2' => 'Plongez dans une expérience de jeu immersive avec l\'éclairage LIGHTSYNC RGB personnalisable de ce clavier. Avec 5 zones distinctes, vous pouvez créer des effets lumineux dynamiques et personnalisés qui correspondent à votre style de jeu ou à l\'ambiance de votre environnement. Que vous préfériez des couleurs vives et éclatantes ou des effets lumineux subtils, ce clavier vous permet de personnaliser votre expérience visuelle selon vos préférences.',
                'sousTitre3' => 'Confort et Ergonomie',
                'paragraph3' => 'Ce clavier est conçu pour offrir un confort optimal pendant les longues sessions de jeu. Doté d\'un repose-poignets intégré et d\'une inclinaison ajustable, il vous permet de jouer pendant des heures sans ressentir de fatigue ni d\'inconfort. De plus, les touches tactiles offrent une sensation de frappe agréable, tandis que la disposition AZERTY en français vous permet de taper rapidement et facilement, même dans l\'action la plus intense.',
                'sousTitre4' => 'Résistance et Durabilité',
                'paragraph4' => 'Le clavier G213 Prodigy est conçu pour résister aux rigueurs de l\'utilisation intensive. Les touches à dômes mécaniques sont résistantes aux éclaboussures, ce qui les rend parfaites pour les environnements de jeu parfois chaotiques. De plus, la construction solide et robuste garantit une durabilité à long terme, vous offrant ainsi une fiabilité exceptionnelle même après des années d\'utilisation.',
                'sousTitre5' => 'Commandes Multimédia Dédiées',
                'paragraph5' => 'Enfin, ce clavier est équipé de commandes multimédia dédiées qui vous permettent de contrôler facilement la lecture audio et vidéo pendant que vous jouez. Ces commandes pratiques vous permettent de régler le volume, de mettre en pause la lecture ou de passer à la piste suivante sans interrompre votre jeu. Cela vous permet de rester concentré sur l\'action tout en restant connecté à votre divertissement.'
            ],
            [
                'id' => 18,
                'sousTitre1' => 'Performances optimisées avec l\'architecture Pascal',
                'paragraph1' => 'La carte graphique PNY GeForce GT 1030 NVIDIA 2 GB GDDR4 est dotée de l\'architecture Pascal, offrant ainsi des performances optimisées pour répondre aux besoins des utilisateurs exigeants. Avec ses 384 cœurs CUDA et ses 2 Go de VRAM DDR4, elle excelle dans les applications gourmandes en ressources, garantissant une expérience fluide et réactive, que ce soit pour les jeux vidéo, la création de contenu multimédia ou d\'autres tâches intensives.',
                'sousTitre2' => 'Sorties HDMI et DVI-D pour une qualité d\'affichage exceptionnelle',
                'paragraph2' => 'Cette carte graphique est équipée de sorties HDMI 2.0b et DVI-D, permettant une résolution maximale de 4096 x 2160. Cela garantit une qualité d\'affichage exceptionnelle, que vous utilisiez un moniteur HD standard ou un écran 4K. Vous pouvez ainsi profiter d\'une netteté d\'image incroyable, avec des détails précis et des couleurs vibrantes, pour une expérience visuelle immersive.',
                'sousTitre3' => 'Refroidissement efficace pour des performances stables',
                'paragraph3' => 'Le refroidissement efficace à ventilateur unique de la carte graphique assure des performances stables, même lors d\'une utilisation prolongée. Grâce à sa conception intelligente, elle évacue efficacement la chaleur générée par les opérations graphiques intensives, permettant ainsi à la carte de fonctionner à des températures optimales et de maintenir des performances constantes dans toutes les situations.',
                'sousTitre4' => 'Technologies avancées pour une accélération et une augmentation dynamique',
                'paragraph4' => 'Exploitez les capacités CUDA de la carte graphique pour accélérer les tâches et améliorer les performances de vos applications. De plus, profitez de la technologie NVIDIA GPU Boost 3.0 pour une augmentation dynamique de la fréquence d\'horloge en temps réel, vous offrant ainsi des performances supplémentaires lorsque vous en avez le plus besoin. Cela vous permet de bénéficier d\'une réactivité accrue et de performances optimales dans toutes vos activités graphiques.',
                'sousTitre5' => 'Polyvalence et efficacité pour une expérience informatique optimale',
                'paragraph5' => 'En résumé, la carte graphique PNY GeForce GT 1030 NVIDIA 2 GB GDDR4 offre polyvalence et efficacité pour une expérience informatique optimale. Que vous soyez un joueur passionné, un créateur de contenu ou un utilisateur professionnel, cette carte graphique vous permet d\'accélérer vos applications et jeux, garantissant ainsi des performances exceptionnelles et une immersion totale dans votre monde numérique.'
            ],
            [
                'id' => 19,
                'sousTitre1' => 'Connectivité haute performance',
                'paragraph1' => 'Le Switch Smart TP-Link TL-SG2218 JetStream est conçu pour offrir une connectivité haut débit et fiable. Avec ses 16 ports Gigabit RJ45 et ses 2 slots SFP Gigabit, il permet de connecter un large éventail de périphériques réseau, tels que des ordinateurs, des serveurs, des imprimantes, des caméras IP et bien plus encore. Que ce soit pour les petites entreprises, les bureaux à domicile ou les réseaux domestiques exigeants, ce switch offre une solution de connectivité complète et performante.',
                'sousTitre2' => 'Administration centralisée via Omada SDN',
                'paragraph2' => 'Grâce à la gestion centralisée du cloud Omada SDN, le switch TP-Link TL-SG2218 offre une administration pratique et une surveillance intelligente du réseau. Cette plateforme cloud permet de gérer facilement tous les appareils du réseau à partir d\'une seule interface, offrant ainsi une visibilité complète sur le réseau et permettant des ajustements rapides et précis en fonction des besoins de l\'utilisateur.',
                'sousTitre3' => 'Fonctionnalités avancées de sécurité',
                'paragraph3' => 'Ce switch est équipé de fonctionnalités avancées de sécurité pour protéger votre réseau contre les menaces en ligne. Il prend en charge les fonctions de sécurité telles que la liste de contrôle d\'accès (ACL), la protection contre les tempêtes de broadcast et les attaques DoS (Déni de Service), garantissant ainsi la sécurité des données et des périphériques connectés.',
                'sousTitre4' => 'Optimisation des applications vocales et vidéo',
                'paragraph4' => 'Le Switch TP-Link TL-SG2218 offre une optimisation des applications vocales et vidéo, garantissant une qualité de service (QoS) supérieure pour les applications sensibles au délai telles que la voix sur IP (VoIP) et la vidéoconférence. Grâce à la prise en charge de la QoS basée sur les ports et les VLAN, ce switch garantit une bande passante suffisante et une priorisation du trafic pour une expérience utilisateur fluide et sans interruption.',
                'sousTitre5' => 'Gestion autonome et polyvalente',
                'paragraph5' => 'En plus de la gestion centralisée via Omada SDN, ce switch offre également des capacités de gestion autonome pour une flexibilité maximale. Il prend en charge les protocoles de gestion standard tels que SNMP (Simple Network Management Protocol) et RMON (Remote Monitoring), ce qui permet une intégration transparente dans les réseaux existants et une gestion aisée à partir de logiciels tiers compatibles. Que vous souhaitiez une gestion centralisée ou autonome, ce switch offre la polyvalence nécessaire pour répondre à tous les besoins de votre réseau.'
            ],
            [
                'id' => 20,
                'sousTitre1' => 'Polyvalence pour toutes vos tâches d\'impression',
                'paragraph1' => 'L\'imprimante A3 Multifonction Jet d\'encre HP OfficeJet Pro 7740 offre une polyvalence exceptionnelle pour répondre à tous vos besoins d\'impression, de copie, de numérisation et de télécopie. Que vous ayez besoin d\'imprimer des documents professionnels, des brochures couleur, des rapports détaillés ou des photos de haute qualité, cette imprimante est prête à relever le défi.',
                'sousTitre2' => 'Vitesse et qualité d\'impression remarquables',
                'paragraph2' => 'Avec une vitesse d\'impression de 34 pages par minute en noir et blanc et en couleur, cette imprimante vous permet de réaliser vos tâches rapidement et efficacement, sans compromis sur la qualité. Vous bénéficiez d\'une résolution d\'impression allant jusqu\'à 1 200 x 1 200 DPI pour le noir et jusqu\'à 4 800 x 1 200 DPI pour la couleur, assurant ainsi des documents nets et professionnels à chaque impression.',
                'sousTitre3' => 'Volume de travail adapté à vos besoins',
                'paragraph3' => 'Le volume de pages mensuel recommandé de 250 à 1 500 pages par mois fait de cette imprimante un choix idéal pour les utilisateurs à domicile, les petites entreprises ou les bureaux nécessitant une impression régulière. Vous pouvez compter sur cette imprimante pour répondre à vos besoins d\'impression, quelle que soit l\'ampleur de votre charge de travail.',
                'sousTitre4' => 'Connectivité étendue pour une facilité d\'utilisation',
                'paragraph4' => 'Avec une connectivité étendue comprenant un port USB 2.0, Ethernet intégré, Wi-Fi et deux ports RJ-11 pour le fax, cette imprimante vous permet de facilement partager l\'imprimante avec plusieurs appareils et d\'imprimer depuis n\'importe où dans votre maison ou votre bureau. Vous pouvez également utiliser l\'application mobile HP Smart pour imprimer, numériser et partager des documents directement depuis votre smartphone ou votre tablette.',
                'sousTitre5' => 'Encres fournies pour une impression immédiate',
                'paragraph5' => 'Les encres fournies avec l\'imprimante vous permettent de commencer à imprimer immédiatement, avec une cartouche noire d\'une autonomie d\'environ 1 000 pages et des cartouches CMJ (cyan, magenta, jaune) d\'une autonomie d\'environ 540 pages chacune. Vous pouvez ainsi profiter de la commodité de l\'impression dès la sortie de la boîte, sans avoir à vous soucier d\'acheter des consommables supplémentaires.'
            ],
            [
                'id' => 21,
                'sousTitre1' => 'Style et praticité au quotidien',
                'paragraph1' => 'Le sac à dos Casual Lenovo ThinkPad B210 15,6" allie style et praticité pour répondre à vos besoins quotidiens de transport. Son design compact et moderne en fait un compagnon idéal pour le travail, l\'école ou les déplacements. Avec sa taille adaptée pour accueillir des ordinateurs portables jusqu\'à 15,6 pouces, ce sac à dos offre un espace de rangement suffisant pour vos appareils électroniques et autres effets personnels.',
                'sousTitre2' => 'Construction durable en polyester',
                'paragraph2' => 'Fabriqué en polyester durable, ce sac à dos est conçu pour résister à une utilisation quotidienne intensive. Son matériau robuste offre une protection fiable contre les éléments extérieurs, garantissant la sécurité de vos appareils électroniques et de vos effets personnels. Vous pouvez ainsi voyager en toute confiance, sachant que vos biens sont bien protégés.',
                'sousTitre3' => 'Protection optimale pour vos appareils',
                'paragraph3' => 'L\'intérieur rembourré de ce sac à dos assure une protection optimale pour votre ordinateur portable et autres appareils électroniques. Le rembourrage absorbe les chocs et les impacts, empêchant ainsi les dommages causés par les chutes ou les collisions. Vous pouvez transporter votre équipement en toute sécurité, même dans les environnements les plus agités.',
                'sousTitre4' => 'Organisation intelligente des compartiments',
                'paragraph4' => 'Ce sac à dos est équipé d\'une poche zippée à accès rapide qui offre un espace de rangement supplémentaire pour vos accessoires essentiels tels que les chargeurs, les câbles, les clés USB et les documents. De plus, les multiples compartiments internes vous permettent de garder vos affaires organisées et facilement accessibles, ce qui facilite la recherche de ce dont vous avez besoin lorsque vous êtes en déplacement.',
                'sousTitre5' => 'Confort de transport toute la journée',
                'paragraph5' => 'Le sac à dos Casual Lenovo ThinkPad B210 15,6" est conçu pour offrir un confort optimal même lors de longues journées de transport. Son panneau arrière matelassé réduit la pression sur vos épaules et votre dos, ce qui vous permet de porter votre sac à dos confortablement pendant de longues périodes. Vous pouvez ainsi rester mobile et productif tout au long de la journée, sans ressentir de fatigue ni d\'inconfort.'
            ],
            [
                'id' => 22,
                'sousTitre1' => 'Performance et Polyvalence',
                'paragraph1' => 'L\'imprimante Epson EcoTank L18050 est conçue pour offrir des performances exceptionnelles et une polyvalence maximale pour répondre à tous vos besoins d\'impression. Que vous souhaitiez imprimer des photos haute qualité, des documents professionnels ou des projets créatifs, cette imprimante est prête à relever le défi. Avec ses fonctionnalités avancées et sa qualité d\'impression remarquable, elle est idéale pour les utilisateurs exigeants.',
                'sousTitre2' => 'Impression Photo Haute Qualité',
                'paragraph2' => 'Cette imprimante est équipée de réservoirs d\'encre individuels haute capacité, ce qui permet une impression continue sans avoir à remplacer les cartouches fréquemment. Avec une résolution d\'impression de 5.760 x 1.440 DPI, elle offre des photos d\'une qualité exceptionnelle, avec des détails nets, des couleurs vives et des nuances subtiles. Que vous imprimiez des photos de famille, des portraits artistiques ou des projets créatifs, cette imprimante garantit des résultats impressionnants à chaque fois.',
                'sousTitre3' => 'Connectivité Facile',
                'paragraph3' => 'Profitez d\'une connectivité sans fil pratique avec la fonction Wi-Fi et Wi-Fi Direct, qui vous permettent d\'imprimer facilement depuis votre smartphone, votre tablette ou votre ordinateur portable, sans avoir besoin de câbles encombrants. De plus, la connectivité USB offre une option supplémentaire pour connecter vos appareils, assurant ainsi une flexibilité maximale pour répondre à tous vos besoins d\'impression.',
                'sousTitre4' => 'Économie d\'Encre et d\'Argent',
                'paragraph4' => 'Grâce à son système de réservoirs d\'encre rechargeables, l\'Epson EcoTank L18050 permet des économies significatives sur les coûts d\'impression. Les grandes bouteilles d\'encre incluses offrent une autonomie élevée, réduisant ainsi la fréquence de remplacement de l\'encre et minimisant les interruptions pendant l\'impression. Cette solution économique et écologique est idéale pour les utilisateurs à la recherche d\'une option rentable et durable pour leurs besoins d\'impression.',
                'sousTitre5' => 'Facilité d\'Utilisation et Fiabilité',
                'paragraph5' => 'L\'Epson EcoTank L18050 est conçue pour une utilisation facile et fiable au quotidien. Son design intuitif et convivial permet une installation rapide et un fonctionnement sans tracas. De plus, sa conception robuste et sa qualité de construction garantissent une fiabilité à long terme, vous offrant ainsi une tranquillité d\'esprit totale lors de vos impressions importantes. Que vous soyez un utilisateur domestique ou professionnel, cette imprimante est prête à répondre à vos besoins d\'impression avec facilité et efficacité.'
            ],
            [
                'id' => 23,
                'sousTitre1' => 'Puissance de Calcul et Performances',
                'paragraph1' => 'Le serveur HPE ProLiant DL20 Gen10 Plus E-2314 est conçu pour offrir des performances de calcul fiables et évolutives pour les petites et moyennes entreprises. Doté d\'un processeur Intel® Xeon® E-2314 à 2,8 GHz et jusqu\'à 8 cœurs, ce serveur offre une puissance de traitement optimale pour une variété de charges de travail. Avec une mémoire cache pouvant atteindre 16 Mo et une vitesse maximale de processeur de 5,0 GHz, il garantit des performances fluides même lors des tâches les plus exigeantes.',
                'sousTitre2' => 'Mémoire et Stockage',
                'paragraph2' => 'Le serveur est équipé de 8 Go de mémoire DDR4 standard, offrant une grande capacité de traitement des données et une fiabilité optimale pour les opérations quotidiennes. De plus, avec deux lecteurs à grand facteur de forme NHP, ce serveur offre une flexibilité de stockage pour répondre aux besoins évolutifs de l\'entreprise, que ce soit pour le stockage des données ou pour la mise en place de solutions de stockage plus avancées.',
                'sousTitre3' => 'Gestion Simplifiée',
                'paragraph3' => 'Grâce à la gestion de l\'infrastructure HPE iLO5 intégrée, ce serveur offre une administration simplifiée et une surveillance à distance, permettant aux administrateurs informatiques de gérer efficacement le serveur depuis n\'importe où. Cette fonctionnalité offre un contrôle complet sur le matériel, la gestion de l\'alimentation, la surveillance des performances et la gestion des correctifs logiciels, ce qui garantit un fonctionnement optimal du serveur en tout temps.',
                'sousTitre4' => 'Connectivité et Stockage des Données',
                'paragraph4' => 'Le serveur est équipé d\'un contrôleur réseau HPE BCM5720 1 Go intégré, assurant une connectivité réseau rapide et fiable pour les besoins de communication et d\'accès aux données. De plus, avec le contrôleur de stockage Intel® VROC SATA, il offre une gestion efficace du stockage des données, garantissant la disponibilité et l\'intégrité des données de l\'entreprise.',
                'sousTitre5' => 'Compact et Facile à Intégrer',
                'paragraph5' => 'Avec son format compact de 1U, ce serveur est facile à intégrer dans n\'importe quel rack de serveur standard. Ses dimensions de 4,32 x 43,46 x 38,22 cm et son poids allant de 6 kg minimum à 9,46 kg maximum en font un choix idéal pour les environnements informatiques avec des contraintes d\'espace. En résumé, le serveur HPE ProLiant DL20 Gen10 Plus offre une combinaison puissante de performances, de fiabilité et de gestion simplifiée pour répondre aux besoins informatiques variés des entreprises.'
            ],
            [
                'id' => 24,
                'sousTitre1' => 'Performances Fiables pour les Tâches Quotidiennes',
                'paragraph1' => 'L\'ordinateur portable Lenovo V15 G3 IAP est conçu pour offrir des performances fiables et rapides pour répondre à vos besoins informatiques quotidiens. Équipé d\'un processeur Intel® Core™ i3-1215U avec 6 cœurs et une vitesse allant jusqu\'à 4,4 GHz en mode turbo, cet ordinateur portable offre une puissance de traitement exceptionnelle pour les applications multitâches, la navigation sur le Web, la productivité bureautique et le divertissement multimédia.',
                'sousTitre2' => 'Expérience Visuelle Immersive',
                'paragraph2' => 'Profitez d\'une expérience visuelle immersive grâce à l\'écran Full HD de 15,6 pouces de l\'ordinateur portable Lenovo V15 G3 IAP. Avec une résolution de 1920x1080 pixels et une luminosité de 250 nits, cet écran offre des images nettes et détaillées pour une visualisation optimale de vos contenus. De plus, la technologie anti-reflet garantit un confort visuel même dans des environnements lumineux.',
                'sousTitre3' => 'Stockage Rapide et Spacieux',
                'paragraph3' => 'Avec un SSD M.2 PCIe® 4.0x4 NVMe® de 256 Go, cet ordinateur portable offre un stockage rapide et spacieux pour vos fichiers, applications et données. Le SSD assure des temps de démarrage rapides, des transferts de fichiers fluides et une réactivité globale du système. Vous bénéficiez ainsi d\'une expérience informatique fluide et sans ralentissement, même lors de l\'exécution de plusieurs applications simultanément.',
                'sousTitre4' => 'Flexibilité et Personnalisation',
                'paragraph4' => 'Livré avec FreeDOS préinstallé, l\'ordinateur portable Lenovo V15 G3 IAP offre une flexibilité totale pour installer le système d\'exploitation de votre choix. Que vous préfériez Windows, Linux ou tout autre système d\'exploitation, vous pouvez personnaliser votre expérience informatique selon vos préférences. De plus, le clavier AZERTY français offre une expérience de frappe confortable, même lors d\'une utilisation prolongée.',
                'sousTitre5' => 'Portabilité et Confort',
                'paragraph5' => 'Avec un poids à partir de seulement 1,7 kg, cet ordinateur portable est parfaitement adapté aux déplacements quotidiens. Son design portable et léger en fait un compagnon idéal pour les professionnels en déplacement, les étudiants et les utilisateurs domestiques. Malgré sa portabilité, il offre des performances fiables et une autonomie de batterie suffisante pour une utilisation tout au long de la journée, vous permettant de rester productif où que vous soyez.'
            ],
            [
                'id' => 25,
                'sousTitre1' => 'Une Expérience Visuelle Immersive',
                'paragraph1' => 'Plongez au cœur de l\'action avec l\'écran plat Samsung Smart Monitor S5 de 32 pouces, conçu pour offrir une expérience visuelle immersive. Doté d\'une dalle VA (Vertical Alignment) et d\'un rétroéclairage LED, cet écran offre des couleurs riches et un contraste saisissant, garantissant une qualité d\'image exceptionnelle pour tous vos contenus. Que vous regardiez des films, jouiez à des jeux ou travailliez sur des projets créatifs, chaque détail est rendu avec une netteté époustouflante grâce à sa résolution Full HD de 1920 x 1080 pixels.',
                'sousTitre2' => 'Réactivité et Fluidité',
                'paragraph2' => 'Profitez d\'une expérience de jeu fluide et réactive grâce à un temps de réponse rapide de 4 ms (gris à gris). Cette réactivité assure une transition en douceur des images rapides, offrant une expérience de jeu immersive sans flou de mouvement. Que vous soyez un joueur passionné ou un utilisateur occasionnel, cet écran répondra à vos besoins en offrant une qualité d\'affichage exceptionnelle à chaque utilisation.',
                'sousTitre3' => 'Connectivité Polyvalente',
                'paragraph3' => 'Avec une connectivité polyvalente comprenant des ports HDMI et un USB Hub, l\'écran Samsung Smart Monitor S5 vous permet de connecter facilement une gamme d\'appareils, tels que des consoles de jeu, des lecteurs multimédias, des ordinateurs portables et bien plus encore. Cette polyvalence vous offre la liberté de profiter de vos contenus préférés avec un seul écran, éliminant ainsi le besoin de plusieurs moniteurs ou périphériques.',
                'sousTitre4' => 'Réglages de Confort',
                'paragraph4' => 'Personnalisez votre expérience de visualisation grâce aux options de réglage de la position de l\'écran. Avec une plage allant de -2,0 ° à +22,0 °, vous pouvez ajuster l\'inclinaison de l\'écran pour trouver l\'angle de vision idéal. Que vous préfériez une position légèrement inclinée pour une visualisation confortable ou un angle plus vertical pour une productivité accrue, cet écran s\'adapte à vos besoins.',
                'sousTitre5' => 'Design Élégant et Moderne',
                'paragraph5' => 'Enfin, avec son design plat et moderne, cet écran apporte une touche d\'élégance à n\'importe quel espace de travail ou de divertissement. Que vous l\'installiez dans votre bureau à domicile, votre salon ou votre salle de jeux, il ajoutera une esthétique sophistiquée à votre environnement, tout en offrant des performances exceptionnelles.'
            ],
            [
                'id' => 26,
                'sousTitre1' => 'Protection Fiable pour Vos Appareils Électroniques',
                'paragraph1' => 'L\'onduleur Line-interactive Eaton 5E 1200 USB offre une protection fiable pour vos équipements électroniques sensibles contre les fluctuations de tension et les coupures de courant imprévues. Avec une capacité de puissance de 660 W / 1200 VA, cet onduleur est capable de maintenir vos appareils en fonctionnement pendant les pannes de courant, ce qui protège vos données et vos équipements contre les dommages potentiellement coûteux.',
                'sousTitre2' => 'Technologie Line-interactive pour une Alimentation Stable',
                'paragraph2' => 'Grâce à sa technologie Line-interactive, cet onduleur est capable de réguler automatiquement la tension entrante, garantissant ainsi une alimentation stable pour vos appareils connectés. Cette technologie corrige les fluctuations de tension tout en minimisant l\'utilisation de la batterie, ce qui prolonge sa durée de vie et assure une protection continue en cas de panne de courant prolongée.',
                'sousTitre3' => 'Connectivité Pratique pour Vos Appareils',
                'paragraph3' => 'Équipé de 6 prises C13 en sortie et d\'une prise C14 en entrée, cet onduleur offre une connectivité pratique pour vos appareils électroniques. Vous pouvez ainsi protéger plusieurs équipements essentiels tels que des ordinateurs, des routeurs, des modems et des périphériques de stockage contre les dommages causés par les surtensions et les coupures de courant.',
                'sousTitre4' => 'Compatibilité Universelle et Facile à Installer',
                'paragraph4' => 'Avec une plage de tension de sortie de 195-257 V et une fréquence de sortie de 50/60 Hz, cet onduleur est compatible avec une variété d\'appareils électroniques. De plus, son installation est rapide et facile, ce qui en fait un choix idéal pour les utilisateurs domestiques et de petits bureaux recherchant une protection fiable et abordable pour leurs appareils sensibles.',
                'sousTitre5' => 'Compact et Silencieux',
                'paragraph5' => 'Enfin, avec son design compact et discret, cet onduleur s\'intègre facilement dans n\'importe quel environnement domestique ou de bureau. Sa conception silencieuse garantit un fonctionnement discret, ce qui en fait un choix parfait pour les espaces de travail où le silence est essentiel.'
            ],
            [
                'id' => 27,
                'sousTitre1' => 'Puissance Informatique Avancée',
                'paragraph1' => 'La station de travail HP Z6 Tower G5 (6E455AV-00342) offre une puissance informatique de pointe pour répondre aux besoins des professionnels les plus exigeants. Équipée d\'un processeur Intel Xeon W5-3423 12C 220W, cette machine offre des performances de calcul exceptionnelles, idéales pour les charges de travail intensives telles que la modélisation 3D, la conception graphique et l\'analyse de données.',
                'sousTitre2' => 'Mémoire et Stockage Fiables',
                'paragraph2' => 'Avec 16 Go de mémoire DDR5 4800 DIMM ECC REG, la HP Z6 Tower G5 garantit une exécution fluide des applications multitâches et gourmandes en ressources. De plus, le disque dur de 2 To PCIe 2280 TLC M.2 2nd SSD offre un espace de stockage généreux pour vos projets, données et programmes, permettant un accès rapide et efficace à vos fichiers.',
                'sousTitre3' => 'Performances Graphiques de Qualité Professionnelle',
                'paragraph3' => 'La carte graphique NVIDIA T1000 8GB 4mDP GFX assure des performances graphiques de qualité professionnelle, adaptées à une gamme étendue d\'applications graphiques et de visualisation. Que vous travailliez sur des rendus 3D, des modèles CAO complexes ou des projets de montage vidéo, cette carte graphique garantit des images fluides et détaillées.',
                'sousTitre4' => 'Flexibilité d\'Utilisation et de Configuration',
                'paragraph4' => 'Livré avec FreeDOS, cet ordinateur offre une flexibilité maximale pour installer le système d\'exploitation de votre choix, adapté à vos besoins professionnels spécifiques. De plus, l\'unité centrale sans écran offre une configuration personnalisable, permettant aux utilisateurs de choisir les composants et les périphériques qui conviennent le mieux à leurs besoins.',
                'sousTitre5' => 'Fiabilité et Durabilité',
                'paragraph5' => 'Conçue pour une utilisation professionnelle intensive, la HP Z6 Tower G5 est robuste et fiable. Sa construction solide et ses composants de qualité garantissent une durabilité à long terme, tandis que ses fonctionnalités de gestion thermique avancées assurent un fonctionnement efficace même lors de charges de travail soutenues.'
            ],

            [
                'id' => 28,
                'sousTitre1' => 'Connectivité Internet Haut Débit Partout',
                'paragraph1' => 'Le Modem/Routeur 4G LTE WiFi TP-Link Archer MR200 AC750 vous offre la possibilité de profiter d\'une connexion Internet haut débit où que vous soyez. Grâce à sa compatibilité avec les réseaux 4G LTE, vous pouvez accéder à Internet même dans les zones où le débit ADSL est faible, tant que vous bénéficiez d\'une couverture 4G suffisante.',
                'sousTitre2' => 'Combinaison 2-en-1 Pratique',
                'paragraph2' => 'Ce dispositif combine un modem 4G LTE et un routeur WiFi, offrant ainsi une solution complète pour accéder à Internet et partager la connexion avec plusieurs appareils. Cette double fonctionnalité en fait un choix pratique pour les foyers, les petites entreprises et même pour une utilisation en déplacement.',
                'sousTitre3' => 'Débit Élevé et Partage Facile',
                'paragraph3' => 'Avec un débit pouvant atteindre 150 Mbps, le Modem/Routeur TP-Link Archer MR200 AC750 assure une connexion rapide et stable pour toutes vos activités en ligne. Vous pouvez facilement partager votre connexion 4G avec plusieurs appareils, que ce soit pour le travail, les loisirs ou les besoins domestiques.',
                'sousTitre4' => 'Antennes Externes pour une Réception Optimale',
                'paragraph4' => 'Les antennes externes du routeur garantissent une réception optimale du signal 4G, ce qui permet d\'obtenir une connexion Internet stable et fiable. Que vous soyez à l\'intérieur ou à l\'extérieur de votre maison, vous pouvez compter sur une connectivité de qualité pour toutes vos activités en ligne.',
                'sousTitre5' => 'Installation Simple et Polyvalence d\'Utilisation',
                'paragraph5' => 'L\'installation du Modem/Routeur 4G LTE WiFi TP-Link Archer MR200 AC750 est simple et rapide, ce qui vous permet de commencer à utiliser Internet en un rien de temps. De plus, avec la possibilité de connecter jusqu\'à 64 appareils simultanément, il offre une grande polyvalence pour répondre aux besoins de votre foyer ou de votre entreprise, que ce soit pour le travail, les loisirs ou les divertissements en ligne.'
            ],
            [
                'id' => 29,
                'sousTitre1' => 'Qualité d\'image exceptionnelle',
                'paragraph1' => 'La webcam Logitech BRIO ULTRA HD PRO offre une qualité d\'image exceptionnelle pour tous vos appels vidéo et vos diffusions en direct. Avec une résolution Ultra HD 4K (4096 x 2160 pixels) à 30 images par seconde, ainsi que la prise en charge de la vidéo en Full HD 1080p à 30 ou 60 images par seconde, et la vidéo en HD 720p à 30, 60 ou 90 images par seconde, vous bénéficiez d\'une netteté et d\'une clarté incomparables.',
                'sousTitre2' => 'Connectivité Plug-and-Play',
                'paragraph2' => 'Grâce à sa connectivité USB prête à l\'emploi, l\'installation de la webcam est rapide et simple. Il vous suffit de la brancher sur un port USB de votre ordinateur, et vous êtes prêt à utiliser toutes ses fonctionnalités sans avoir besoin de télécharger des pilotes supplémentaires.',
                'sousTitre3' => 'Large champ de vision et zoom numérique',
                'paragraph3' => 'Avec un champ de vision diagonal de 90°, horizontal de 82,1° et vertical de 52,2°, la webcam BRIO capture un large espace, idéal pour les réunions de groupe ou les présentations en ligne. De plus, le zoom numérique 5x en Full HD vous permet de vous concentrer sur les détails importants avec une grande précision.',
                'sousTitre4' => 'Son cristallin et technologie antiparasite',
                'paragraph4' => 'La webcam est équipée de deux microphones omnidirectionnels intégrés qui captent le son avec une grande clarté et une réduction du bruit de fond. Vous pouvez ainsi être sûr que votre voix sera parfaitement entendue pendant vos appels vidéo ou vos enregistrements.',
                'sousTitre5' => 'Options de fixation flexibles',
                'paragraph5' => 'Que vous souhaitiez fixer la webcam sur votre écran d\'ordinateur portable, votre moniteur ou un trépied, la BRIO offre plusieurs options de fixation pour s\'adapter à vos besoins. Vous pouvez utiliser le clip intégré pour une installation facile sur un écran, ou opter pour un trépied pour une stabilité accrue lors des diffusions en direct ou des enregistrements.'
            ],
            [
                'id' => 30,
                'sousTitre1' => 'Stockage généreux et fiabilité garantie',
                'paragraph1' => 'La boîte de 10 DVD+R Verbatim Double Layer offre une capacité de stockage généreuse de 8,5 Go par disque, permettant ainsi d\'enregistrer une grande quantité de données, de vidéos, de photos ou de musique. Cette capacité étendue en fait un choix idéal pour les besoins de stockage importants, que ce soit pour des projets professionnels ou personnels. De plus, la technologie MKM/Verbatim garantit une fiabilité exceptionnelle à chaque enregistrement, assurant la sécurité de vos données sur le long terme.',
                'sousTitre2' => 'Compatibilité étendue',
                'paragraph2' => 'Grâce à une collaboration étroite avec les fabricants de lecteurs, le département de Recherche et Développement de Mitsubishi Chemical assure une compatibilité étendue des disques Verbatim avec une large gamme de lecteurs DVD et Blu-ray. Cette compatibilité garantie vous permet d\'utiliser ces DVD+R avec confiance sur différents appareils, qu\'ils soient des lecteurs de salon, des ordinateurs portables ou des graveurs externes.',
                'sousTitre3' => 'Polyvalence d\'utilisation',
                'paragraph3' => 'Les DVD+R Verbatim Double Layer sont idéaux pour une variété d\'utilisations, que ce soit pour le stockage de données informatiques, la sauvegarde de fichiers importants, l\'enregistrement de vidéos amateurs, la création de diaporamas de photos ou la compilation de musique. Leur grande capacité de stockage et leur fiabilité en font un support polyvalent pour répondre à tous vos besoins en matière de stockage et de partage de données.',
                'sousTitre4' => 'Surface matte silver élégante',
                'paragraph4' => 'La surface matte silver des DVD+R Verbatim offre un aspect élégant et professionnel. Cette finition matte permet également un étiquetage facile avec un marqueur permanent, vous permettant d\'organiser et de personnaliser vos disques en fonction de leur contenu. Que vous les utilisiez pour des projets professionnels ou personnels, ces DVD+R offrent une présentation soignée et professionnelle.',
                'sousTitre5' => 'Emballage économique de 10 disques',
                'paragraph5' => 'Avec cette boîte de 10 DVD+R, vous disposez d\'un emballage économique et pratique pour vos besoins de stockage. Que ce soit pour archiver des données importantes, partager des vidéos avec des amis ou graver des souvenirs précieux, cette boîte vous assure un stock fiable et durable de DVD+R Verbatim Double Layer pour répondre à vos besoins de stockage à long terme.'
            ],
            [
                'id' => 31,
                'sousTitre1' => 'Qualité d\'impression exceptionnelle',
                'paragraph1' => 'La ramette de papier Navigator Universal NAVA480 est synonyme de qualité d\'impression exceptionnelle. Conçu pour répondre aux besoins les plus exigeants en matière d\'impression, ce papier offre des résultats nets et précis à chaque utilisation. Que vous imprimiez des documents professionnels, des rapports ou des projets créatifs, ce papier assure une reproduction fidèle des couleurs et des détails, garantissant des impressions de haute qualité.',
                'sousTitre2' => 'Certification FSC pour la durabilité',
                'paragraph2' => 'Soucieux de l\'impact environnemental, le papier Navigator Universal NAVA480 est certifié FSC (Forest Stewardship Council), garantissant une gestion responsable des forêts. En choisissant ce papier, vous contribuez à la préservation des ressources forestières et à la protection de la biodiversité. Cette certification atteste également de l\'engagement du fabricant envers des pratiques durables tout au long de la chaîne d\'approvisionnement.',
                'sousTitre3' => 'Grammage optimal pour polyvalence',
                'paragraph3' => 'Avec un grammage de 80g/m², ce papier offre un équilibre parfait entre légèreté et résistance. Il est suffisamment léger pour une manipulation facile et une alimentation sans accroc dans votre imprimante, tout en étant assez résistant pour garantir des impressions durables. Ce grammage optimal assure également une polyvalence d\'utilisation, adaptée à une variété d\'applications d\'impression, des documents quotidiens aux projets professionnels.',
                'sousTitre4' => 'Dimensions standard A4 pour compatibilité universelle',
                'paragraph4' => 'Les dimensions standard A4 (21 x 29,7 cm) de ce papier en font un choix universellement compatible avec la plupart des imprimantes et des applications d\'impression. Que vous utilisiez une imprimante domestique, de bureau ou professionnelle, ce papier s\'adapte parfaitement à votre équipement, vous offrant une expérience d\'impression fluide et sans souci.',
                'sousTitre5' => 'Quantité généreuse pour une utilisation prolongée',
                'paragraph5' => 'Chaque paquet de la ramette de papier Navigator Universal NAVA480 contient 500 feuilles de papier, vous offrant une quantité généreuse pour répondre à vos besoins d\'impression à long terme. Cette grande quantité de papier vous assure une réserve suffisante pour vos projets futurs, réduisant ainsi la fréquence des réapprovisionnements et vous permettant de rester productif sans interruption.'
            ],
            [
                'id' => 32,
                'sousTitre1' => 'Connexion Pratique',
                'paragraph1' => 'Ce hub USB C ajoute 4 ports USB 3.0 de type A à votre appareil USB C, pratique pour connecter les anciens appareils à votre nouvel ordinateur portable/tablette/smartphone USB C. Contrairement aux autres hub USB C, il est doté d\'un port Micro USB pour connecter une alimentation externe 5V 2,4A (max), assurant une performance stable des périphériques énergivores.',
                'sousTitre2' => 'Haute Vitesse',
                'paragraph2' => 'Ce hub USB C transforme un seul port USB C en 4 ports de données USB 3.1 Gen 1 (USB 3.0) avec des taux de transfert de données allant jusqu\'à 5 Gbps, il vous permet de transférer un film HD en quelques secondes. Il est rétrocompatible avec USB 2.0 et USB 1.1.',
                'sousTitre3' => 'Forte Compatibilité',
                'paragraph3' => 'Ce hub USB C 4 ports est compatible avec les ordinateurs portables/ tablettes/ smartphones USB C pour transférer les données, tels que MacBook Pro, iPad Pro 2020/ 2018, MacBook Air 2020/ 2019, iMac, Redmi Note 10/ Note 9/ Note 8, Galaxy Note 10/ S21/ S20/ S10/ S9/ S8/ A52/ A02s, etc. Compatible avec Windows 10/ 8.1/ 8/ 7/ Vista/ XP, Mac OS X, Linux, aucun pilote nécessaire.',
                'sousTitre4' => 'Design Fin et Léger',
                'paragraph4' => 'Très compact (104 x 30 x 10 mm), de forme rectangulaire et avec un poids léger, le hub (1 USB C vers 4 Ports USB A) se prête bien aux déplacements et est votre meilleur compagnon de voyage.',
                'sousTitre5' => 'Qualité Fiable',
                'paragraph5' => 'Chip intégré de ce hub USB C vers USB 3.0 protège vos appareils connectés contre les courts-circuits, les surtensions, les surchauffe et les surintensités, en assurant une transmission plus stable et plus rapide. De plus, le voyant LED vous montre l\'état de fonctionnement.'
            ]
        ]);
    }
}
