<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DetailsImages;

class DetailsImagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DetailsImages::insert([
            [
                'id' => 1,
                'smallImage1' => 'ordinateur-hp-24-cr0000nk-aio-pc-small-1.png',
                'zoomImage1' => 'ordinateur-hp-24-cr0000nk-aio-pc-zoom-1.jpg',
                'smallImage2' => 'ordinateur-hp-24-cr0000nk-aio-pc-small-2.png',
                'zoomImage2' => 'ordinateur-hp-24-cr0000nk-aio-pc-zoom-2.jpg',
                'smallImage3' => 'ordinateur-hp-24-cr0000nk-aio-pc-small-3.png',
                'zoomImage3' => 'ordinateur-hp-24-cr0000nk-aio-pc-zoom-3.jpg',
                'smallImage4' => 'ordinateur-hp-24-cr0000nk-aio-pc-small-4.png',
                'zoomImage4' => 'ordinateur-hp-24-cr0000nk-aio-pc-zoom-4.jpg',
                'smallImage5' => 'ordinateur-hp-24-cr0000nk-aio-pc-small-5.png',
                'zoomImage5' => 'ordinateur-hp-24-cr0000nk-aio-pc-zoom-5.jpg'
            ],
            [
                'id' => 2,
                'smallImage1' => 'volant-de-course-Logitech-G29-Force-pour-Xbox-Series-X|S-XboxOne-PC-small-1.png',
                'zoomImage1' => 'volant-de-course-Logitech-G29-Force-pour-Xbox-Series-X|S-XboxOne-PC-zoom-1.jpg',
                'smallImage2' => 'volant-de-course-Logitech-G29-Force-pour-Xbox-Series-X|S-XboxOne-PC-small-2.png',
                'zoomImage2' => 'volant-de-course-Logitech-G29-Force-pour-Xbox-Series-X|S-XboxOne-PC-zoom-2.jpg',
                'smallImage3' => 'volant-de-course-Logitech-G29-Force-pour-Xbox-Series-X|S-XboxOne-PC-small-3.png',
                'zoomImage3' => 'volant-de-course-Logitech-G29-Force-pour-Xbox-Series-X|S-XboxOne-PC-zoom-3.jpg',
                'smallImage4' => 'volant-de-course-Logitech-G29-Force-pour-Xbox-Series-X|S-XboxOne-PC-small-4.png',
                'zoomImage4' => 'volant-de-course-Logitech-G29-Force-pour-Xbox-Series-X|S-XboxOne-PC-zoom-4.jpg',
                'smallImage5' => 'volant-de-course-Logitech-G29-Force-pour-Xbox-Series-X|S-XboxOne-PC-small-5.png',
                'zoomImage5' => 'volant-de-course-Logitech-G29-Force-pour-Xbox-Series-X|S-XboxOne-PC-zoom-5.jpg'
            ],
            [
                'id' => 3,
                'smallImage1' => 'Epson-EB-FH52-Vidéoprojecteur-Full-HD-1920x1080-V11H978040-small-1.png',
                'zoomImage1' => 'Epson-EB-FH52-Vidéoprojecteur-Full-HD-1920x1080-V11H978040-zoom-1.jpg',
                'smallImage2' => 'Epson-EB-FH52-Vidéoprojecteur-Full-HD-1920x1080-V11H978040-small-2.png',
                'zoomImage2' => 'Epson-EB-FH52-Vidéoprojecteur-Full-HD-1920x1080-V11H978040-zoom-2.jpg',
                'smallImage3' => 'Epson-EB-FH52-Vidéoprojecteur-Full-HD-1920x1080-V11H978040-small-3.png',
                'zoomImage3' => 'Epson-EB-FH52-Vidéoprojecteur-Full-HD-1920x1080-V11H978040-zoom-3.jpg',
                'smallImage4' => 'Epson-EB-FH52-Vidéoprojecteur-Full-HD-1920x1080-V11H978040-small-4.png',
                'zoomImage4' => 'Epson-EB-FH52-Vidéoprojecteur-Full-HD-1920x1080-V11H978040-zoom-4.jpg',
                'smallImage5' => 'Epson-EB-FH52-Vidéoprojecteur-Full-HD-1920x1080-V11H978040-small-5.png',
                'zoomImage5' => 'Epson-EB-FH52-Vidéoprojecteur-Full-HD-1920x1080-V11H978040-zoom-5.jpg'
            ],
            [
                'id' => 4,
                'smallImage1' => 'Module-WiFi-Epson-ELPAP11-pour-projecteur-Dual-Fonction-5GHZ-V12H005A01-small-1.png',
                'zoomImage1' => 'Module-WiFi-Epson-ELPAP11-pour-projecteur-Dual-Fonction-5GHZ-V12H005A01-zoom-1.jpg',
                'smallImage2' => 'Module-WiFi-Epson-ELPAP11-pour-projecteur-Dual-Fonction-5GHZ-V12H005A01-small-2.png',
                'zoomImage2' => 'Module-WiFi-Epson-ELPAP11-pour-projecteur-Dual-Fonction-5GHZ-V12H005A01-zoom-2.jpg',
                'smallImage3' => 'Module-WiFi-Epson-ELPAP11-pour-projecteur-Dual-Fonction-5GHZ-V12H005A01-small-3.png',
                'zoomImage3' => 'Module-WiFi-Epson-ELPAP11-pour-projecteur-Dual-Fonction-5GHZ-V12H005A01-zoom-3.jpg',
                'smallImage4' => 'Module-WiFi-Epson-ELPAP11-pour-projecteur-Dual-Fonction-5GHZ-V12H005A01-small-4.png',
                'zoomImage4' => 'Module-WiFi-Epson-ELPAP11-pour-projecteur-Dual-Fonction-5GHZ-V12H005A01-zoom-4.jpg',
                'smallImage5' => 'Module-WiFi-Epson-ELPAP11-pour-projecteur-Dual-Fonction-5GHZ-V12H005A01-small-5.png',
                'zoomImage5' => 'Module-WiFi-Epson-ELPAP11-pour-projecteur-Dual-Fonction-5GHZ-V12H005A01-zoom-5.jpg'
            ],
            [
                'id' => 5,
                'smallImage1' => 'Imprimante-Multifonction-Laser-Couleur-Canon-I-SENSYS-MF657Cdw-small-1.png',
                'zoomImage1' => 'Imprimante-Multifonction-Laser-Couleur-Canon-I-SENSYS-MF657Cdw-zoom-1.jpg',
                'smallImage2' => 'Imprimante-Multifonction-Laser-Couleur-Canon-I-SENSYS-MF657Cdw-small-2.png',
                'zoomImage2' => 'Imprimante-Multifonction-Laser-Couleur-Canon-I-SENSYS-MF657Cdw-zoom-2.jpg',
                'smallImage3' => 'Imprimante-Multifonction-Laser-Couleur-Canon-I-SENSYS-MF657Cdw-small-3.png',
                'zoomImage3' => 'Imprimante-Multifonction-Laser-Couleur-Canon-I-SENSYS-MF657Cdw-zoom-3.jpg',
                'smallImage4' => 'Imprimante-Multifonction-Laser-Couleur-Canon-I-SENSYS-MF657Cdw-small-4.png',
                'zoomImage4' => 'Imprimante-Multifonction-Laser-Couleur-Canon-I-SENSYS-MF657Cdw-zoom-4.jpg',
                'smallImage5' => 'Imprimante-Multifonction-Laser-Couleur-Canon-I-SENSYS-MF657Cdw-small-5.png',
                'zoomImage5' => 'Imprimante-Multifonction-Laser-Couleur-Canon-I-SENSYS-MF657Cdw-zoom-5.jpg'
            ],
            [
                'id' => 6,
                'smallImage1' => 'Disque-dur-externe-LaCie-d2-Professional-10-To-small-1.png',
                'zoomImage1' => 'Disque-dur-externe-LaCie-d2-Professional-10-To-zoom-1.jpg',
                'smallImage2' => 'Disque-dur-externe-LaCie-d2-Professional-10-To-small-2.png',
                'zoomImage2' => 'Disque-dur-externe-LaCie-d2-Professional-10-To-zoom-2.jpg',
                'smallImage3' => 'Disque-dur-externe-LaCie-d2-Professional-10-To-small-3.png',
                'zoomImage3' => 'Disque-dur-externe-LaCie-d2-Professional-10-To-zoom-3.jpg',
                'smallImage4' => 'Disque-dur-externe-LaCie-d2-Professional-10-To-small-4.png',
                'zoomImage4' => 'Disque-dur-externe-LaCie-d2-Professional-10-To-zoom-4.jpg',
                'smallImage5' => 'Disque-dur-externe-LaCie-d2-Professional-10-To-small-5.png',
                'zoomImage5' => 'Disque-dur-externe-LaCie-d2-Professional-10-To-zoom-5.jpg'
            ],
            [
                'id' => 7,
                'smallImage1' => 'Disque-Dur-portable-ADATA-HV620S-2.5”-4TB-USB-3.1-Noir-small-1.png',
                'zoomImage1' => 'Disque-Dur-portable-ADATA-HV620S-2.5”-4TB-USB-3.1-Noir-zoom-1.jpg',
                'smallImage2' => 'Disque-Dur-portable-ADATA-HV620S-2.5”-4TB-USB-3.1-Noir-small-2.png',
                'zoomImage2' => 'Disque-Dur-portable-ADATA-HV620S-2.5”-4TB-USB-3.1-Noir-zoom-2.jpg',
                'smallImage3' => 'Disque-Dur-portable-ADATA-HV620S-2.5”-4TB-USB-3.1-Noir-small-3.png',
                'zoomImage3' => 'Disque-Dur-portable-ADATA-HV620S-2.5”-4TB-USB-3.1-Noir-zoom-3.jpg',
                'smallImage4' => 'Disque-Dur-portable-ADATA-HV620S-2.5”-4TB-USB-3.1-Noir-small-4.png',
                'zoomImage4' => 'Disque-Dur-portable-ADATA-HV620S-2.5”-4TB-USB-3.1-Noir-zoom-4.jpg',
                'smallImage5' => 'Disque-Dur-portable-ADATA-HV620S-2.5”-4TB-USB-3.1-Noir-small-5.png',
                'zoomImage5' => 'Disque-Dur-portable-ADATA-HV620S-2.5”-4TB-USB-3.1-Noir-zoom-5.jpg'
            ],
            [
                'id' => 8,
                'smallImage1' => 'TP-Link-RE505X-prolongateur-réseau-Émetteur-et-récepteur-réseau-Blanc-small-1.png',
                'zoomImage1' => 'TP-Link-RE505X-prolongateur-réseau-Émetteur-et-récepteur-réseau-Blanc-zoom-1.jpg',
                'smallImage2' => 'TP-Link-RE505X-prolongateur-réseau-Émetteur-et-récepteur-réseau-Blanc-small-2.png',
                'zoomImage2' => 'TP-Link-RE505X-prolongateur-réseau-Émetteur-et-récepteur-réseau-Blanc-zoom-2.jpg',
                'smallImage3' => 'TP-Link-RE505X-prolongateur-réseau-Émetteur-et-récepteur-réseau-Blanc-small-3.png',
                'zoomImage3' => 'TP-Link-RE505X-prolongateur-réseau-Émetteur-et-récepteur-réseau-Blanc-zoom-3.jpg',
                'smallImage4' => 'TP-Link-RE505X-prolongateur-réseau-Émetteur-et-récepteur-réseau-Blanc-small-4.png',
                'zoomImage4' => 'TP-Link-RE505X-prolongateur-réseau-Émetteur-et-récepteur-réseau-Blanc-zoom-4.jpg',
                'smallImage5' => 'TP-Link-RE505X-prolongateur-réseau-Émetteur-et-récepteur-réseau-Blanc-small-5.png',
                'zoomImage5' => 'TP-Link-RE505X-prolongateur-réseau-Émetteur-et-récepteur-réseau-Blanc-zoom-5.jpg'
            ],
            [
                'id' => 9,
                'smallImage1' => 'Ensemble-clavier-et-souris-sans-fil-ultra-fin-Logitech-MK470-AZERTY-small-1.png',
                'zoomImage1' => 'Ensemble-clavier-et-souris-sans-fil-ultra-fin-Logitech-MK470-AZERTY-zoom-1.jpg',
                'smallImage2' => 'Ensemble-clavier-et-souris-sans-fil-ultra-fin-Logitech-MK470-AZERTY-small-2.png',
                'zoomImage2' => 'Ensemble-clavier-et-souris-sans-fil-ultra-fin-Logitech-MK470-AZERTY-zoom-2.jpg',
                'smallImage3' => 'Ensemble-clavier-et-souris-sans-fil-ultra-fin-Logitech-MK470-AZERTY-small-3.png',
                'zoomImage3' => 'Ensemble-clavier-et-souris-sans-fil-ultra-fin-Logitech-MK470-AZERTY-zoom-3.jpg',
                'smallImage4' => 'Ensemble-clavier-et-souris-sans-fil-ultra-fin-Logitech-MK470-AZERTY-small-4.png',
                'zoomImage4' => 'Ensemble-clavier-et-souris-sans-fil-ultra-fin-Logitech-MK470-AZERTY-zoom-4.jpg',
                'smallImage5' => 'Ensemble-clavier-et-souris-sans-fil-ultra-fin-Logitech-MK470-AZERTY-small-5.png',
                'zoomImage5' => 'Ensemble-clavier-et-souris-sans-fil-ultra-fin-Logitech-MK470-AZERTY-zoom-5.jpg'
            ],
            [
                'id' => 10,
                'smallImage1' => 'Écran-24-Samsung-Essential-Monitor-S3-S31C-small-1.png',
                'zoomImage1' => 'Écran-24-Samsung-Essential-Monitor-S3-S31C-zoom-1.jpg',
                'smallImage2' => 'Écran-24-Samsung-Essential-Monitor-S3-S31C-small-2.png',
                'zoomImage2' => 'Écran-24-Samsung-Essential-Monitor-S3-S31C-zoom-2.jpg',
                'smallImage3' => 'Écran-24-Samsung-Essential-Monitor-S3-S31C-small-3.png',
                'zoomImage3' => 'Écran-24-Samsung-Essential-Monitor-S3-S31C-zoom-3.jpg',
                'smallImage4' => 'Écran-24-Samsung-Essential-Monitor-S3-S31C-small-4.png',
                'zoomImage4' => 'Écran-24-Samsung-Essential-Monitor-S3-S31C-zoom-4.jpg',
                'smallImage5' => 'Écran-24-Samsung-Essential-Monitor-S3-S31C-small-5.png',
                'zoomImage5' => 'Écran-24-Samsung-Essential-Monitor-S3-S31C-zoom-5.jpg'
            ],
            [
                'id' => 11,
                'smallImage1' => 'Ordinateur-de-bureau-Lenovo-ThinkCentre-neo-50t-small-1.png',
                'zoomImage1' => 'Ordinateur-de-bureau-Lenovo-ThinkCentre-neo-50t-zoom-1.jpg',
                'smallImage2' => 'Ordinateur-de-bureau-Lenovo-ThinkCentre-neo-50t-small-2.png',
                'zoomImage2' => 'Ordinateur-de-bureau-Lenovo-ThinkCentre-neo-50t-zoom-2.jpg',
                'smallImage3' => 'Ordinateur-de-bureau-Lenovo-ThinkCentre-neo-50t-small-3.png',
                'zoomImage3' => 'Ordinateur-de-bureau-Lenovo-ThinkCentre-neo-50t-zoom-3.jpg',
                'smallImage4' => 'Ordinateur-de-bureau-Lenovo-ThinkCentre-neo-50t-small-4.png',
                'zoomImage4' => 'Ordinateur-de-bureau-Lenovo-ThinkCentre-neo-50t-zoom-4.jpg',
                'smallImage5' => 'Ordinateur-de-bureau-Lenovo-ThinkCentre-neo-50t-small-5.png',
                'zoomImage5' => 'Ordinateur-de-bureau-Lenovo-ThinkCentre-neo-50t-zoom-5.jpg'
            ],
            [
                'id' => 12,
                'smallImage1' => 'Ordinateur-portable-Asus-ROG-Zephyrus-G14-small-1.png',
                'zoomImage1' => 'Ordinateur-portable-Asus-ROG-Zephyrus-G14-zoom-1.jpg',
                'smallImage2' => 'Ordinateur-portable-Asus-ROG-Zephyrus-G14-small-2.png',
                'zoomImage2' => 'Ordinateur-portable-Asus-ROG-Zephyrus-G14-zoom-2.jpg',
                'smallImage3' => 'Ordinateur-portable-Asus-ROG-Zephyrus-G14-small-3.png',
                'zoomImage3' => 'Ordinateur-portable-Asus-ROG-Zephyrus-G14-zoom-3.jpg',
                'smallImage4' => 'Ordinateur-portable-Asus-ROG-Zephyrus-G14-small-4.png',
                'zoomImage4' => 'Ordinateur-portable-Asus-ROG-Zephyrus-G14-zoom-4.jpg',
                'smallImage5' => 'Ordinateur-portable-Asus-ROG-Zephyrus-G14-small-5.png',
                'zoomImage5' => 'Ordinateur-portable-Asus-ROG-Zephyrus-G14-zoom-5.jpg'
            ],

            [
                'id' => 13,
                'smallImage1' => 'HP-Smart-Tank-530-Imprimante-multifonction-à-réservoirs-rechargeables-small-1.png',
                'zoomImage1' => 'HP-Smart-Tank-530-Imprimante-multifonction-à-réservoirs-rechargeables-zoom-1.jpg',
                'smallImage2' => 'HP-Smart-Tank-530-Imprimante-multifonction-à-réservoirs-rechargeables-small-2.png',
                'zoomImage2' => 'HP-Smart-Tank-530-Imprimante-multifonction-à-réservoirs-rechargeables-zoom-2.jpg',
                'smallImage3' => 'HP-Smart-Tank-530-Imprimante-multifonction-à-réservoirs-rechargeables-small-3.png',
                'zoomImage3' => 'HP-Smart-Tank-530-Imprimante-multifonction-à-réservoirs-rechargeables-zoom-3.jpg',
                'smallImage4' => 'HP-Smart-Tank-530-Imprimante-multifonction-à-réservoirs-rechargeables-small-4.png',
                'zoomImage4' => 'HP-Smart-Tank-530-Imprimante-multifonction-à-réservoirs-rechargeables-zoom-4.jpg',
                'smallImage5' => 'HP-Smart-Tank-530-Imprimante-multifonction-à-réservoirs-rechargeables-small-5.png',
                'zoomImage5' => 'HP-Smart-Tank-530-Imprimante-multifonction-à-réservoirs-rechargeables-zoom-5.jpg'
            ],
            [
                'id' => 14,
                'smallImage1' => 'Canon-PG-445-Noir-Cartouche-d-encre-Canon-d-origine-small-1.png',
                'zoomImage1' => 'Canon-PG-445-Noir-Cartouche-d-encre-Canon-d-origine-zoom-1.jpg',
                'smallImage2' => 'Canon-PG-445-Noir-Cartouche-d-encre-Canon-d-origine-small-2.png',
                'zoomImage2' => 'Canon-PG-445-Noir-Cartouche-d-encre-Canon-d-origine-zoom-2.jpg',
                'smallImage3' => 'Canon-PG-445-Noir-Cartouche-d-encre-Canon-d-origine-small-3.png',
                'zoomImage3' => 'Canon-PG-445-Noir-Cartouche-d-encre-Canon-d-origine-zoom-3.jpg',
                'smallImage4' => 'Canon-PG-445-Noir-Cartouche-d-encre-Canon-d-origine-small-4.png',
                'zoomImage4' => 'Canon-PG-445-Noir-Cartouche-d-encre-Canon-d-origine-zoom-4.jpg',
                'smallImage5' => 'Canon-PG-445-Noir-Cartouche-d-encre-Canon-d-origine-small-5.png',
                'zoomImage5' => 'Canon-PG-445-Noir-Cartouche-d-encre-Canon-d-origine-zoom-5.jpg'
            ],
            [
                'id' => 15,
                'smallImage1' => 'Disque-Dur-interne-SSD-Kingston-FURY-Renegade-Heatsink-M.2-2280-PCIe-Gen4-x4-NVMe-1-To-small-1.png',
                'zoomImage1' => 'Disque-Dur-interne-SSD-Kingston-FURY-Renegade-Heatsink-M.2-2280-PCIe-Gen4-x4-NVMe-1-To-zoom-1.jpg',
                'smallImage2' => 'Disque-Dur-interne-SSD-Kingston-FURY-Renegade-Heatsink-M.2-2280-PCIe-Gen4-x4-NVMe-1-To-small-2.png',
                'zoomImage2' => 'Disque-Dur-interne-SSD-Kingston-FURY-Renegade-Heatsink-M.2-2280-PCIe-Gen4-x4-NVMe-1-To-zoom-2.jpg',
                'smallImage3' => 'Disque-Dur-interne-SSD-Kingston-FURY-Renegade-Heatsink-M.2-2280-PCIe-Gen4-x4-NVMe-1-To-small-3.png',
                'zoomImage3' => 'Disque-Dur-interne-SSD-Kingston-FURY-Renegade-Heatsink-M.2-2280-PCIe-Gen4-x4-NVMe-1-To-zoom-3.jpg',
                'smallImage4' => 'Disque-Dur-interne-SSD-Kingston-FURY-Renegade-Heatsink-M.2-2280-PCIe-Gen4-x4-NVMe-1-To-small-4.png',
                'zoomImage4' => 'Disque-Dur-interne-SSD-Kingston-FURY-Renegade-Heatsink-M.2-2280-PCIe-Gen4-x4-NVMe-1-To-zoom-4.jpg',
                'smallImage5' => 'Disque-Dur-interne-SSD-Kingston-FURY-Renegade-Heatsink-M.2-2280-PCIe-Gen4-x4-NVMe-1-To-small-5.png',
                'zoomImage5' => 'Disque-Dur-interne-SSD-Kingston-FURY-Renegade-Heatsink-M.2-2280-PCIe-Gen4-x4-NVMe-1-To-zoom-5.jpg'
            ],
            [
                'id' => 16,
                'smallImage1' => 'Souris-gaming-filaire-Logitech-G502-X-small-1.png',
                'zoomImage1' => 'Souris-gaming-filaire-Logitech-G502-X-zoom-1.jpg',
                'smallImage2' => 'Souris-gaming-filaire-Logitech-G502-X-small-2.png',
                'zoomImage2' => 'Souris-gaming-filaire-Logitech-G502-X-zoom-2.jpg',
                'smallImage3' => 'Souris-gaming-filaire-Logitech-G502-X-small-3.png',
                'zoomImage3' => 'Souris-gaming-filaire-Logitech-G502-X-zoom-3.jpg',
                'smallImage4' => 'Souris-gaming-filaire-Logitech-G502-X-small-4.png',
                'zoomImage4' => 'Souris-gaming-filaire-Logitech-G502-X-zoom-4.jpg',
                'smallImage5' => 'Souris-gaming-filaire-Logitech-G502-X-small-5.png',
                'zoomImage5' => 'Souris-gaming-filaire-Logitech-G502-X-zoom-5.jpg'
            ],
            [
                'id' => 17,
                'smallImage1' => 'Clavier-gaming-G213-Prodigy-de-Logitech-avec-éclairage-RVB-et-anti-ghosting-Noir-Français-small-1.png',
                'zoomImage1' => 'Clavier-gaming-G213-Prodigy-de-Logitech-avec-éclairage-RVB-et-anti-ghosting-Noir-Français-zoom-1.jpg',
                'smallImage2' => 'Clavier-gaming-G213-Prodigy-de-Logitech-avec-éclairage-RVB-et-anti-ghosting-Noir-Français-small-2.png',
                'zoomImage2' => 'Clavier-gaming-G213-Prodigy-de-Logitech-avec-éclairage-RVB-et-anti-ghosting-Noir-Français-zoom-2.jpg',
                'smallImage3' => 'Clavier-gaming-G213-Prodigy-de-Logitech-avec-éclairage-RVB-et-anti-ghosting-Noir-Français-small-3.png',
                'zoomImage3' => 'Clavier-gaming-G213-Prodigy-de-Logitech-avec-éclairage-RVB-et-anti-ghosting-Noir-Français-zoom-3.jpg',
                'smallImage4' => 'Clavier-gaming-G213-Prodigy-de-Logitech-avec-éclairage-RVB-et-anti-ghosting-Noir-Français-small-4.png',
                'zoomImage4' => 'Clavier-gaming-G213-Prodigy-de-Logitech-avec-éclairage-RVB-et-anti-ghosting-Noir-Français-zoom-4.jpg',
                'smallImage5' => 'Clavier-gaming-G213-Prodigy-de-Logitech-avec-éclairage-RVB-et-anti-ghosting-Noir-Français-small-5.png',
                'zoomImage5' => 'Clavier-gaming-G213-Prodigy-de-Logitech-avec-éclairage-RVB-et-anti-ghosting-Noir-Français-zoom-5.jpg'
            ],
            [
                'id' => 18,
                'smallImage1' => 'Carte-Graphique-PNY-GeForce-GT-1030-NVIDIA-2-GB-GDDR4-small-1.png',
                'zoomImage1' => 'Carte-Graphique-PNY-GeForce-GT-1030-NVIDIA-2-GB-GDDR4-zoom-1.jpg',
                'smallImage2' => 'Carte-Graphique-PNY-GeForce-GT-1030-NVIDIA-2-GB-GDDR4-small-2.png',
                'zoomImage2' => 'Carte-Graphique-PNY-GeForce-GT-1030-NVIDIA-2-GB-GDDR4-zoom-2.jpg',
                'smallImage3' => 'Carte-Graphique-PNY-GeForce-GT-1030-NVIDIA-2-GB-GDDR4-small-3.png',
                'zoomImage3' => 'Carte-Graphique-PNY-GeForce-GT-1030-NVIDIA-2-GB-GDDR4-zoom-3.jpg',
                'smallImage4' => 'Carte-Graphique-PNY-GeForce-GT-1030-NVIDIA-2-GB-GDDR4-small-4.png',
                'zoomImage4' => 'Carte-Graphique-PNY-GeForce-GT-1030-NVIDIA-2-GB-GDDR4-zoom-4.jpg',
                'smallImage5' => 'Carte-Graphique-PNY-GeForce-GT-1030-NVIDIA-2-GB-GDDR4-small-5.png',
                'zoomImage5' => 'Carte-Graphique-PNY-GeForce-GT-1030-NVIDIA-2-GB-GDDR4-zoom-5.jpg'
            ],
            [
                'id' => 19,
                'smallImage1' => 'Switch-Smart-TP-Link-TL-SG2218-JetStream-16-ports-Gigabit-avec-2-slots-SFP-small-1.png',
                'zoomImage1' => 'Switch-Smart-TP-Link-TL-SG2218-JetStream-16-ports-Gigabit-avec-2-slots-SFP-zoom-1.jpg',
                'smallImage2' => 'Switch-Smart-TP-Link-TL-SG2218-JetStream-16-ports-Gigabit-avec-2-slots-SFP-small-2.png',
                'zoomImage2' => 'Switch-Smart-TP-Link-TL-SG2218-JetStream-16-ports-Gigabit-avec-2-slots-SFP-zoom-2.jpg',
                'smallImage3' => 'Switch-Smart-TP-Link-TL-SG2218-JetStream-16-ports-Gigabit-avec-2-slots-SFP-small-3.png',
                'zoomImage3' => 'Switch-Smart-TP-Link-TL-SG2218-JetStream-16-ports-Gigabit-avec-2-slots-SFP-zoom-3.jpg',
                'smallImage4' => 'Switch-Smart-TP-Link-TL-SG2218-JetStream-16-ports-Gigabit-avec-2-slots-SFP-small-4.png',
                'zoomImage4' => 'Switch-Smart-TP-Link-TL-SG2218-JetStream-16-ports-Gigabit-avec-2-slots-SFP-zoom-4.jpg',
                'smallImage5' => 'Switch-Smart-TP-Link-TL-SG2218-JetStream-16-ports-Gigabit-avec-2-slots-SFP-small-5.png',
                'zoomImage5' => 'Switch-Smart-TP-Link-TL-SG2218-JetStream-16-ports-Gigabit-avec-2-slots-SFP-zoom-5.jpg'
            ],
            [
                'id' => 20,
                'smallImage1' => 'Imprimante-A3-Multifonction-Jet-d-encre-HP-OfficeJet-Pro-7740-small-1.png',
                'zoomImage1' => 'Imprimante-A3-Multifonction-Jet-d-encre-HP-OfficeJet-Pro-7740-zoom-1.jpg',
                'smallImage2' => 'Imprimante-A3-Multifonction-Jet-d-encre-HP-OfficeJet-Pro-7740-small-2.png',
                'zoomImage2' => 'Imprimante-A3-Multifonction-Jet-d-encre-HP-OfficeJet-Pro-7740-zoom-2.jpg',
                'smallImage3' => 'Imprimante-A3-Multifonction-Jet-d-encre-HP-OfficeJet-Pro-7740-small-3.png',
                'zoomImage3' => 'Imprimante-A3-Multifonction-Jet-d-encre-HP-OfficeJet-Pro-7740-zoom-3.jpg',
                'smallImage4' => 'Imprimante-A3-Multifonction-Jet-d-encre-HP-OfficeJet-Pro-7740-small-4.png',
                'zoomImage4' => 'Imprimante-A3-Multifonction-Jet-d-encre-HP-OfficeJet-Pro-7740-zoom-4.jpg',
                'smallImage5' => 'Imprimante-A3-Multifonction-Jet-d-encre-HP-OfficeJet-Pro-7740-small-5.png',
                'zoomImage5' => 'Imprimante-A3-Multifonction-Jet-d-encre-HP-OfficeJet-Pro-7740-zoom-5.jpg'
            ],
            [
                'id' => 21,
                'smallImage1' => 'Sac-à-dos-Casual-Lenovo-ThinkPad-B210-15-6-small-1.png',
                'zoomImage1' => 'Sac-à-dos-Casual-Lenovo-ThinkPad-B210-15-6-zoom-1.jpg',
                'smallImage2' => 'Sac-à-dos-Casual-Lenovo-ThinkPad-B210-15-6-small-2.png',
                'zoomImage2' => 'Sac-à-dos-Casual-Lenovo-ThinkPad-B210-15-6-zoom-2.jpg',
                'smallImage3' => 'Sac-à-dos-Casual-Lenovo-ThinkPad-B210-15-6-small-3.png',
                'zoomImage3' => 'Sac-à-dos-Casual-Lenovo-ThinkPad-B210-15-6-zoom-3.jpg',
                'smallImage4' => 'Sac-à-dos-Casual-Lenovo-ThinkPad-B210-15-6-small-4.png',
                'zoomImage4' => 'Sac-à-dos-Casual-Lenovo-ThinkPad-B210-15-6-zoom-4.jpg',
                'smallImage5' => 'Sac-à-dos-Casual-Lenovo-ThinkPad-B210-15-6-small-5.png',
                'zoomImage5' => 'Sac-à-dos-Casual-Lenovo-ThinkPad-B210-15-6-zoom-5.jpg'
            ],
            [
                'id' => 22,
                'smallImage1' => 'Epson-EcoTank-L18050-Imprimante-Photo-A3-à-réservoirs-rechargeables-small-1.png',
                'zoomImage1' => 'Epson-EcoTank-L18050-Imprimante-Photo-A3-à-réservoirs-rechargeables-zoom-1.jpg',
                'smallImage2' => 'Epson-EcoTank-L18050-Imprimante-Photo-A3-à-réservoirs-rechargeables-small-2.png',
                'zoomImage2' => 'Epson-EcoTank-L18050-Imprimante-Photo-A3-à-réservoirs-rechargeables-zoom-2.jpg',
                'smallImage3' => 'Epson-EcoTank-L18050-Imprimante-Photo-A3-à-réservoirs-rechargeables-small-3.png',
                'zoomImage3' => 'Epson-EcoTank-L18050-Imprimante-Photo-A3-à-réservoirs-rechargeables-zoom-3.jpg',
                'smallImage4' => 'Epson-EcoTank-L18050-Imprimante-Photo-A3-à-réservoirs-rechargeables-small-4.png',
                'zoomImage4' => 'Epson-EcoTank-L18050-Imprimante-Photo-A3-à-réservoirs-rechargeables-zoom-4.jpg',
                'smallImage5' => 'Epson-EcoTank-L18050-Imprimante-Photo-A3-à-réservoirs-rechargeables-small-5.png',
                'zoomImage5' => 'Epson-EcoTank-L18050-Imprimante-Photo-A3-à-réservoirs-rechargeables-zoom-5.jpg'
            ],
            [
                'id' => 23,
                'smallImage1' => 'Serveur-HPE-ProLiant-DL20-Gen10-Plus-E-2314-small-1.png',
                'zoomImage1' => 'Serveur-HPE-ProLiant-DL20-Gen10-Plus-E-2314-zoom-1.jpg',
                'smallImage2' => 'Serveur-HPE-ProLiant-DL20-Gen10-Plus-E-2314-small-2.png',
                'zoomImage2' => 'Serveur-HPE-ProLiant-DL20-Gen10-Plus-E-2314-zoom-2.jpg',
                'smallImage3' => 'Serveur-HPE-ProLiant-DL20-Gen10-Plus-E-2314-small-3.png',
                'zoomImage3' => 'Serveur-HPE-ProLiant-DL20-Gen10-Plus-E-2314-zoom-3.jpg',
                'smallImage4' => 'Serveur-HPE-ProLiant-DL20-Gen10-Plus-E-2314-small-4.png',
                'zoomImage4' => 'Serveur-HPE-ProLiant-DL20-Gen10-Plus-E-2314-zoom-4.jpg',
                'smallImage5' => 'Serveur-HPE-ProLiant-DL20-Gen10-Plus-E-2314-small-5.png',
                'zoomImage5' => 'Serveur-HPE-ProLiant-DL20-Gen10-Plus-E-2314-zoom-5.jpg'
            ],
            [
                'id' => 24,
                'smallImage1' => 'Ordinateur-Portable-Lenovo-V15-G3-IAP-small-1.png',
                'zoomImage1' => 'Ordinateur-Portable-Lenovo-V15-G3-IAP-zoom-1.jpg',
                'smallImage2' => 'Ordinateur-Portable-Lenovo-V15-G3-IAP-small-2.png',
                'zoomImage2' => 'Ordinateur-Portable-Lenovo-V15-G3-IAP-zoom-2.jpg',
                'smallImage3' => 'Ordinateur-Portable-Lenovo-V15-G3-IAP-small-3.png',
                'zoomImage3' => 'Ordinateur-Portable-Lenovo-V15-G3-IAP-zoom-3.jpg',
                'smallImage4' => 'Ordinateur-Portable-Lenovo-V15-G3-IAP-small-4.png',
                'zoomImage4' => 'Ordinateur-Portable-Lenovo-V15-G3-IAP-zoom-4.jpg',
                'smallImage5' => 'Ordinateur-Portable-Lenovo-V15-G3-IAP-small-5.png',
                'zoomImage5' => 'Ordinateur-Portable-Lenovo-V15-G3-IAP-zoom-5.jpg'
            ],
            [
                'id' => 25,
                'smallImage1' => 'Écran-Plat-32"-Samsung-Smart-Monitor-S5-small-1.png',
                'zoomImage1' => 'Écran-Plat-32"-Samsung-Smart-Monitor-S5-zoom-1.jpg',
                'smallImage2' => 'Écran-Plat-32"-Samsung-Smart-Monitor-S5-small-2.png',
                'zoomImage2' => 'Écran-Plat-32"-Samsung-Smart-Monitor-S5-zoom-2.jpg',
                'smallImage3' => 'Écran-Plat-32"-Samsung-Smart-Monitor-S5-small-3.png',
                'zoomImage3' => 'Écran-Plat-32"-Samsung-Smart-Monitor-S5-zoom-3.jpg',
                'smallImage4' => 'Écran-Plat-32"-Samsung-Smart-Monitor-S5-small-4.png',
                'zoomImage4' => 'Écran-Plat-32"-Samsung-Smart-Monitor-S5-zoom-4.jpg',
                'smallImage5' => 'Écran-Plat-32"-Samsung-Smart-Monitor-S5-small-5.png',
                'zoomImage5' => 'Écran-Plat-32"-Samsung-Smart-Monitor-S5-zoom-5.jpg'
            ],
            [
                'id' => 26,
                'smallImage1' => 'Onduleur-Line-interactive-Eaton-5E-1200-USB-660W-1200VA-6-prises-C13-small-1.png',
                'zoomImage1' => 'Onduleur-Line-interactive-Eaton-5E-1200-USB-660W-1200VA-6-prises-C13-zoom-1.jpg',
                'smallImage2' => 'Onduleur-Line-interactive-Eaton-5E-1200-USB-660W-1200VA-6-prises-C13-small-2.png',
                'zoomImage2' => 'Onduleur-Line-interactive-Eaton-5E-1200-USB-660W-1200VA-6-prises-C13-zoom-2.jpg',
                'smallImage3' => 'Onduleur-Line-interactive-Eaton-5E-1200-USB-660W-1200VA-6-prises-C13-small-3.png',
                'zoomImage3' => 'Onduleur-Line-interactive-Eaton-5E-1200-USB-660W-1200VA-6-prises-C13-zoom-3.jpg',
                'smallImage4' => 'Onduleur-Line-interactive-Eaton-5E-1200-USB-660W-1200VA-6-prises-C13-small-4.png',
                'zoomImage4' => 'Onduleur-Line-interactive-Eaton-5E-1200-USB-660W-1200VA-6-prises-C13-zoom-4.jpg',
                'smallImage5' => 'Onduleur-Line-interactive-Eaton-5E-1200-USB-660W-1200VA-6-prises-C13-small-5.png',
                'zoomImage5' => 'Onduleur-Line-interactive-Eaton-5E-1200-USB-660W-1200VA-6-prises-C13-zoom-5.jpg'
            ],
            [
                'id' => 27,
                'smallImage1' => 'Station-de-travail-HP-Z6-Tower-G5-small-1.png',
                'zoomImage1' => 'Station-de-travail-HP-Z6-Tower-G5-zoom-1.jpg',
                'smallImage2' => 'Station-de-travail-HP-Z6-Tower-G5-small-2.png',
                'zoomImage2' => 'Station-de-travail-HP-Z6-Tower-G5-zoom-2.jpg',
                'smallImage3' => 'Station-de-travail-HP-Z6-Tower-G5-small-3.png',
                'zoomImage3' => 'Station-de-travail-HP-Z6-Tower-G5-zoom-3.jpg',
                'smallImage4' => 'Station-de-travail-HP-Z6-Tower-G5-small-4.png',
                'zoomImage4' => 'Station-de-travail-HP-Z6-Tower-G5-zoom-4.jpg',
                'smallImage5' => 'Station-de-travail-HP-Z6-Tower-G5-small-5.png',
                'zoomImage5' => 'Station-de-travail-HP-Z6-Tower-G5-zoom-5.jpg'
            ],
            [
                'id' => 28,
                'smallImage1' => 'Modem-Routeur-4G-LTE-WiFi-TP-Link-Archer-MR200-AC750-Mbps-bi-bande-small-1.png',
                'zoomImage1' => 'Modem-Routeur-4G-LTE-WiFi-TP-Link-Archer-MR200-AC750-Mbps-bi-bande-zoom-1.jpg',
                'smallImage2' => 'Modem-Routeur-4G-LTE-WiFi-TP-Link-Archer-MR200-AC750-Mbps-bi-bande-small-2.png',
                'zoomImage2' => 'Modem-Routeur-4G-LTE-WiFi-TP-Link-Archer-MR200-AC750-Mbps-bi-bande-zoom-2.jpg',
                'smallImage3' => 'Modem-Routeur-4G-LTE-WiFi-TP-Link-Archer-MR200-AC750-Mbps-bi-bande-small-3.png',
                'zoomImage3' => 'Modem-Routeur-4G-LTE-WiFi-TP-Link-Archer-MR200-AC750-Mbps-bi-bande-zoom-3.jpg',
                'smallImage4' => 'Modem-Routeur-4G-LTE-WiFi-TP-Link-Archer-MR200-AC750-Mbps-bi-bande-small-4.png',
                'zoomImage4' => 'Modem-Routeur-4G-LTE-WiFi-TP-Link-Archer-MR200-AC750-Mbps-bi-bande-zoom-4.jpg',
                'smallImage5' => 'Modem-Routeur-4G-LTE-WiFi-TP-Link-Archer-MR200-AC750-Mbps-bi-bande-small-5.png',
                'zoomImage5' => 'Modem-Routeur-4G-LTE-WiFi-TP-Link-Archer-MR200-AC750-Mbps-bi-bande-zoom-5.jpg'
            ],
            [
                'id' => 29,
                'smallImage1' => 'Logitech-BRIO-ULTRA-HD-PRO-WEBCAM-small-1.png',
                'zoomImage1' => 'Logitech-BRIO-ULTRA-HD-PRO-WEBCAM-zoom-1.jpg',
                'smallImage2' => 'Logitech-BRIO-ULTRA-HD-PRO-WEBCAM-small-2.png',
                'zoomImage2' => 'Logitech-BRIO-ULTRA-HD-PRO-WEBCAM-zoom-2.jpg',
                'smallImage3' => 'Logitech-BRIO-ULTRA-HD-PRO-WEBCAM-small-3.png',
                'zoomImage3' => 'Logitech-BRIO-ULTRA-HD-PRO-WEBCAM-zoom-3.jpg',
                'smallImage4' => 'Logitech-BRIO-ULTRA-HD-PRO-WEBCAM-small-4.png',
                'zoomImage4' => 'Logitech-BRIO-ULTRA-HD-PRO-WEBCAM-zoom-4.jpg',
                'smallImage5' => 'Logitech-BRIO-ULTRA-HD-PRO-WEBCAM-small-5.png',
                'zoomImage5' => 'Logitech-BRIO-ULTRA-HD-PRO-WEBCAM-zoom-5.jpg'
            ],
            [
                'id' => 30,
                'smallImage1' => 'BOITE-DE-10-DVD-plus-R-VERBATIM-DOUBLE-LAYER-8.5GB-8X-MATT-SILVER-small-1.png',
                'zoomImage1' => 'BOITE-DE-10-DVD-plus-R-VERBATIM-DOUBLE-LAYER-8.5GB-8X-MATT-SILVER-zoom-1.jpg',
                'smallImage2' => 'BOITE-DE-10-DVD-plus-R-VERBATIM-DOUBLE-LAYER-8.5GB-8X-MATT-SILVER-small-2.png',
                'zoomImage2' => 'BOITE-DE-10-DVD-plus-R-VERBATIM-DOUBLE-LAYER-8.5GB-8X-MATT-SILVER-zoom-2.jpg',
                'smallImage3' => 'BOITE-DE-10-DVD-plus-R-VERBATIM-DOUBLE-LAYER-8.5GB-8X-MATT-SILVER-small-3.png',
                'zoomImage3' => 'BOITE-DE-10-DVD-plus-R-VERBATIM-DOUBLE-LAYER-8.5GB-8X-MATT-SILVER-zoom-3.jpg',
                'smallImage4' => 'BOITE-DE-10-DVD-plus-R-VERBATIM-DOUBLE-LAYER-8.5GB-8X-MATT-SILVER-small-4.png',
                'zoomImage4' => 'BOITE-DE-10-DVD-plus-R-VERBATIM-DOUBLE-LAYER-8.5GB-8X-MATT-SILVER-zoom-4.jpg',
                'smallImage5' => 'BOITE-DE-10-DVD-plus-R-VERBATIM-DOUBLE-LAYER-8.5GB-8X-MATT-SILVER-small-5.png',
                'zoomImage5' => 'BOITE-DE-10-DVD-plus-R-VERBATIM-DOUBLE-LAYER-8.5GB-8X-MATT-SILVER-zoom-5.jpg'
            ],
            [
                'id' => 31,
                'smallImage1' => 'Ramette-de-papier-Navigator-Universal-NAVA480-Papier-A4-80-g-par-m²-5-flux-500-feuilles-small-1.png',
                'zoomImage1' => 'Ramette-de-papier-Navigator-Universal-NAVA480-Papier-A4-80-g-par-m²-5-flux-500-feuilles-zoom-1.jpg',
                'smallImage2' => 'Ramette-de-papier-Navigator-Universal-NAVA480-Papier-A4-80-g-par-m²-5-flux-500-feuilles-small-2.png',
                'zoomImage2' => 'Ramette-de-papier-Navigator-Universal-NAVA480-Papier-A4-80-g-par-m²-5-flux-500-feuilles-zoom-2.jpg',
                'smallImage3' => 'Ramette-de-papier-Navigator-Universal-NAVA480-Papier-A4-80-g-par-m²-5-flux-500-feuilles-small-3.png',
                'zoomImage3' => 'Ramette-de-papier-Navigator-Universal-NAVA480-Papier-A4-80-g-par-m²-5-flux-500-feuilles-zoom-3.jpg',
                'smallImage4' => 'Ramette-de-papier-Navigator-Universal-NAVA480-Papier-A4-80-g-par-m²-5-flux-500-feuilles-small-4.png',
                'zoomImage4' => 'Ramette-de-papier-Navigator-Universal-NAVA480-Papier-A4-80-g-par-m²-5-flux-500-feuilles-zoom-4.jpg',
                'smallImage5' => 'Ramette-de-papier-Navigator-Universal-NAVA480-Papier-A4-80-g-par-m²-5-flux-500-feuilles-small-5.png',
                'zoomImage5' => 'Ramette-de-papier-Navigator-Universal-NAVA480-Papier-A4-80-g-par-m²-5-flux-500-feuilles-zoom-5.jpg'
            ],
            [
                'id' => 32,
                'smallImage1' => 'HUB-USB-C-UGREEN-4-PORTS-USB-3.0-ADAPTATEUR-USB-TYPE-C-small-1.png',
                'zoomImage1' => 'HUB-USB-C-UGREEN-4-PORTS-USB-3.0-ADAPTATEUR-USB-TYPE-C-zoom-1.jpg',
                'smallImage2' => 'HUB-USB-C-UGREEN-4-PORTS-USB-3.0-ADAPTATEUR-USB-TYPE-C-small-2.png',
                'zoomImage2' => 'HUB-USB-C-UGREEN-4-PORTS-USB-3.0-ADAPTATEUR-USB-TYPE-C-zoom-2.jpg',
                'smallImage3' => 'HUB-USB-C-UGREEN-4-PORTS-USB-3.0-ADAPTATEUR-USB-TYPE-C-small-3.png',
                'zoomImage3' => 'HUB-USB-C-UGREEN-4-PORTS-USB-3.0-ADAPTATEUR-USB-TYPE-C-zoom-3.jpg',
                'smallImage4' => 'HUB-USB-C-UGREEN-4-PORTS-USB-3.0-ADAPTATEUR-USB-TYPE-C-small-4.png',
                'zoomImage4' => 'HUB-USB-C-UGREEN-4-PORTS-USB-3.0-ADAPTATEUR-USB-TYPE-C-zoom-4.jpg',
                'smallImage5' => 'HUB-USB-C-UGREEN-4-PORTS-USB-3.0-ADAPTATEUR-USB-TYPE-C-small-5.png',
                'zoomImage5' => 'HUB-USB-C-UGREEN-4-PORTS-USB-3.0-ADAPTATEUR-USB-TYPE-C-zoom-5.jpg'
            ]
        ]);
    }
}
