<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Produit;
use Illuminate\Support\Str;

class ProduitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Produit::insert([
            [
                'titre' => 'Ordinateur HP 24-cr0000nk AIO PC',
                'slug' => Str::slug('Ordinateur HP 24-cr0000nk AIO PC'),
                'status' => 'Affaire du jour',
                'ParametreStatus' => '-958.00 DH',
                'ImagePrincipale' => 'ordinateur-hp-24-cr0000nk-aio-pc.jpg',
                'ImageDashboard' => 'ordinateur-hp-24-cr0000nk-aio-pc-228px-250px.jpg',
                'AncienPrix' => '17 388,00 DH',
                'NouveauPrix' => '16 430,00 DH',
                'DescriptionModal' => 'Intel® Core™ i7-1355U (jusqu’à 5,0 GHz avec la technologie Intel® Turbo Boost, 12 Mo de mémoire cache L3, 10 cœurs, 12 threads) / RAM: 16 Go de mémoire RAM DDR4-3200 MHz (2 x 8 Go) / Disque dur: SSD PCIe® NVMe™ M.2 512 Go / Écran: Tactile Full HD de 60,5 cm (23,8 pouces) (1920 x 1080), IPS, micro-bords sur trois côtés, antireflet, 300 nits, 99 % sRGB / Carte graphique: Intel® Iris® X / Windows 11 Famille unilingue en mode S',
                'DescriptionPlus' => 'L\'ordinateur tout-en-un HP 24-cr0000nk AIO PC (845P4EA) est une solution complète pour les besoins informatiques domestiques et professionnels. Doté d\'un puissant processeur Intel® Core™ i7-1355U avec jusqu\'à 5,0 GHz de puissance grâce à la technologie Intel® Turbo Boost, cet ordinateur offre des performances rapides et fluides pour une variété de tâches. Avec 16 Go de mémoire RAM DDR4-3200 MHz, il peut facilement gérer plusieurs programmes et applications simultanément.',
                'IdDetails' => 1,
                'IdTags' => 1,
                'IdImages' => 1,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Volant de course Logitech G29 Force pour Xbox Series X|S /Xbox One/PC',
                'slug' => Str::slug('Volant de course Logitech G29 Force pour Xbox Series X|S XboxOne PC'),
                'status' => 'Affaire du jour',
                'ParametreStatus' => '-1186,00 DH',
                'ImagePrincipale' => 'volant-de-course-Logitech-G29-Force-pour-Xbox-Series -X|S-XboxOne-PC.jpg',
                'ImageDashboard' => 'volant-de-course-Logitech-G29-Force-pour-Xbox-Series -X|S-XboxOne-PC-228px-250px.jpg',
                'AncienPrix' => '4 375,00 DH',
                'NouveauPrix' => '3 189,00 DH',
                'DescriptionModal' => 'Plongez dans l\'expérience ultime de course avec le volant de course Logitech G29 pour Xbox Series X|S, Xbox One et PC. Doté d\'un retour de force à double moteur, de palettes en acier inoxydable et d\'un volant en cuir cousu à la main, ce volant offre une immersion totale. Les pédales ajustables vous permettent d\'accélérer, de freiner et de changer de vitesse avec une sensation de conduite réaliste. Avec une rotation de 900 degrés et des capteurs de direction précis, chaque virage et chaque mouvement seront ressentis avec une incroyable précision.',
                'DescriptionPlus' => 'Plongez dans l\'expérience ultime de course avec le volant de course Logitech G29 pour Xbox Series X|S, Xbox One et PC. Doté d\'un retour de force à double moteur, de palettes en acier inoxydable et d\'un volant en cuir cousu à la main, ce volant offre une immersion totale. Les pédales ajustables vous permettent d\'accélérer, de freiner et de changer de vitesse avec une sensation de conduite réaliste. Avec une rotation de 900 degrés et des capteurs de direction précis, chaque virage et chaque mouvement seront ressentis avec une incroyable précision.',
                'IdDetails' => 2,
                'IdTags' => 2,
                'IdImages' => 2,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Epson EB-FH52 Vidéoprojecteur Full HD (1920 x 1080) (V11H978040)',
                'slug' => Str::slug('Epson EB-FH52 Vidéoprojecteur Full HD 1920x1080 V11H978040'),
                'status' => 'Affaire du jour',
                'ParametreStatus' => '-674,00 DH',
                'ImagePrincipale' => 'Epson-EB-FH52-Vidéoprojecteur-Full-HD-1920x1080-V11H978040.jpg',
                'ImageDashboard' => 'Epson-EB-FH52-Vidéoprojecteur-Full-HD-1920x1080-V11H978040-228px-250px.jpg',
                'AncienPrix' => '12 264,00 DH',
                'NouveauPrix' => '11 590,00 DH',
                'DescriptionModal' => 'Résolution: Full HD (1920 x 1080), 16:9 / Luminosité: 4.000 lumen- 2.400 lumen (économie) / Rapport de contraste: 16.000 : 1 / UHE, 230 W, 5.500 h Longévité, 12.000 h Longévité (en mode économique) / Rapport de projection: 1,32 - 2,14:1 / Taille de l\'image: 30 pouces - 300 pouces / Système de projection: Technologie 3LCD / Haut-parleur: 16 W / Poids: 3,1 kg / Connexions: USB 2.0 type A, USB 2.0 type B, Réseau local sans fil IEEE 802.11b/g/n (WiFi 4), Entrée VGA, Entrée HDMI (2x), Entrée composite, Entrée RCA, Miracast ',
                'DescriptionPlus' => 'Profitez d’années de réunions ininterrompues et de présentations claires, en grand format évolutif Full HD 1080p, grâce à ce projecteur qui s’installe presque partout. Au bureau ou dans tout autre environnement professionnel, l’élégant modèle EB-FH52 est parfait pour projeter des présentations nettes ou visualiser du contenu vidéo. Profitez d’une image Full HD et d’une luminosité élevée pour une visibilité exceptionnelle du contenu. Une technologie fiable avec intervention et maintenance réduites favorise la tranquillité d’esprit.',
                'IdDetails' => 3,
                'IdTags' => 3,
                'IdImages' => 3,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Module WiFi Epson ELPAP11 pour projecteur - Dual Fonction 5GHZ (V12H005A01)',
                'slug' => Str::slug('Module WiFi Epson ELPAP11 pour projecteur - Dual Fonction 5GHZ V12H005A01'),
                'status' => 'Affaire du jour',
                'ParametreStatus' => '-92,00 DH',
                'ImagePrincipale' => 'Module-WiFi-Epson-ELPAP11-pour-projecteur-Dual-Fonction-5GHZ-V12H005A01.jpg',
                'ImageDashboard' => 'Module-WiFi-Epson-ELPAP11-pour-projecteur-Dual-Fonction-5GHZ-V12H005A01-228px-250px.jpg',
                'AncienPrix' => '1 392,00 DH',
                'NouveauPrix' => '1 300,00 DH',
                'DescriptionModal' => 'Compatible avec: EB-1485Fi,EB-X49,EB-W49,EB-982W,EB-725Wi,EB-800F,EB-805F,EB-750F,EB-755F,EB-X51,EB-X06,EB-W06, EB-W51,EB-FH06,EB-L255F,EB-L250F,EB-L200W,EB-FH52,EB-992F,EB-L520U,EB-L720U,EB-L530U,EB-L630SU,EB-L630U,EB-L635SU, EB-L730U,EB-L735U,EB-PU2010B,EB-PU2010W,EB-PU1006W,EB-PU1007W,EB-PU1007B,EB-PU1008B,EB-PU1008W,EB-PU2220B,EB-PU2120W, EB-PU2116W,EB-PU2216B,EB-PU2113W,EB-PU2213B,Epson EB-L210W,EB-L260F,CO-W01,CO-FH01,EB-L570U,EB-L770U,EB-L775U,EB-775F, Epson EB-L265F,EB-L210SW,EB-L210SF,EB-770F,EB-760W,EB-770Fi,EB-810E,EB-815E,TW740,EH-TW740,EB-1480Fi,EB-720,EB-725W, EB-735F,EB-735Fi,EB-L200F,EB-L200SW,EB-L200SX',
                'DescriptionPlus' => 'Le module WiFi Epson ELPAP11 pour projecteur offre une connexion sans fil de haute qualité et une double fonctionnalité 5GHZ, permettant une projection de contenu en haute définition et en temps réel. C\'est une solution pratique pour les présentateurs et les professionnels qui souhaitent se déplacer librement lors de leurs présentations. Ce module est compatible avec plusieurs modèles de projecteurs Epson, y compris le modèle EB-1940W, EB-1950, EB-1960, EB-1970W, EB-1980WU, EB-4550, EB-4650 et bien d\'autres. Achetez dès maintenant chez nous pour bénéficier d\'une livraison rapide et d\'un excellent service clientèle.',
                'IdDetails' => 4,
                'IdTags' => 4,
                'IdImages' => 4,
                'IdCategorie' => 2
            ],
            [
                'titre' => 'Imprimante Multifonction Laser Couleur Canon I-SENSYS MF657Cdw',
                'slug' => Str::slug('Imprimante Multifonction Laser Couleur Canon I-SENSYS MF657Cdw'),
                'status' => 'Affaire du jour',
                'ParametreStatus' => '-500 DHS',
                'ImagePrincipale' => 'Imprimante-Multifonction-Laser-Couleur-Canon-I-SENSYS-MF657Cdw.jpg',
                'ImageDashboard' => 'Imprimante-Multifonction-Laser-Couleur-Canon-I-SENSYS-MF657Cdw-228px-250px.jpg',
                'AncienPrix' => '6 895,00 DHS',
                'NouveauPrix' => '6 395,00 DHS',
                'DescriptionModal' => 'Impression, numérisation, copie et télécopie / Vitesse d\'impression couleur: Recto : jusqu\'à 21 ppm (A4), Jusqu\'à 38 ppm (A5 - Paysage), Recto verso : jusqu\'à 12,7 ipm (A4) / Qualité d\'impression couleur: Jusqu\'à 1200 × 1200 ppp / Volume de pages mensuel recommandé: 250 à 2500 pages par mois / Impression recto/verso: Automatique / Fonctionne avec: 4 Cartouches ( Noir, Cyan, Magenta, Jaune) / Connectivité: USB 2.0 Haute Vitesse, 10BASE-T/100BASE-TX/1000Base-T, 802.11b/g/n sans fil, connexion directe sans fil ',
                'DescriptionPlus' => 'L\'imprimante multifonction laser couleur Canon i-SENSYS MF657Cdw (5158C001AA) est une solution polyvalente pour les besoins d\'impression, de numérisation, de copie et de télécopie dans les environnements professionnels ou à domicile. Dotée d\'une vitesse d\'impression couleur allant jusqu\'à 21 pages par minute pour le format A4 et jusqu\'à 38 pages par minute pour le format A5 en mode paysage, cette imprimante offre une productivité accrue. Avec une qualité d\'impression couleur allant jusqu\'à 1200 × 1200 ppp, elle garantit des documents nets et professionnels à chaque impression. Avec un volume de pages mensuel recommandé allant de 250 à 2500 pages par mois, cette imprimante convient aussi bien aux petits bureaux qu\'aux groupes de travail plus importants. La fonction d\'impression recto verso automatique permet d\'économiser du temps et du papier, tandis que les quatre cartouches d\'encre (noir, cyan, magenta, jaune) offrent des performances fiables et des couleurs éclatantes. En termes de connectivité, l\'i-SENSYS MF657Cdw est équipée de ports USB 2.0 Haute Vitesse, 10BASE-T/100BASE-TX/1000Base-T, ainsi que d\'une connectivité sans fil 802.11b/g/n et d\'une option de connexion directe sans fil. Cette gamme de connexions permet aux utilisateurs d\'imprimer facilement à partir d\'une variété de périphériques, y compris des ordinateurs, des smartphones et des tablettes, offrant ainsi une flexibilité maximale dans les environnements de travail modernes.',
                'IdDetails' => 5,
                'IdTags' => 5,
                'IdImages' => 5,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Disque dur externe LaCie d2 Professional 10 To',
                'slug' => Str::slug('Disque dur externe LaCie d2 Professional 10 To'),
                'status' => 'Nouveau Arrivage',
                'ParametreStatus' => 'Nouveau',
                'ImagePrincipale' => 'Disque-dur-externe-LaCie-d2-Professional-10-To.jpg',
                'ImageDashboard' => 'Disque-dur-externe-LaCie-d2-Professional-10-To-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '5 095,00 DH',
                'DescriptionModal' => 'Décuplez votre capacité de stockage avec le Disque dur externe LaCie d2 Professional 10 To. Ce bijou de technologie offre une capacité généreuse de 10 To pour stocker vos données les plus précieuses en toute sécurité. Doté d\'une connectivité USB-C et Thunderbolt 3, il assure des transferts ultra-rapides. Son design élégant et robuste est parfait pour les professionnels exigeants. Ne vous limitez plus et libérez votre créativité sans contrainte grâce à ce disque dur externe haut de gamme.',
                'DescriptionPlus' => 'Augmentez votre espace de stockage avec le Disque dur externe LaCie d2 Professional 10 To. Ce dispositif offre une capacité massive de 10 To pour sécuriser vos données essentielles. Grâce à sa connectivité USB-C et Thunderbolt 3, les transferts sont d\'une rapidité exceptionnelle. Son design à la fois élégant et robuste convient parfaitement aux professionnels les plus exigeants. Libérez votre créativité sans limites avec ce disque dur externe haut de gamme.',
                'IdDetails' => 6,
                'IdTags' => 6,
                'IdImages' => 6,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Disque Dur portable ADATA HV620S 2.5” 4TB USB 3.1 Noir',
                'slug' => Str::slug('Disque Dur portable ADATA HV620S 2.5” 4TB USB 3.1 Noir'),
                'status' => 'Nouveau Arrivage',
                'ParametreStatus' => 'Nouveau',
                'ImagePrincipale' => 'Disque-Dur-portable-ADATA-HV620S-2.5”-4TB-USB-3.1-Noir.jpg',
                'ImageDashboard' => 'Disque-Dur-portable-ADATA-HV620S-2.5”-4TB-USB-3.1-Noir-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '1 720,00 DH',
                'DescriptionModal' => 'Disque dur externe portable - USB 3.1, rétrocompatible avec USB 2.0 - de 1 à 4 To  - 1TB/2TB : 115 x 78 x 11.5mm, 4TB : 115 x 78 x 21mm - 1TB/2TB : 152g, 4TB : 230g - Windows 7 / 8 / 8.1 / 10 - Mac OS X 10.6 ou version ultérieure - Linux kernel 2.6 ou version ultérieure - 5°C (41°F) à 50°C (121°F)',
                'DescriptionPlus' => 'Disque dur externe portable ADATA HV620S 2,5" avec connectivité USB 3.1, compatible avec USB 2.0. Disponible en capacités de 1 à 4 To, ce disque offre une solution de stockage compacte et légère. Dimensions de 115 x 78 x 11.5mm pour les versions 1TB/2TB et 115 x 78 x 21mm pour la version 4TB, pesant respectivement 152g et 230g. Compatible avec Windows 7/8/8.1/10, Mac OS X 10.6 ou ultérieur, et Linux kernel 2.6 ou ultérieur. Plage de température de fonctionnement de 5°C (41°F) à 50°C (121°F).',
                'IdDetails' => 7,
                'IdTags' => 7,
                'IdImages' => 7,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'TP-Link RE505X prolongateur réseau Émetteur et récepteur réseau Blanc 10, 100, 1000 Mbit/s',
                'slug' => Str::slug('TP-Link RE505X prolongateur réseau Émetteur et récepteur réseau Blanc 10, 100, 1000 Mbit/s'),
                'status' => 'Nouveau Arrivage',
                'ParametreStatus' => 'Nouveau',
                'ImagePrincipale' => 'TP-Link-RE505X-prolongateur-réseau-Émetteur-et-récepteur-réseau-Blanc.jpg',
                'ImageDashboard' => 'TP-Link-RE505X-prolongateur-réseau-Émetteur-et-récepteur-réseau-Blanc-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '746,00 DH',
                'DescriptionModal' => '- Émetteur et récepteur réseau 1200 Mbit/s - 10/100/1000Base-T(X) - Wifi Bi-bande (2,4 GHz / 5 GHz) 1200 Mbit/s 802.11a, 802.11b, 802.11g, Wi-Fi 4 (802.11n), Wi-Fi 5 (802.11ac), Wi-Fi 6 (802.11ax) - Blanc',
                'DescriptionPlus' => 'TP-Link RE505X. Type: Émetteur et récepteur réseau, Taux de transfert de données: 1200 Mbit/s, LAN Ethernet : taux de transfert des données: 10,100,1000 Mbit/s. Type d\'antenne: Externe, Puissance de transmission (CE): 2.4 GHz ≤20dBm, 5 GHz ≤30dBm. Technologie de cablâge: 10/100/1000Base-T(X), Standards réseau: IEEE 802.11a, IEEE 802.11ac, IEEE 802.11ax, IEEE 802.11b, IEEE 802.11g, IEEE 802.11n, Standards wifi: 802.11a, 802.11b, 802.11g, Wi-Fi 4 (802.11n), Wi-Fi 5 (802.11ac), Wi-Fi 6 (802.11ax). Couleur du produit: Blanc, Voyants: Énergie, WAN, WLAN, Quantité: 1 pièce(s). Tension d\'entrée AC: 100 - 240 V, Fréquence d\'entrée AC: 50/60 Hz, Consommation (max): 10 W',
                'IdDetails' => 8,
                'IdTags' => 8,
                'IdImages' => 8,
                'IdCategorie' => 2
            ],
            [
                'titre' => 'Ensemble clavier et souris sans fil ultra-fin Logitech MK470 AZERTY',
                'slug' => Str::slug('Ensemble clavier et souris sans fil ultra-fin Logitech MK470 AZERTY'),
                'status' => 'Nouveau Arrivage',
                'ParametreStatus' => 'Nouveau',
                'ImagePrincipale' => 'Ensemble-clavier-et-souris-sans-fil-ultra-fin-Logitech-MK470-AZERTY.jpg',
                'ImageDashboard' => 'Ensemble-clavier-et-souris-sans-fil-ultra-fin-Logitech-MK470-AZERTY-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '706,00 DH',
                'DescriptionModal' => 'Équipez-vous avec l\'ensemble clavier et souris sans fil ultra-fin Logitech MK470 AZERTY. La souris compacte offre une résolution de capteur de 1 000 ppp, 3 boutons et une roulette de défilement mécanique. Le clavier, d\'une portée sans fil de 10 mètres, fonctionne avec un nano-récepteur Logitech. Profitez d\'une liberté de mouvement et d\'une productivité accrue grâce à ce duo élégant et léger.',
                'DescriptionPlus' => 'Transformez n\'importe quel espace en un bureau minimaliste, moderne et silencieux avec l\'ensemble sans fil MK470, composé d’un clavier et d’une souris au design ultra-fin, compact et avant-gardiste. Le combo parfait pour travailler efficacement, même dans les endroits les plus exigus.',
                'IdDetails' => 9,
                'IdTags' => 9,
                'IdImages' => 9,
                'IdCategorie' => 3
            ],
            [
                'titre' => 'Écran 24" Samsung Essential Monitor S3 S31C',
                'slug' => Str::slug('Écran 24" Samsung Essential Monitor S3 S31C'),
                'status' => 'Nouveau Arrivage',
                'ParametreStatus' => 'Nouveau',
                'ImagePrincipale' => 'Écran-24-Samsung-Essential-Monitor-S3-S31C.jpg',
                'ImageDashboard' => 'Écran-24-Samsung-Essential-Monitor-S3-S31C-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '1 820,00 DH',
                'DescriptionModal' => 'Taille de l\'écran: 24" - Format 16:9 - Courbure de l\'écran: Plat - Type de Dalle: IPS - Résolution: Full HD 1920 x 1080 - Temps de réponse: 5 ms (gris à gris) - Taux de rafraîchissement: 75 Hz - Connecteurs d\'entrée: VGA, HDMI - Réglages de la position de l\'écran: Inclinaison -2.0°(-1.0°/+2.0°)~20.0°(±2.0°)',
                'DescriptionPlus' => 'Découvrez le nouvel écran 24" Samsung Essential Monitor S3 S31C, conçu pour vous offrir une expérience visuelle exceptionnelle. Grâce à sa dalle IPS, vous pourrez profiter d\'images précises et éclatantes sous tous les angles, sans altération des couleurs. Plongez dans vos jeux préférés avec la technologie AMD FreeSync et un taux de rafraîchissement de 75 Hz pour une expérience de jeu fluide et sans déchirure d\'image. De plus, son design sans bordures vous permet de vous concentrer sur ce qui se passe à l\'écran, tout en offrant une esthétique moderne et épurée à votre espace de travail ou votre bureau à domicile. Le confort de vos yeux est également assuré avec le mode Eye Saver et la technologie Flicker Free, qui réduisent la fatigue oculaire en minimisant la lumière bleue et en supprimant les scintillements. L\'écran Samsung S31C est également doté d\'une connectivité HDMI et D-sub, pour une plus grande polyvalence et une facilité d\'utilisation accrue. Avec cet écran, vous pourrez non seulement profiter de vos jeux et films, mais également travailler confortablement et efficacement. Ne cherchez plus, l\'écran Samsung Essential Monitor S3 S31C est le choix idéal pour toutes vos activités numériques.',
                'IdDetails' => 10,
                'IdTags' => 10,
                'IdImages' => 10,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Ordinateur de bureau Lenovo ThinkCentre neo 50t',
                'slug' => Str::slug('Ordinateur de bureau Lenovo ThinkCentre neo 50t'),
                'status' => 'Nouveau Arrivage',
                'ParametreStatus' => 'Nouveau',
                'ImagePrincipale' => 'Ordinateur-de-bureau-Lenovo-ThinkCentre-neo-50t.jpg',
                'ImageDashboard' => 'Ordinateur-de-bureau-Lenovo-ThinkCentre-neo-50t-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '4 560,00 DH',
                'DescriptionModal' => 'Intel® Core™ i3-12100, 4C (4P + 0E) / 8T, P-core 3.3 / 4.3GHz, 12MB - RAM: 1x 8GB UDIMM DDR4-3200 - Disque dur: 512GB SSD M.2 2280 PCIe® 4.0x4 NVMe® Opal 2.0 - Carte graphique: Integrated Intel® UHD Graphics 730 - FreeDOS (Sans Windows) - Unité centrale sans écran',
                'DescriptionPlus' => 'L\'ordinateur de bureau Lenovo ThinkCentre neo 50t (11SE00QFFM) offre des performances fiables et une efficacité accrue pour répondre aux besoins professionnels et personnels. Doté d\'un processeur Intel® Core™ i3-12100 avec 4 cœurs et 8 threads, cadencé à 3,3 GHz et pouvant atteindre 4,3 GHz en mode Turbo, ainsi que d\'une mémoire cache de 12 Mo, il offre une puissance de traitement impressionnante pour les tâches multitâches et les applications exigeantes. Avec 8 Go de RAM DDR4-3200, il garantit une exécution fluide des programmes et une réactivité accrue. De plus, son SSD M.2 2280 PCIe® 4.0x4 NVMe® Opal 2.0 de 512 Go offre un stockage rapide et fiable pour vos fichiers et applications essentiels. La carte graphique intégrée Intel® UHD Graphics 730 offre des performances graphiques suffisantes pour les tâches quotidiennes et les applications professionnelles, tandis que le système d\'exploitation FreeDOS offre une flexibilité pour installer le système d\'exploitation de votre choix. Compact et sans écran, cet ordinateur de bureau est une solution pratique et polyvalente pour les environnements de bureau et domestiques.',
                'IdDetails' => 11,
                'IdTags' => 11,
                'IdImages' => 11,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Ordinateur portable Asus ROG Zephyrus G14',
                'slug' => Str::slug('Ordinateur portable Asus ROG Zephyrus G14'),
                'status' => 'Nouveau Arrivage',
                'ParametreStatus' => 'Nouveau',
                'ImagePrincipale' => 'Ordinateur-portable-Asus-ROG-Zephyrus-G14.jpg',
                'ImageDashboard' => 'Ordinateur-portable-Asus-ROG-Zephyrus-G14-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '13 420,00 DH',
                'DescriptionModal' => 'AMD Ryzen™ 5-4600HS 3.0 GHz (8M Cache, up to 4.0 GHz) - RAM: 16 GB ( 8GB DDR4 on board + 8GB DDR4-3200 SO-DIMM) - Disque dur: 512GB M.2 NVMe™ PCIe® 3.0 SSD - Écran: 14" FHD (1920 x 1080) 16:9 60Hz, Viewing Angle 170/170, IPS, Brightness 300, Contrast 700:1, NTSC 72%, SRGB 100%, Adobe 75.35% Anti glare - Carte graphique: NVIDIA® GeForce® GTX 1650 Ti 4GB GDDR6 - Windows 10 Home - Clavier: AZERTY Français - Poids: 1.60',
                'DescriptionPlus' => 'L\'ordinateur portable Asus ROG Zephyrus G14 est un concentré de puissance et de polyvalence conçu pour répondre aux besoins des joueurs et des professionnels exigeants. Animé par un processeur AMD Ryzen™ 5-4600HS cadencé à 3.0 GHz (pouvant atteindre 4.0 GHz en mode Turbo), il offre des performances exceptionnelles pour le multitâche, le jeu et les applications gourmandes en ressources. Avec une mémoire vive de 16 Go (8 Go DDR4 intégrés + 8 Go DDR4-3200 SO-DIMM), et un disque dur SSD M.2 NVMe™ PCIe® 3.0 de 512 Go, cet ordinateur garantit des temps de chargement rapides et une réactivité accrue pour une expérience utilisateur fluide et immersive. Son écran de 14 pouces FHD (1920 x 1080) IPS offre des couleurs vives et des angles de vision larges, tandis que la carte graphique NVIDIA® GeForce® GTX 1650 Ti 4 Go GDDR6 offre des performances graphiques exceptionnelles pour les jeux et les applications créatives. Livré avec Windows 10 Home et un clavier AZERTY français, ce portable est prêt à l\'emploi dès sa sortie de la boîte. Avec un poids de seulement 1,60 kg, il est également facilement transportable, ce qui en fait le compagnon idéal pour le travail ou les loisirs en déplacement.',
                'IdDetails' => 12,
                'IdTags' => 12,
                'IdImages' => 12,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'HP Smart Tank 530 Imprimante multifonction à réservoirs rechargeables',
                'slug' => Str::slug('HP Smart Tank 530 Imprimante multifonction à réservoirs rechargeables'),
                'status' => 'Nouveau Arrivage',
                'ParametreStatus' => 'Nouveau',
                'ImagePrincipale' => 'HP-Smart-Tank-530-Imprimante-multifonction-à-réservoirs-rechargeables.jpg',
                'ImageDashboard' => 'HP-Smart-Tank-530-Imprimante-multifonction-à-réservoirs-rechargeables-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '2 560,00 DH',
                'DescriptionModal' => 'Impression, numérisation, copie, chargeur automatique de documents, sans fil - Livré avec 3 x HP GT53XL Bouteilles d\'encre noire de 135 ml + 1 x HP GT52 Bouteille d\'encre cyan + 1 x HP GT52 Bouteille d\'encre magenta + 1 x HP GT52 Bouteille d\'encre jaune - Vitesse d\'impression noir: 22 pages/min (11 pages/min en norme ISO) - Vitesse d\'impression couleur: 16 pages/min (5 pages/min en norme ISO) - Qualité d\'impression noire: Jusqu\'à 1 200 x 1 200 ppp rendus - Qualité d\'impression couleur: Jusqu\'à 4 800 x 1 200 ppp optimisés couleur (si impression depuis un ordinateur et entrée 1 200 ppp) - Volume de pages mensuel recommandé: 400 à 800 - Impression recto/verso: Manuelle (prise en charge des pilotes fournie) - Fonctionne avec: 4 (1 bouteille d\'encre noire, jeu de 3 bouteilles d\'encre de couleur) - Connectivité: Port USB 2.0 haut débit, Wi-Fi, Bluetooth LE',
                'DescriptionPlus' => 'L\'imprimante multifonction HP Smart Tank 530 (4SB24A) est une solution d\'impression complète et économique pour les besoins domestiques et professionnels. Avec des fonctionnalités d\'impression, de numérisation et de copie, ainsi qu\'un chargeur automatique de documents, cette imprimante répond à une variété de besoins en matière de documentation. Elle est également équipée de réservoirs rechargeables, éliminant ainsi le besoin de cartouches d\'encre coûteuses et réduisant les coûts d\'impression à long terme. En outre, l\'imprimante est livrée avec un ensemble complet d\'encre, comprenant trois bouteilles d\'encre noire HP GT53XL de 135 ml et une bouteille d\'encre cyan, magenta et jaune HP GT52. Cette configuration garantit une impression de haute qualité, avec une vitesse d\'impression rapide de 22 pages par minute en noir et 16 pages par minute en couleur. De plus, la qualité d\'impression est exceptionnelle, avec une résolution maximale de 1200 x 1200 ppp en noir et jusqu\'à 4800 x 1200 ppp en couleur, pour des résultats nets et précis. La HP Smart Tank 530 est conçue pour une utilisation pratique, avec une capacité de volume mensuel recommandée de 400 à 800 pages. Elle offre également une connectivité polyvalente, avec des options de port USB 2.0 haut débit, Wi-Fi et Bluetooth LE. De plus, bien qu\'elle prenne en charge l\'impression recto/verso manuelle, cette imprimante est facile à utiliser grâce à ses pilotes intuitifs et conviviaux. En résumé, l\'imprimante HP Smart Tank 530 offre une combinaison idéale de performance, de qualité et de coût-efficacité, en faisant un choix judicieux pour les utilisateurs à la recherche d\'une solution d\'impression fiable et abordable.',
                'IdDetails' => 13,
                'IdTags' => 13,
                'IdImages' => 13,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Canon PG-445 Noir - Cartouche d\'encre Canon d\'origine',
                'slug' => Str::slug('Canon PG-445 Noir-Cartouche d encre Canon d origine'),
                'status' => 'Meilleures Ventes',
                'ParametreStatus' => 'Populaire',
                'ImagePrincipale' => 'Canon-PG-445-Noir-Cartouche-d-encre-Canon-d-origine.jpg',
                'ImageDashboard' => 'Canon-PG-445-Noir-Cartouche-d-encre-Canon-d-origine-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '244,00 DH',
                'DescriptionModal' => 'Obtenez des résultats exceptionnels avec la cartouche d\'encre Canon PG-445 Noir. Les encres Canon d\'origine offrent des couleurs fidèles et éclatantes, des photos durables et une qualité d\'impression supérieure. Protégez votre imprimante avec la technologie FINE exclusive de Canon. Cette cartouche jet d\'encre de 8 ml assure une précision optimale pour les petits caractères et lignes fines. Améliorez vos impressions avec les encres d\'origine Canon et profitez de performances de pointe à chaque utilisation.',
                'DescriptionPlus' => 'La cartouche d\'encre Canon PG-445 Noir offre des résultats d\'impression exceptionnels pour répondre à vos besoins quotidiens. Avec les encres Canon d\'origine, vous bénéficiez de couleurs fidèles, de photos durables et d\'une qualité d\'impression supérieure. La technologie FINE exclusive de Canon assure la protection de votre imprimante tout en garantissant des performances optimales. Avec une capacité de 8 ml, cette cartouche jet d\'encre offre une précision remarquable pour les petits caractères et les lignes fines. Améliorez vos impressions avec les encres Canon d\'origine et profitez de performances de pointe à chaque utilisation.',
                'IdDetails' => 14,
                'IdTags' => 14,
                'IdImages' => 14,
                'IdCategorie' => 4
            ],
            [
                'titre' => 'Disque Dur interne SSD Kingston FURY Renegade Heatsink M.2 2280 PCIe Gen4 x4 NVMe 1 To',
                'slug' => Str::slug('Disque Dur interne SSD Kingston FURY Renegade Heatsink M.2 2280 PCIe Gen4 x4 NVMe 1 To'),
                'status' => 'Meilleures Ventes',
                'ParametreStatus' => 'Populaire',
                'ImagePrincipale' => 'Disque-Dur-interne-SSD-Kingston-FURY-Renegade-Heatsink-M.2-2280-PCIe-Gen4-x4-NVMe-1-To.jpg',
                'ImageDashboard' => 'Disque-Dur-interne-SSD-Kingston-FURY-Renegade-Heatsink-M.2-2280-PCIe-Gen4-x4-NVMe-1-To-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '1 460,00 DH',
                'DescriptionModal' => 'Transformez votre expérience de jeu avec le Disque Dur SSD Kingston FURY Renegade Heatsink M.2 2280 PCIe Gen4 x4 NVMe 1 To. Bénéficiez de la puissance du PCIe Gen 4, offrant des transferts de données ultra-rapides jusqu\'à 8 Go/s. Ce SSD révolutionnaire offre des vitesses de lecture/écriture allant jusqu\'à 7 300/7 000 Mo/s et jusqu\'à 1 000 000 d\'IOPS. Réduisez les temps de chargement, améliorez la réactivité du système et assurez une stabilité optimale grâce à sa gestion thermique avancée. Plongez dans une performance exceptionnelle, idéale pour les passionnés de jeux et de matériel informatique exigeants.',
                'DescriptionPlus' => 'Le Disque Dur SSD Kingston FURY Renegade Heatsink M.2 2280 PCIe Gen4 x4 NVMe 1 To révolutionne votre expérience de jeu et d\'informatique avec des performances de pointe. Grâce à la technologie PCIe Gen 4, il offre des transferts de données ultra-rapides pouvant atteindre 8 Go/s, vous permettant de réduire les temps de chargement et d\'améliorer la réactivité de votre système. Avec des vitesses de lecture/écriture allant jusqu\'à 7 300/7 000 Mo/s et jusqu\'à 1 000 000 d\'IOPS, ce SSD offre des performances exceptionnelles pour répondre aux besoins des passionnés de jeux et de matériel informatique exigeants. De plus, sa gestion thermique avancée assure une stabilité optimale, garantissant des performances fiables même lors de sessions de jeu intensives.',
                'IdDetails' => 15,
                'IdTags' => 15,
                'IdImages' => 15,
                'IdCategorie' => 3
            ],
            [
                'titre' => 'Souris gaming filaire Logitech G502 X',
                'slug' => Str::slug('Souris gaming filaire Logitech G502 X '),
                'status' => 'Meilleures Ventes',
                'ParametreStatus' => 'Populaire',
                'ImagePrincipale' => 'Souris-gaming-filaire-Logitech-G502-X.jpg',
                'ImageDashboard' => 'Souris-gaming-filaire-Logitech-G502-X-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '833,00 DH',
                'DescriptionModal' => 'Plongez dans une expérience de jeu incomparable avec la souris gaming filaire Logitech G502 X. Pesant seulement 89 grammes grâce à son design repensé, elle offre une maniabilité sans égale. Dotée des tout nouveaux commutateurs optiques-mécaniques LIGHTFORCE et du capteur HERO 25K submicronique, elle garantit une précision ultime à chaque mouvement. Profitez de jusqu\'à 5 profils de mémoire embarqués pour une personnalisation totale, des patins en PTFE à faible friction pour une glisse fluide et 13 commandes programmables pour une domination totale. Compatible avec Windows® 10 ou ultérieur et Mac 10.14 ou ultérieur, elle est prête à vous accompagner dans vos aventures virtuelles dès sa connexion USB.',
                'DescriptionPlus' => 'La souris gaming filaire Logitech G502 X offre une expérience de jeu incomparable avec des performances exceptionnelles et une maniabilité sans égale. Avec son poids de seulement 89 grammes, grâce à son design repensé, elle offre une sensation de confort et de contrôle optimal. Dotée des tout nouveaux commutateurs optiques-mécaniques LIGHTFORCE et du capteur HERO 25K submicronique, cette souris garantit une précision ultime à chaque mouvement, offrant ainsi un avantage compétitif dans vos jeux préférés. Vous bénéficiez également de jusqu\'à 5 profils de mémoire embarqués pour une personnalisation totale, des patins en PTFE à faible friction pour une glisse fluide et 13 commandes programmables pour une domination totale sur le champ de bataille virtuel. Compatible avec Windows® 10 ou ultérieur et Mac 10.14 ou ultérieur, elle est prête à vous accompagner dans toutes vos aventures gaming dès sa connexion USB.',
                'IdDetails' => 16,
                'IdTags' => 16,
                'IdImages' => 16,
                'IdCategorie' => 3
            ],
            [
                'titre' => 'Clavier gaming G213 Prodigy de Logitech avec éclairage RVB et anti-ghosting Noir Français (Azerty)',
                'slug' => Str::slug('Clavier gaming G213 Prodigy de Logitech avec éclairage RVB et anti-ghosting Noir Français'),
                'status' => 'Meilleures Ventes',
                'ParametreStatus' => 'Populaire',
                'ImagePrincipale' => 'Clavier-gaming-G213-Prodigy-de-Logitech-avec-éclairage-RVB-et-anti-ghosting-Noir-Français.jpg',
                'ImageDashboard' => 'Clavier-gaming-G213-Prodigy-de-Logitech-avec-éclairage-RVB-et-anti-ghosting-Noir-Français-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '550,00 DH',
                'DescriptionModal' => 'Découvrez le clavier gaming G213 Prodigy de Logitech, offrant des performances durables pour les gamers exigeants. Ce clavier Azerty en noir, est doté de touches tactiles à dômes mécaniques résistantes aux éclaboussures, assurant une réponse rapide et silencieuse. L\'éclairage LIGHTSYNC RVB personnalisable avec 5 zones distinctes crée une expérience immersive. Son repose-poignets intégré et son inclinaison ajustable offrent un confort optimal, tandis que les commandes multimédia dédiées facilitent la gestion de vos divertissements.',
                'DescriptionPlus' => 'Le clavier gaming G213 Prodigy de Logitech est conçu pour répondre aux besoins des joueurs exigeants, offrant des performances durables et une expérience de jeu immersive. Doté de touches tactiles à dômes mécaniques résistantes aux éclaboussures, ce clavier assure une réponse rapide et silencieuse pour une expérience de frappe confortable. L\'éclairage LIGHTSYNC RVB personnalisable avec 5 zones distinctes crée une ambiance visuelle dynamique, tandis que le repose-poignets intégré et l\'inclinaison ajustable garantissent un confort optimal pendant les longues sessions de jeu. De plus, les commandes multimédia dédiées facilitent la gestion de vos divertissements, vous permettant de rester concentré sur votre jeu sans interruption.',
                'IdDetails' => 17,
                'IdTags' => 17,
                'IdImages' => 17,
                'IdCategorie' => 3
            ],
            [
                'titre' => 'Carte Graphique PNY GeForce GT 1030 NVIDIA 2 GB GDDR4',
                'slug' => Str::slug('Carte Graphique PNY GeForce GT 1030 NVIDIA 2 GB GDDR4'),
                'status' => 'Meilleures Ventes',
                'ParametreStatus' => 'Populaire',
                'ImagePrincipale' => 'Carte-Graphique-PNY-GeForce-GT-1030-NVIDIA-2-GB-GDDR4.jpg',
                'ImageDashboard' => 'Carte-Graphique-PNY-GeForce-GT-1030-NVIDIA-2-GB-GDDR4-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '2 070,00 DH',
                'DescriptionModal' => 'La carte graphique PNY GeForce GT 1030 NVIDIA 2 GB GDDR4 offre des performances optimisées grâce à son architecture Pascal. Dotée de 384 cœurs CUDA et 2 Go de VRAM DDR4, elle excelle dans les applications gourmandes en ressources. La sortie HDMI 2.0b et DVI-D permettent une résolution maximale de 4096 x 2160. Son refroidissement efficace à ventilateur unique garantit des performances stables. Exploitez CUDA pour accélérer les tâches et profitez de la technologie NVIDIA GPU Boost 3.0 pour une augmentation dynamique de la fréquence d\'horloge en temps réel. Accélérez vos applications et jeux avec cette carte graphique polyvalente.',
                'DescriptionPlus' => 'La carte graphique PNY GeForce GT 1030 NVIDIA 2 GB GDDR4 offre des performances optimisées pour répondre aux besoins des utilisateurs exigeants. Avec son architecture Pascal, dotée de 384 cœurs CUDA et de 2 Go de VRAM DDR4, elle excelle dans les applications gourmandes en ressources, offrant ainsi une expérience fluide et réactive. Les sorties HDMI 2.0b et DVI-D permettent une résolution maximale de 4096 x 2160, garantissant une qualité d\'affichage exceptionnelle. Son refroidissement efficace à ventilateur unique assure des performances stables, même lors d\'une utilisation prolongée. Exploitez les capacités CUDA pour accélérer les tâches et profitez de la technologie NVIDIA GPU Boost 3.0 pour une augmentation dynamique de la fréquence d\'horloge en temps réel. Avec cette carte graphique polyvalente, accélérez vos applications et jeux pour une expérience informatique optimale.',
                'IdDetails' => 18,
                'IdTags' => 18,
                'IdImages' => 18,
                'IdCategorie' => 3
            ],
            [
                'titre' => 'Switch Smart TP-Link TL-SG2218 JetStream 16 ports Gigabit avec 2 slots SFP',
                'slug' => Str::slug('Switch Smart TP-Link TL-SG2218 JetStream 16 ports Gigabit avec 2 slots SFP'),
                'status' => 'Meilleures Ventes',
                'ParametreStatus' => 'Populaire',
                'ImagePrincipale' => 'Switch-Smart-TP-Link-TL-SG2218-JetStream-16-ports-Gigabit-avec-2-slots-SFP.jpg',
                'ImageDashboard' => 'Switch-Smart-TP-Link-TL-SG2218-JetStream-16-ports-Gigabit-avec-2-slots-SFP-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '1 680,00 DH',
                'DescriptionModal' => 'Le Smart Switch TP-Link TL-SG2218 JetStream offre 16 ports Gigabit RJ45 et 2 slots SFP Gigabit, assurant des connexions haut débit. Grâce à la gestion centralisée du cloud Omada SDN, profitez d\'une administration pratique et d\'une surveillance intelligente. Bénéficiez de stratégies de sécurité avancées, d\'une optimisation des applications vocales et vidéo, ainsi que de puissantes capacités de gestion autonome. Idéal pour créer un réseau Omada complet et sécurisé.',
                'DescriptionPlus' => 'Le Switch Smart TP-Link TL-SG2218 JetStream offre une connectivité fiable et haut débit avec ses 16 ports Gigabit RJ45 et 2 slots SFP Gigabit. Grâce à la gestion centralisée du cloud Omada SDN, ce switch permet une administration aisée et une surveillance intelligente de votre réseau. Profitez de fonctionnalités avancées de sécurité, d\'une optimisation des applications vocales et vidéo, ainsi que de puissantes capacités de gestion autonome. Parfait pour établir un réseau Omada complet et sécurisé, ce switch répond aux besoins des entreprises cherchant à garantir une connectivité réseau stable et performante.',
                'IdDetails' => 19,
                'IdTags' => 19,
                'IdImages' => 19,
                'IdCategorie' => 2
            ],
            [
                'titre' => 'Imprimante A3 Multifonction Jet d’encre HP OfficeJet Pro 7740',
                'slug' => Str::slug('Imprimante A3 Multifonction Jet d’encre HP OfficeJet Pro 7740'),
                'status' => 'Meilleures Ventes',
                'ParametreStatus' => 'Populaire',
                'ImagePrincipale' => 'Imprimante-A3-Multifonction-Jet-d-encre-HP-OfficeJet-Pro-7740.jpg',
                'ImageDashboard' => 'Imprimante-A3-Multifonction-Jet-d-encre-HP-OfficeJet-Pro-7740-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '3 430,00 DH',
                'DescriptionModal' => 'Impression, copie, scan, fax - Vitesse d\'impression noir: 34 pages/min (22 pages/min en norme ISO) - Vitesse d\'impression couleur: 34 pages/min (18 pages/min en norme ISO) - Qualité d\'impression noire: Jusqu\'à 1 200 x 1 200 DPI (ppp) rendus - Qualité d\'impression couleur: Jusqu\'à 4 800 x 1 200 DPI (ppp) optimisés - Volume de pages mensuel recommandé: De 250 à 1 500 pages/mois - Impression recto/verso: Automatique - Fonctionne avec: 4 Cartouches (noir, cyan, magenta, jaune) - Connectivité: 1 port USB 2.0, Ethernet intégré, Wi-Fi, 2 ports RJ-11 - Encres fournies avec l\'imprimante: HP 953 noir (environ 1 000 pages) + HP 953 CMJ (environ 540 pages)',
                'DescriptionPlus' => 'L\'imprimante A3 Multifonction Jet d\'encre HP OfficeJet Pro 7740 offre une polyvalence exceptionnelle pour répondre à tous vos besoins d\'impression, de copie, de numérisation et de télécopie. Avec une vitesse d\'impression de 34 pages par minute en noir et blanc et en couleur, cette imprimante vous permet de réaliser vos tâches rapidement et efficacement. Vous bénéficiez également d\'une qualité d\'impression exceptionnelle avec une résolution pouvant atteindre 1 200 x 1 200 DPI pour le noir et jusqu\'à 4 800 x 1 200 DPI pour la couleur, assurant ainsi des documents nets et professionnels à chaque impression. Grâce à son volume de pages mensuel recommandé allant de 250 à 1 500 pages par mois, cette imprimante convient parfaitement aux utilisateurs à domicile ou aux petites entreprises nécessitant une impression régulière. De plus, la fonction d\'impression recto/verso automatique vous permet d\'économiser du papier tout en réduisant votre impact environnemental. Cette imprimante est équipée de quatre cartouches d\'encre (noir, cyan, magenta, jaune), fournissant ainsi des couleurs vives et éclatantes pour vos documents et vos photos. De plus, avec une connectivité étendue comprenant un port USB 2.0, Ethernet intégré, Wi-Fi et deux ports RJ-11 pour le fax, vous pouvez facilement partager l\'imprimante avec plusieurs appareils et imprimer depuis n\'importe où dans votre maison ou votre bureau. Enfin, les encres fournies avec l\'imprimante vous permettent de commencer à imprimer immédiatement, avec une cartouche noire d\'une autonomie d\'environ 1 000 pages et des cartouches CMJ (cyan, magenta, jaune) d\'une autonomie d\'environ 540 pages chacune. Avec ses fonctionnalités avancées et sa qualité d\'impression remarquable, l\'imprimante A3 Multifonction Jet d\'encre HP OfficeJet Pro 7740 est un choix idéal pour ceux qui recherchent une solution d\'impression professionnelle et polyvalente.',
                'IdDetails' => 20,
                'IdTags' => 20,
                'IdImages' => 20,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Sac à dos Casual Lenovo ThinkPad B210 15,6"',
                'slug' => Str::slug('Sac à dos Casual Lenovo ThinkPad B210 15,6"'),
                'status' => 'Meilleures Ventes',
                'ParametreStatus' => 'Populaire',
                'ImagePrincipale' => 'Sac-à-dos-Casual-Lenovo-ThinkPad-B210-15-6.jpg',
                'ImageDashboard' => 'Sac-à-dos-Casual-Lenovo-ThinkPad-B210-15-6-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '166,00 DH',
                'DescriptionModal' => 'Transportez votre ordinateur portable avec style et praticité grâce au sac à dos Casual Lenovo ThinkPad B210 15,6". Son design compact convient parfaitement pour le travail et l\'école. Fabriqué en polyester durable, il dispose d\'un intérieur rembourré pour protéger vos notebooks et vos objets importants. Une poche zippée à accès rapide offre un espace de rangement supplémentaire. Son panneau arrière matelassé assure un confort optimal tout au long de la journée. Ce sac à dos est compatible avec des ordinateurs jusqu\'à 15,6". Profitez de la garantie limitée d\'un an offerte par Lenovo.',
                'DescriptionPlus' => 'Le sac à dos Casual Lenovo ThinkPad B210 15,6" offre un mélange parfait de style, de praticité et de durabilité pour transporter votre ordinateur portable en toute sécurité. Conçu pour convenir aussi bien au travail qu\'à l\'école, ce sac à dos compact est fabriqué en polyester durable, garantissant une protection fiable pour vos notebooks et vos objets importants. Son intérieur rembourré offre une protection supplémentaire contre les chocs et les rayures, tandis que la poche zippée à accès rapide vous permet de ranger facilement vos accessoires essentiels tels que les chargeurs, les câbles et les clés USB. Le sac à dos Casual Lenovo ThinkPad B210 15,6" est doté d\'un panneau arrière matelassé qui assure un confort optimal même lors de longues journées de déplacement. Grâce à sa conception ergonomique, vous pouvez porter votre sac à dos en toute tranquillité d\'esprit, sachant que votre dos est bien soutenu. De plus, sa capacité de transporter des ordinateurs portables jusqu\'à 15,6" en fait un compagnon idéal pour les déplacements professionnels ou les voyages scolaires. Profitez également de la garantie limitée d\'un an offerte par Lenovo, ce qui vous permet d\'acheter en toute confiance, sachant que votre sac à dos est couvert en cas de défaut de fabrication. Avec son design élégant, sa praticité et sa durabilité exceptionnelle, le sac à dos Casual Lenovo ThinkPad B210 15,6" est un choix parfait pour ceux qui recherchent un sac à dos polyvalent et fiable pour transporter leur ordinateur portable au quotidien.',
                'IdDetails' => 21,
                'IdTags' => 21,
                'IdImages' => 21,
                'IdCategorie' => 3
            ],
            [
                'titre' => 'Epson EcoTank L18050 Imprimante Photo A3+ à réservoirs rechargeables',
                'slug' => Str::slug('Epson EcoTank L18050 Imprimante Photo A3+ à réservoirs rechargeables'),
                'status' => 'Articles Soldés',
                'ParametreStatus' => 'Solde',
                'ImagePrincipale' => 'Epson-EcoTank-L18050-Imprimante-Photo-A3-à-réservoirs-rechargeables.jpg',
                'ImageDashboard' => 'Epson-EcoTank-L18050-Imprimante-Photo-A3-à-réservoirs-rechargeables-228px-250px.jpg',
                'AncienPrix' => '11 880,00 DH',
                'NouveauPrix' => '11 180,00 DH',
                'DescriptionModal' => 'Livrée avec 6 bouteilles d\'encre individuelles de 70 ml (Noir, Cyan, Jaune, Magenta, Cyan Clair, Magenta Clair) - Vitesse d\'impression noir: 22 pages/min (8 pages/min en norme ISO) - Vitesse d\'impression couleur: 22 pages/min (8 pages/min en norme ISO) - Qualité d\'impression noire: 5.760 x 1.440 DPI (ppp) - Qualité d\'impression couleur: 5.760 x 1.440 DPI (ppp) - Impression recto/verso: Manuelle - Fonctionne avec: 6 Réservoirs (magenta clair, magenta, jaune, cyan clair, cyan, noir) - Connectivité: Wi-Fi, Wi-Fi Direct, USB',
                'DescriptionPlus' => 'L\'imprimante Epson EcoTank L18050 est une solution idéale pour les besoins d\'impression photo haute qualité et économique. Livrée avec 6 bouteilles d\'encre individuelles de 70 ml, elle offre des performances impressionnantes avec une vitesse d\'impression de 22 pages par minute en noir et en couleur. Dotée d\'une qualité d\'impression exceptionnelle de 5.760 x 1.440 DPI, cette imprimante garantit des photos nettes et éclatantes à chaque impression. Bien qu\'elle offre une impression recto/verso manuelle, sa connectivité Wi-Fi, Wi-Fi Direct et USB assure une facilité d\'utilisation et une flexibilité de connexion pour tous vos appareils. Avec ses réservoirs rechargeables, cette imprimante offre une solution économique et écologique pour vos besoins d\'impression photo A3+.',
                'IdDetails' => 22,
                'IdTags' => 22,
                'IdImages' => 22,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Serveur HPE ProLiant DL20 Gen10 Plus E-2314 2.8 GHz 4 cœurs ,1 Processeur 8GO-U 2 lecteurs à grand facteur de forme NHP',
                'slug' => Str::slug('Serveur HPE ProLiant DL20 Gen10 Plus E-2314 2.8 GHz 4 cœurs ,1 Processeur 8GO-U 2 lecteurs à grand facteur de forme NHP'),
                'status' => 'Articles Soldés',
                'ParametreStatus' => 'Solde',
                'ImagePrincipale' => 'Serveur-HPE-ProLiant-DL20-Gen10-Plus-E-2314.jpg',
                'ImageDashboard' => 'Serveur-HPE-ProLiant-DL20-Gen10-Plus-E-2314-228px-250px.jpg',
                'AncienPrix' => '21 721,00 DH',
                'NouveauPrix' => '19 860,00 DH',
                'DescriptionModal' => 'Noyau processeur disponible: 4 à 8 cœurs, selon le processeur - Mémoire cache du processeur: Jusqu’à 16 Mo de mémoire Intel® Smart Cache, selon le processeur - Nombre de processeurs: 1 - Vitesse du processeur: 5.0 GHz maximum selon le processeur - Type de mémoire: Mémoire standard HPE DDR4 - Gestion de l\'infrastructure: HPE iLO5 - Logements d\'extension: Deux maximum - Contrôleur réseau: Adaptateur réseau HPE BCM5720 1 Go 2 ports intégré - Contrôleur de stockage: Intel® VROC SATA (anciennement Intel® RSTe) - Format: 1U - Dimensions du produit: 4,32 x 43,46 x 38,22 cm - Poids: 6 kg minimum, 9,46 kg maximum',
                'DescriptionPlus' => 'Le serveur HPE ProLiant DL20 Gen10 Plus E-2314 offre des performances fiables et évolutives pour les besoins informatiques essentiels des petites et moyennes entreprises. Doté d\'un processeur Intel® Xeon® E-2314 à 2,8 GHz et jusqu\'à 8 cœurs de traitement, ce serveur offre une puissance de calcul optimale pour les charges de travail variées. Avec une mémoire cache pouvant aller jusqu\'à 16 Mo et une vitesse maximale du processeur de 5,0 GHz, il garantit des performances fluides même lors des tâches les plus exigeantes. Le serveur HPE ProLiant DL20 Gen10 Plus est équipé de 8 Go de mémoire DDR4 standard, offrant une grande capacité de traitement des données et une fiabilité optimale pour les opérations quotidiennes. Il dispose également de 2 lecteurs à grand facteur de forme NHP, offrant une flexibilité de stockage pour répondre aux besoins évolutifs de l\'entreprise. Avec la gestion de l\'infrastructure HPE iLO5 intégrée, ce serveur offre une administration simplifiée et une surveillance à distance, ce qui permet aux administrateurs informatiques de gérer efficacement le serveur depuis n\'importe où. De plus, avec le contrôleur réseau HPE BCM5720 1 Go intégré et le contrôleur de stockage Intel® VROC SATA, ce serveur assure une connectivité réseau rapide et une gestion efficace du stockage des données. Le serveur HPE ProLiant DL20 Gen10 Plus est conçu dans un format compact de 1U, ce qui le rend idéal pour les environnements informatiques avec des contraintes d\'espace. Avec des dimensions de 4,32 x 43,46 x 38,22 cm et un poids allant de 6 kg minimum à 9,46 kg maximum, il est facile à intégrer dans n\'importe quel rack de serveur standard. En résumé, ce serveur offre une combinaison puissante de performances, de fiabilité et de gestion simplifiée pour répondre aux besoins informatiques actuels et futurs des entreprises.',
                'IdDetails' => 23,
                'IdTags' => 23,
                'IdImages' => 23,
                'IdCategorie' => 2
            ],
            [
                'titre' => 'Ordinateur Portable Lenovo V15 G3 IAP',
                'slug' => Str::slug('Ordinateur Portable Lenovo V15 G3 IAP'),
                'status' => 'Articles Soldés',
                'ParametreStatus' => 'Solde',
                'ImagePrincipale' => 'Ordinateur-Portable-Lenovo-V15-G3-IAP.jpg',
                'ImageDashboard' => 'Ordinateur-Portable-Lenovo-V15-G3-IAP-228px-250px.jpg',
                'AncienPrix' => '6 460,00 DH',
                'NouveauPrix' => '4 790,00 DH',
                'DescriptionModal' => 'Intel® Core™ i3-1215U, 6C (2P + 4E) / 8T, P-core 1.2 / 4.4GHz, E-core 0.9 / 3.3GHz, 10MB - RAM: 8 GB (4GB Soldered DDR4-3200 + 4GB SO-DIMM DDR4-3200) - Disque dur: 256GB SSD M.2 2242 PCIe® 4.0x4 NVMe® - Écran: 15.6" FHD (1920x1080) TN 250nits Anti-glare - Carte graphique: Integrated Intel® UHD - FreeDOS (Sans Windows) - Clavier: Non-backlit, français (AZERTY) - Poids: À partir de 1.7 kg',
                'DescriptionPlus' => 'L\'ordinateur portable Lenovo V15 G3 IAP offre des performances fiables dans un design portable et élégant. Équipé d\'un processeur Intel® Core™ i3-1215U avec 6 cœurs et une vitesse pouvant atteindre 4,4 GHz, cet ordinateur portable offre une puissance de traitement optimale pour les tâches quotidiennes et les applications multitâches. Avec 8 Go de mémoire RAM DDR4 et un SSD M.2 PCIe® 4.0x4 NVMe® de 256 Go, il offre des performances fluides et une capacité de stockage suffisante pour vos fichiers et applications. Doté d\'un écran Full HD de 15,6 pouces avec une résolution de 1920x1080 et une luminosité de 250 nits, cet ordinateur portable offre une expérience visuelle nette et immersive. La technologie anti-reflet assure un confort visuel même dans des conditions d\'éclairage difficiles. Avec une carte graphique intégrée Intel® UHD, il offre des performances graphiques décentes pour la navigation sur le Web, le streaming vidéo et les tâches bureautiques. Livré avec FreeDOS préinstallé, cet ordinateur portable offre une flexibilité pour installer le système d\'exploitation de votre choix. Le clavier AZERTY français et le poids léger de seulement 1,7 kg en font un compagnon idéal pour les déplacements quotidiens. Bien que le clavier ne soit pas rétroéclairé, il offre une expérience de frappe confortable pour une utilisation prolongée. En résumé, le Lenovo V15 G3 IAP est un ordinateur portable polyvalent qui offre des performances fiables et une portabilité pratique pour répondre à vos besoins informatiques quotidiens.',
                'IdDetails' => 24,
                'IdTags' => 24,
                'IdImages' => 24,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Écran Plat 32" Samsung Smart Monitor S5',
                'slug' => Str::slug('Écran Plat 32" Samsung Smart Monitor S5'),
                'status' => 'Articles Soldés',
                'ParametreStatus' => 'Solde',
                'ImagePrincipale' => 'Écran-Plat-32"-Samsung-Smart-Monitor-S5.jpg',
                'ImageDashboard' => 'Écran-Plat-32"-Samsung-Smart-Monitor-S5-228px-250px.jpg',
                'AncienPrix' => '4 668,00 DH',
                'NouveauPrix' => '3 100,00 DH',
                'DescriptionModal' => 'Taille de l\'écran: 32" - Format 16:9 - Courbure de l\'écran: Plat - Type de Dalle: VA (Vertical Alignment) - Rétroéclairage: LED - Résolution: Full HD 1920 x 1080 - Temps de réponse: 4 ms (gris à gris) - Taux de rafraîchissement: Max 60 Hz - Connecteurs d\'entrée: HDMI, USB Hub - Réglages de la position de l\'écran: -2,0 °(±2,0 °) ~ +22,0 °(±2,0 °)',
                'DescriptionPlus' => 'L\'écran plat Samsung Smart Monitor S5 de 32 pouces offre une expérience visuelle immersive dans un format spacieux et élégant. Doté d\'une dalle VA (Vertical Alignment) et d\'un rétroéclairage LED, il garantit des couleurs vives et un contraste élevé pour une qualité d\'image exceptionnelle. Avec une résolution Full HD de 1920 x 1080 pixels, chaque détail est rendu avec une netteté remarquable, offrant une expérience de visionnage immersive pour les jeux, les films et la navigation sur le Web. Avec un temps de réponse rapide de 4 ms (gris à gris), cet écran offre une réactivité fluide, idéale pour les jeux rapides et les vidéos d\'action. Grâce à ses connecteurs HDMI et USB Hub, vous pouvez facilement connecter vos appareils et accessoires pour une expérience de divertissement polyvalente. De plus, avec des options de réglage de position d\'écran allant de -2,0 ° à +22,0 °, vous pouvez ajuster l\'écran selon vos préférences de visualisation pour un confort optimal pendant de longues sessions.',
                'IdDetails' => 25,
                'IdTags' => 25,
                'IdImages' => 25,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Onduleur Line-interactive Eaton 5E 1200 USB - 660 W / 1200 VA - 6 prises C13',
                'slug' => Str::slug('Onduleur Line-interactive Eaton 5E 1200 USB - 660 W  1200 VA - 6 prises C13'),
                'status' => 'Articles Soldés',
                'ParametreStatus' => 'Solde',
                'ImagePrincipale' => 'Onduleur-Line-interactive-Eaton-5E-1200-USB-660W-1200VA-6-prises-C13.jpg',
                'ImageDashboard' => 'Onduleur-Line-interactive-Eaton-5E-1200-USB-660W-1200VA-6-prises-C13-228px-250px.jpg',
                'AncienPrix' => '1 608,00 DH',
                'NouveauPrix' => '1 520,00 DH',
                'DescriptionModal' => 'Technologie: Line-interactive - Puissance: 660 W / 1200 VA - Tension (sortie/entrée): 195-257 V / 230V par défaut (220/230/240V) - Fréquence (sortie/entrée): 50/60 Hz / 45-63 Hz - Connexions 1 de sortie: (6) IEC-320-C13 - Connexions d\'entrée: (1) IEC-320-C14 - Phase (sortie/entrée): 1 / 1',
                'DescriptionPlus' => 'L\'onduleur Line-interactive Eaton 5E 1200 USB offre une protection fiable pour vos équipements électroniques sensibles. Avec une puissance de 660 W / 1200 VA, il assure une alimentation électrique stable pour prévenir les interruptions dues aux fluctuations de tension ou aux pannes de courant. Équipé de la technologie Line-interactive, cet onduleur corrige automatiquement les fluctuations de tension sans basculer sur la batterie, garantissant ainsi une protection efficace tout en prolongeant la durée de vie de la batterie. Avec ses 6 prises C13, il offre une connectivité pratique pour vos appareils essentiels. Compact et facile à installer, il est idéal pour une utilisation à domicile ou en petit bureau.',
                'IdDetails' => 26,
                'IdTags' => 26,
                'IdImages' => 26,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Station de travail HP Z6 Tower G5',
                'slug' => Str::slug('Station de travail HP Z6 Tower G5'),
                'status' => 'Articles Soldés',
                'ParametreStatus' => 'Solde',
                'ImagePrincipale' => 'Station-de-travail-HP-Z6-Tower-G5.jpg',
                'ImageDashboard' => 'Station-de-travail-HP-Z6-Tower-G5-228px-250px.jpg',
                'AncienPrix' => '49 188,00 DH',
                'NouveauPrix' => '44 770,00 DH',
                'DescriptionModal' => 'Intel Xeon W5-3423 12C 220W CPU - RAM: 16GB (1x16GB) DDR5 4800 DIMM ECC REG Mem - Disque dur: 2TB PCIe 2280 TLC M.2 2nd SSD - Carte graphique: NVIDIA T1000 8GB 4mDP GFX - FreeDOS (Sans Windows) - Unité centrale sans écran',
                'DescriptionPlus' => 'La station de travail HP Z6 Tower G5 (6E455AV-00342) est un système informatique puissant conçu pour répondre aux besoins des professionnels exigeants. Dotée d\'un processeur Intel Xeon W5-3423 12C 220W, cette station offre des performances exceptionnelles pour les tâches informatiques les plus exigeantes. Avec 16 Go de mémoire DDR5 4800 DIMM ECC REG, elle garantit une exécution fluide des applications gourmandes en ressources. Le disque dur de 2 To PCIe 2280 TLC M.2 2nd SSD offre un espace de stockage généreux pour vos données et programmes. De plus, la carte graphique NVIDIA T1000 8GB 4mDP GFX assure des performances graphiques de haute qualité pour la modélisation 3D, la conception assistée par ordinateur et d\'autres tâches graphiques intensives. Livré avec FreeDOS, cet ordinateur offre une flexibilité maximale pour installer le système d\'exploitation de votre choix. Parfait pour les professionnels créatifs et techniques, cette station de travail offre une combinaison imbattable de puissance, de fiabilité et de polyvalence.',
                'IdDetails' => 27,
                'IdTags' => 27,
                'IdImages' => 27,
                'IdCategorie' => 1
            ],
            [
                'titre' => 'Modem / Routeur 4G LTE WiFi TP-Link Archer MR200 AC750 Mbps bi-bande',
                'slug' => Str::slug('Modem Routeur 4G LTE WiFi TP-Link Archer MR200 AC750 Mbps bi-bande'),
                'status' => 'Articles Soldés',
                'ParametreStatus' => 'Solde',
                'ImagePrincipale' => 'Modem-Routeur-4G-LTE-WiFi-TP-Link-Archer-MR200-AC750-Mbps-bi-bande.jpg',
                'ImageDashboard' => 'Modem-Routeur-4G-LTE-WiFi-TP-Link-Archer-MR200-AC750-Mbps-bi-bande-228px-250px.jpg',
                'AncienPrix' => '1 126,00 DH',
                'NouveauPrix' => '942,00 DH',
                'DescriptionModal' => 'Profitez d\'une connexion Internet haut débit partout avec le Modem/Routeur 4G LTE WiFi TP-Link AC750. Ce 2-en-1 combine un modem 4G LTE et un routeur WiFi, idéal pour ceux avec un faible débit ADSL et une bonne couverture 4G. Partagez facilement votre réseau 4G avec plusieurs appareils grâce à un débit allant jusqu\'à 150 Mbps. Les antennes externes assurent une réception optimale, tandis que la large couverture WiFi dans toute la maison garantit une excellente connectivité. L\'installation est simple et rapide, et vous pouvez connecter jusqu\'à 64 appareils simultanément. Emportez-le facilement en vacances pour profiter de la 4G et du partage WiFi partout.',
                'DescriptionPlus' => 'Le Modem/Routeur 4G LTE WiFi TP-Link Archer MR200 AC750 offre une connectivité Internet haut débit où que vous soyez. Grâce à sa double fonctionnalité de modem 4G LTE et de routeur WiFi, il est idéal pour les utilisateurs confrontés à un faible débit ADSL mais bénéficiant d\'une bonne couverture 4G. Avec un débit pouvant atteindre 150 Mbps, il permet de partager facilement la connexion 4G avec plusieurs appareils, offrant ainsi une connectivité rapide et stable. Les antennes externes garantissent une réception optimale, tandis que la large couverture WiFi dans toute la maison assure une connectivité sans interruption. L\'installation est simple et rapide, et jusqu\'à 64 appareils peuvent être connectés simultanément, ce qui en fait une solution pratique pour les foyers et les petites entreprises. Avec sa portabilité, il est également parfait pour les voyages, offrant ainsi un accès à la 4G et au partage WiFi partout où vous allez.',
                'IdDetails' => 28,
                'IdTags' => 28,
                'IdImages' => 28,
                'IdCategorie' => 2
            ],
            [
                'titre' => 'Logitech BRIO ULTRA HD PRO WEBCAM',
                'slug' => Str::slug('Logitech BRIO ULTRA HD PRO WEBCAM'),
                'status' => 'Articles Soldés',
                'ParametreStatus' => 'Solde',
                'ImagePrincipale' => 'Logitech-BRIO-ULTRA-HD-PRO-WEBCAM.jpg',
                'ImageDashboard' => 'Logitech-BRIO-ULTRA-HD-PRO-WEBCAM-228px-250px.jpg',
                'AncienPrix' => '2 748,00 DH',
                'NouveauPrix' => '2 570,00 DH',
                'DescriptionModal' => 'Appel vidéo en Ultra HD 4K (jusqu\'à 4 096 x 2 160 pixels à 30 images/seconde) - Appel vidéo en Full HD 1080p (jusqu\'à 1 920 x 1 080 pixels à 30 ou 60 images par seconde) - Appel vidéo en HD 720p (jusqu\'à 1 280 x 720 pixels à 30, 60 ou 90 images/seconde) - Connectivité USB prêt à l\'emploi - Champ de vision: Diagonal: 90° - Horizontal: 82,1° - Vertical: 52,2° - Zoom numérique 5x en Full HD - Mise au point automatique - Deux microphones omnidirectionnels intégrés avec technologie antiparasite - Volet de 1 confidentialité externe - Options de fixation multiples, comprenant un clip et un trépied',
                'DescriptionPlus' => 'La webcam Logitech BRIO ULTRA HD PRO offre des performances exceptionnelles pour les appels vidéo, avec une qualité d\'image allant jusqu\'à l\'Ultra HD 4K (4096 x 2160 pixels) à 30 images par seconde, garantissant une clarté et une netteté optimales. De plus, elle prend en charge la vidéo en Full HD 1080p à 30 ou 60 images par seconde, ainsi que la vidéo en HD 720p à 30, 60 ou 90 images par seconde, offrant ainsi une flexibilité pour répondre à différents besoins en résolution. Grâce à sa connectivité USB prête à l\'emploi, la mise en place de la webcam est rapide et facile, sans avoir besoin de pilotes supplémentaires. Son champ de vision étendu offre une vision large et immersive, avec un angle diagonal de 90°, horizontal de 82,1° et vertical de 52,2°, permettant de capturer facilement plusieurs personnes ou une grande partie de l\'espace de travail. Avec un zoom numérique 5x en Full HD, la webcam Logitech BRIO permet de se concentrer sur les détails importants avec précision, tandis que la mise au point automatique assure une netteté optimale à tout moment. Deux microphones omnidirectionnels intégrés avec technologie antiparasite garantissent un son clair et naturel lors des appels vidéo, tandis que le volet de confidentialité externe offre une tranquillité d\'esprit en assurant la protection de la vie privée lorsque la webcam n\'est pas utilisée. La webcam BRIO est également polyvalente en termes de fixation, offrant plusieurs options, y compris un clip pour une fixation facile sur un écran d\'ordinateur portable ou un moniteur, ainsi qu\'un trépied pour une installation stable sur une surface plane. Ces caractéristiques font de la Logitech BRIO ULTRA HD PRO une solution idéale pour les appels vidéo professionnels, les visioconférences, les diffusions en direct et bien plus encore.',
                'IdDetails' => 29,
                'IdTags' => 29,
                'IdImages' => 29,
                'IdCategorie' => 3
            ],
            [
                'titre' => 'BOITE DE 10 DVD+R VERBATIM DOUBLE LAYER 8.5GB 8X MATT SILVER',
                'slug' => Str::slug('BOITE DE 10 DVD+R VERBATIM DOUBLE LAYER 8.5GB 8X MATT SILVER'),
                'status' => null,
                'ParametreStatus' => null,
                'ImagePrincipale' => 'BOITE-DE-10-DVD-plus-R-VERBATIM-DOUBLE-LAYER-8.5GB-8X-MATT-SILVER.jpg',
                'ImageDashboard' => 'BOITE-DE-10-DVD-plus-R-VERBATIM-DOUBLE-LAYER-8.5GB-8X-MATT-SILVER-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '750,00 Dhs',
                'DescriptionModal' => 'Les DVDR DL de Verbatim utilisent la technologie MKM/Verbatim, qui assure à tout enregistrement une qualité supérieure. Grâce à son étroite collaboration avec les fabricants de lecteurs, le département de Recherche et développement de Mitsubishi Chemical assure la compatibilité étendue des disques Verbatim, ce qui en fait le support idéal pour partager des données informatiques, ainsi que des vidéos amateurs, des photos et de la musique.',
                'DescriptionPlus' => 'Les DVD+R Verbatim Double Layer offrent une capacité de stockage généreuse de 8,5 Go par disque, permettant d\'enregistrer une grande quantité de données, de vidéos ou de fichiers multimédias. Grâce à la technologie MKM/Verbatim, la qualité d\'enregistrement est garantie, assurant des performances supérieures à chaque utilisation. En collaborant étroitement avec les fabricants de lecteurs, le département de Recherche et Développement de Mitsubishi Chemical assure une compatibilité étendue des disques Verbatim avec une variété de lecteurs, ce qui en fait un choix idéal pour partager des données informatiques, des vidéos amateurs, des photos et de la musique. La surface matte silver offre un aspect élégant et professionnel, tout en permettant une étiquetage facile avec un marqueur permanent. Avec cette boîte de 10 DVD+R, vous disposez d\'un stock fiable et durable pour archiver et partager vos précieuses données en toute sécurité.',
                'IdDetails' => 30,
                'IdTags' => 30,
                'IdImages' => 30,
                'IdCategorie' => 4
            ],
            [
                'titre' => 'Ramette de papier Navigator Universal NAVA480 Papier A4, 80 g/m² 5 flux (500 feuilles)',
                'slug' => Str::slug('Ramette de papier Navigator Universal NAVA480 Papier A4, 5 flux 500 feuilles'),
                'status' => null,
                'ParametreStatus' => null,
                'ImagePrincipale' => 'Ramette-de-papier-Navigator-Universal-NAVA480-Papier-A4-80-g-par-m²-5-flux-500-feuilles.jpg',
                'ImageDashboard' => 'Ramette-de-papier-Navigator-Universal-NAVA480-Papier-A4-80-g-par-m²-5-flux-500-feuilles-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '68,00 DH',
                'DescriptionModal' => 'Le papier Navigator Universal NAVA480 offre une qualité inégalée pour 1 vos besoins d\'impression. Certifié FSC, il garantit une source responsable de fibres. Avec un grammage de 80g/m², il allie légèreté et résistance. Ses dimensions A4 (21 x 29,7 cm) en font un choix polyvalent. Chaque paquet contient 500 feuilles de papier blanc non couché de haute qualité. Idéal pour des impressions nettes et durables.',
                'DescriptionPlus' => 'La ramette de papier Navigator Universal NAVA480 est le choix parfait pour répondre à vos besoins d\'impression au quotidien. Avec sa qualité inégalée, ce papier garantit des impressions nettes et durables pour une présentation professionnelle de vos documents. Certifié FSC, il offre une source responsable de fibres, soulignant ainsi votre engagement envers la durabilité environnementale. Avec un grammage de 80g/m², ce papier allie légèreté et résistance, assurant une manipulation facile tout en garantissant des impressions de haute qualité. Avec ses dimensions A4 (21 x 29,7 cm), ce papier est polyvalent et convient à une variété d\'applications d\'impression, que ce soit pour des rapports, des présentations ou des documents quotidiens. Chaque paquet contient 500 feuilles de papier blanc non couché, offrant une grande quantité de papier pour répondre à vos besoins d\'impression à long terme.',
                'IdDetails' => 31,
                'IdTags' => 31,
                'IdImages' => 31,
                'IdCategorie' => 4
            ],
            [
                'titre' => 'HUB USB C UGREEN 4 PORTS USB 3.0 ADAPTATEUR USB TYPE C',
                'slug' => Str::slug('HUB USB C UGREEN 4 PORTS USB 3.0 ADAPTATEUR USB TYPE C'),
                'status' => null,
                'ParametreStatus' => null,
                'ImagePrincipale' => 'HUB-USB-C-UGREEN-4-PORTS-USB-3.0-ADAPTATEUR-USB-TYPE-C.jpg',
                'ImageDashboard' => 'HUB-USB-C-UGREEN-4-PORTS-USB-3.0-ADAPTATEUR-USB-TYPE-C-228px-250px.jpg',
                'AncienPrix' => null,
                'NouveauPrix' => '190,00 Dhs',
                'DescriptionModal' => 'Le HUB USB C UGREEN 4 ports USB 3.0 est un adaptateur USB de type C qui étend les capacités de connectivité de votre appareil. Avec quatre ports USB 3.0 supplémentaires, vous pouvez connecter plusieurs périphériques simultanément, tels que des clés USB, des disques durs externes, des souris et des claviers, à votre ordinateur portable ou à votre smartphone via un seul port USB de type C. Compact et portable, cet adaptateur est idéal pour une utilisation au bureau, à la maison ou en déplacement. Grâce à sa compatibilité universelle avec une large gamme d\'appareils USB de type C, le HUB USB C UGREEN simplifie la connectivité et facilite la gestion de vos périphériques.',
                'DescriptionPlus' => 'Le HUB USB C UGREEN 4 ports USB 3.0 est un adaptateur USB de type C qui étend les capacités de connectivité de votre appareil. Avec quatre ports USB 3.0 supplémentaires, vous pouvez connecter plusieurs périphériques simultanément, tels que des clés USB, des disques durs externes, des souris et des claviers, à votre ordinateur portable ou à votre smartphone via un seul port USB de type C. Compact et portable, cet adaptateur est idéal pour une utilisation au bureau, à la maison ou en déplacement. Grâce à sa compatibilité universelle avec une large gamme d\'appareils USB de type C, le HUB USB C UGREEN simplifie la connectivité et facilite la gestion de vos périphériques.',
                'IdDetails' => 32,
                'IdTags' => 32,
                'IdImages' => 32,
                'IdCategorie' => 4
            ]
        ]);
    }
}
